### ISSUE TITLE
Unexpected token is thrown

### ISSUE THREAD

**Issue by MMaurel** [ioBroker/ioBroker.js-controller#1161]
https://github.com/ioBroker/ioBroker.js-controller/blob/74adc2bd41fcf8442b5133592f64f3d5f13d820b/lib/cli/cliPlugin.js#L253

/opt/iobroker/node_modules/iobroker.js-controller/lib/cli/cliPlugin.js:253
                    } catch {
                            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/cli/index.js:19:17)

**Comment by MMaurel** [comment]
Maybe you can replace "} catch {" by "} catch (err) {" ...

**Comment by foxriver76** [comment]
Seems like your Nodejs version is outdated

**Comment by Apollon77** [comment]
Current js.controller supports node.js 10.x+ ...which node.js version you have?

**Comment by MMaurel** [comment]
This was clearly the problem => updating fixed the issue
Bur now, with a recent version, I have another problem which is related with the SIA addon (not directly with the ioBroker)
Thanks for you quick answer !
