### ISSUE TITLE
3.2.1 doesn't start with Redis

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.js-controller#1164]
With lxc debian 10, Node 14.15.1, Npm 6.14.11, iobroker can#t start anymore, here the error logs:
`
2021-01-09 08:47:20.924  - info: host.VMC123-iobroker iobroker Starting node restart.js
2021-01-09 08:47:21.632  - error: host.VMC123-iobroker Could not delete /opt/iobroker/node_modules/iobroker.js-controller/pids.txt: Error: ENOENT: no such file or directory, unlink '/opt/iobroker/node_modules/iobroker.js-controller/pids.txt'
2021-01-09 08:47:22.273  - info: host.VMC123-iobroker iobroker.js-controller version 3.2.1 js-controller starting
2021-01-09 08:47:22.281  - info: host.VMC123-iobroker Copyright (c) 2014-2021 bluefox, 2014 hobbyquaker
2021-01-09 08:47:22.281  - info: host.VMC123-iobroker hostname: VMC123-iobroker, node: v14.15.4
2021-01-09 08:47:22.282  - info: host.VMC123-iobroker ip addresses: 192.168.3.41
2021-01-09 08:47:22.409  - info: host.VMC123-iobroker connected to Objects and States
2021-01-09 08:47:22.530  - info: host.VMC123-iobroker added notifications configuration of host
2021-01-09 08:47:23.372  - error: host.VMC123-iobroker uncaught exception: Installation error or unknown objects database type: 127.0.0.1
2021-01-09 08:47:23.374  - error: host.VMC123-iobroker Error: Installation error or unknown objects database type: 127.0.0.1
    at objectsDbHasServer (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:2640:15)
    at Object.isLocalObjectsDbServer (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:2653:10)
    at startMultihost (/opt/iobroker/node_modules/iobroker.js-controller/main.js:186:44)
    at /opt/iobroker/node_modules/iobroker.js-controller/main.js:532:21
    at checkHost (/opt/iobroker/node_modules/iobroker.js-controller/main.js:933:21)
    at /opt/iobroker/node_modules/iobroker.js-controller/main.js:531:17
    at /opt/iobroker/node_modules/@iobroker/plugin-base/lib/PluginHandler.js:148:109
    at /opt/iobroker/node_modules/@iobroker/plugin-base/lib/PluginHandler.js:133:47
    at /opt/iobroker/node_modules/@iobroker/plugin-base/lib/PluginBase.js:304:17
2021-01-09 08:47:23.384  - info: host.VMC123-iobroker iobroker _restart
2021-01-09 08:47:23.413  - info: host.VMC123-iobroker terminated

`

here iobroker.json

`
ilovegym@VMC123-iobroker:/opt/iobroker$ cat /opt/iobroker/iobroker-data/iobroker.json
{
  "system": {
    "memoryLimitMB": 0,
    "hostname": "",
    "statisticsInterval": 15000,
    "statisticsIntervalComment": "Interval how often the counters for input/output in adapters and controller will be updated"
  },
  "multihostService": {
    "enabled": true,
    "secure": true,
    "password": "3edcfbcce1de120ae6c2af0909623e22"
  },
  "network": {
    "IPv4": true,
    "IPv6": true,
    "bindAddress": null
  },
  "objects": {
    "type": "redis",
    "typeComment": "Possible values: 'file' - [port 9001], redis - [port 6379], couch - [port 5984].",
    "host": "127.0.0.1",
    "port": 6379,
    "user": "",
    "pass": "",
    "noFileCache": false,
    "connectTimeout": 2000,
    "backup": {
      "disabled": false,
      "files": 24,
      "filesComment": "Minimal number of backup files, after the deletion will be executed according to backupTime settings",
      "hours": 48,
      "hoursComment": "All backups older than 48 hours will be deleted. But only if the number of files is greater than of backupNumber",
      "period": 120,
      "periodComment": "by default backup every 2 hours. Time is in minutes. To disable backup set the value to 0",
      "path": "",
      "pathComment": "Absolute path to backup directory or empty to backup in data directory"
    },
    "options": {
      "auth_pass": null,
      "retry_max_delay": 5000
    }
  },
  "states": {
    "type": "redis",
    "typeComment": "Possible values: 'file' - [port 9000], 'redis' - [port 6379].",
    "host": "127.0.0.1",
    "port": 6379,
    "maxQueue": 1000,
    "options": {
      "auth_pass": null,
      "retry_max_delay": 5000
    },
    "backup": {
      "disabled": false,
      "files": 24,
      "filesComment": "Minimal number of backup files, after the deletion will be executed according to backupTime settings",
      "hours": 48,
      "hoursComment": "All backups older than 48 hours will be deleted. But only if the number of files is greater than of backupNumber",
      "period": 120,
      "periodComment": "by default backup every 2 hours. Time is in minutes. To disable backup set the value to 0",
      "path": "",
      "pathComment": "Absolute path to backup directory or empty to backup in data directory"
    }
  },
  "log": {
    "level": "info",
    "maxDays": 7,
    "noStdout": true,
    "transport": {
      "file1": {
        "type": "file",
        "enabled": true,
        "filename": "log/iobroker",
        "fileext": ".log",
        "maxsize": null,
        "maxFiles": null
      },
      "syslog1": {
        "type": "syslog",
        "enabled": false,
        "host": "localhost",
        "host_comment": "The host running syslogd, defaults to localhost.",
        "port_comment": "The port on the host that syslog is running on, defaults to syslogd's default port(514/UDP).",
        "protocol": "udp4",
        "protocol_comment": "The network protocol to log over (e.g. tcp4, udp4, unix, unix-connect, etc).",
        "path_comment": "The path to the syslog dgram socket (i.e. /dev/log or /var/run/syslog for OS X).",
        "facility_comment": "Syslog facility to use (Default: local0).",
        "localhost": "iobroker",
        "localhost_comment": "Host to indicate that log messages are coming from (Default: localhost).",
        "sysLogType_comment": "The type of the syslog protocol to use (Default: BSD).",
        "app_name_comment": "The name of the application (Default: process.title).",
        "eol_comment": "The end of line character to be added to the end of the message (Default: Message without modifications)."
      }
    }
  },
  "dataDirComment": "Always relative to iobroker.js-controller/",
  "dataDir": "../../iobroker-data/"
}ilovegym@VMC123-iobroker:/opt/iobroker$

`

iobroker setup custom:

`
ilovegym@VMC123-iobroker:/opt/iobroker$ iobroker setup custom
Current configuration:
- Objects database:
  - Type: redis
  - Host/Unix Socket: 127.0.0.1
  - Port: 6379
- States database:
  - Type: redis
  - Host/Unix Socket: 127.0.0.1
  - Port: 6379

Type of objects DB [(f)ile, (r)edis], default [redis]: ^C
`

**Comment by Apollon77** [comment]
On one place parameters were exchanged ... only hppened when redis was configured on "127.0.0.1" :-)

**Comment by Apollon77** [comment]
fixed in 3.2.2
