### ISSUE TITLE
Invalid version leaves "iobroker upgrade all" in undefined state

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.js-controller#1207]
Somehow `iobroker upgrade all` fails on my server with the following error output:

```
...
Adapter "hass-mqtt"      is not installed.
(node:3922202) UnhandledPromiseRejectionWarning: TypeError: Invalid Version:
    at new SemVer (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/semver/classes/semver.js:38:13)
    at compare (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/semver/functions/compare.js:3:3)
    at Object.lte (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/semver/functions/lte.js:2:30)
    at showUpgradeDialog (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpgrade.js:304:36)
    at Upgrade.upgradeAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpgrade.js:384:22)
(node:3922202) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3922202) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The repository is `beta` / `latest`. Not sure what is wrong here, it works on the other hosts. But I think the error should be handled differently. Either caught and ignored with a warning output (I'd prefer that) or the process should exit. 

js-controller version is 3.2.8 (but 3.2.7-beta was the same).

**Comment by Garfonso** [comment]
Outpur from iobroker update: 
```
Used repository: beta
hash unchanged, use cached sources
update done
Adapter    "accuweather"   : 1.1.4    , installed 1.1.4
Adapter    "adb"           : 0.0.5
Adapter    "admin"         : 4.2.1    , installed 4.2.1
Adapter    "alarm"         : 1.9.0
Adapter    "alexa2"        : 3.5.4    , installed 3.5.4
Adapter    "alpha2"        : 1.0.0
Adapter    "amazon-dash"   : 1.1.0
Adapter    "artnet"        : 1.2.2
Adapter    "asterisk"      : 1.0.6
Adapter    "asuswrt"       : 1.0.1
Adapter    "b-control-em"  : 0.2.1
Adapter    "backitup"      : 1.8.5
Adapter    "beckhoff"      : 1.2.2
Adapter    "benq"          : 0.2.2
Adapter    "binance"       : 1.1.3
Adapter    "ble"           : 0.12.0
Adapter    "blink4home"    : 0.1.1
Adapter    "bmw"           : 1.4.0
Adapter    "boblight"      : 0.0.1
Adapter    "bosesoundtouch": 0.9.3
Adapter    "botvac"        : 1.0.0    , installed 1.0.0
Adapter    "bring"         : 1.7.7
Adapter    "broadlink2"    : 2.1.5
Adapter    "bsblan"        : 0.2.0
Adapter    "bshb"          : 0.1.10
Adapter    "calendar"      : 1.2.0    , installed 1.2.0
Adapter    "cameras"       : 0.1.3
Adapter    "canbus"        : 1.0.0-beta.6
Adapter    "chromecast"    : 2.3.1
Adapter    "cloud"         : 4.0.1    , installed 4.0.1
Adapter    "comfoair"      : 1.1.2
Adapter    "contact"       : 1.1.3
Adapter    "contactid"     : 1.0.2
Adapter    "coronavirus-statistics": 0.6.7   , installed 0.6.7
Adapter    "corrently"     : 0.0.2
Adapter    "countdown"     : 1.1.0
Adapter    "cul"           : 1.3.4
Adapter    "daikin"        : 1.3.0
Adapter    "daswetter"     : 3.0.4    , installed 3.0.4
Adapter    "deconz"        : 1.3.11
Adapter    "denon"         : 1.10.0
Adapter    "device-reminder": 1.0.6
Adapter    "devices"       : 0.3.15   , installed 0.3.15
Adapter    "digitalstrom"  : 2.0.5
Adapter    "discovergy"    : 0.5.4
Adapter    "discovery"     : 2.5.0    , installed 2.5.0
Adapter    "doorbird"      : 0.1.5    , installed 0.1.5
Adapter    "doorio"        : 1.1.2
Adapter    "ds18b20"       : 1.2.1
Adapter    "dwd"           : 2.7.2
Adapter    "ebus"          : 2.2.3
Adapter    "echarts"       : 0.4.9
Adapter    "ecovacs-deebot": 1.0.10
Adapter    "egigeozone"    : 0.1.2
Adapter    "ekey"          : 1.1.0
Adapter    "email"         : 1.0.7    , installed 1.0.7
Adapter    "emby"          : 1.0.2
Adapter    "energymanager" : 1.2.3
Adapter    "enet"          : 1.0.1
Adapter    "epson_stylus_px830": 0.2.1
Adapter    "eventlist"     : 0.4.2
Adapter    "exchangerates" : 0.0.13
Adapter    "fahrplan"      : 1.0.2
Adapter    "fakeroku"      : 0.2.1
Adapter    "fb-checkpresence": 1.1.0   , installed 1.1.0
Adapter    "feiertage"     : 1.0.19   , installed 1.0.19
Adapter    "fhem"          : 1.5.3    , installed 1.5.3
Adapter    "find-my-iphone": 0.2.17
Adapter    "firetv"        : 1.0.0    , installed 1.0.0
Adapter    "fitbit-api"    : 0.1.1    , installed 0.1.1
Adapter    "flot"          : 1.10.6   , installed 1.10.6
Adapter    "followthesun"  : 0.2.6
Adapter    "foobar2000"    : 2.0.3
Adapter    "fritzbox"      : 0.2.1    , installed 0.2.1
Adapter    "fritzdect"     : 2.1.7    , installed 2.1.7
Adapter    "fronius"       : 1.1.1
Adapter    "frontier_silicon": 0.0.10
Adapter    "fullcalendar"  : 1.1.0    , installed 1.1.0
Adapter    "fullybrowser"  : 2.0.4
Adapter    "g-homa"        : 0.5.3
Adapter    "geofency"      : 0.3.2
Adapter    "go-e"          : 1.0.0
Adapter    "growatt"       : 0.0.17
Adapter    "gruenbeck"     : 0.0.27
Adapter    "habpanel"      : 0.4.3
Adapter    "haier"         : 1.0.3
Adapter    "ham"           : 3.0.2
Adapter    "ham-wemo"      : 1.1.0
Adapter    "harmony"       : 1.2.2
Adapter    "hass"          : 1.0.0
Adapter    "hass-mqtt"     : 0.0.7
Adapter    "heatingcontrol": 2.0.2    , installed 2.0.1 [Updateable]
Adapter    "heos"          : 1.6.2
Adapter    "heytech"       : 1.0.1
Adapter    "hid"           : 0.1.17
Adapter    "hilink"        : 0.2.7
Adapter    "history"       : 1.9.12   , installed 1.9.12
Adapter    "hm-rega"       : 3.0.7
Adapter    "hm-rpc"        : 1.14.31  , installed 1.14.31
Adapter    "hmip"          : 1.6.2
Adapter    "hombot"        : 0.1.3
Adapter    "homeconnect"   : 0.0.31   , installed 0.0.31
Adapter    "homee"         : 1.1.0
Adapter    "homepilot"     : 1.1.4
Adapter    "hp-ilo"        : 1.0.6
Adapter    "hs100"         : 2.0.2    , installed 2.0.2
Adapter    "hue"           : 3.4.0
Adapter    "hue-extended"  : 2.0.0
Adapter    "hyperion"      : 0.0.9
Adapter    "i2c"           : 1.1.1
Adapter    "ical"          : 1.9.0    , installed 1.9.0
Adapter    "icons-addictive-flavour-png": 0.1.0   , installed 0.1.0
Adapter    "icons-fatcow-hosting": 0.1.0   , installed 0.1.0
Adapter    "icons-icons8"  : 0.0.1    , installed 0.0.1
Adapter    "icons-material-png": 0.1.0   , installed 0.1.0
Adapter    "icons-material-svg": 0.1.0   , installed 0.1.0
Adapter    "icons-mfd-png" : 1.0.2    , installed 1.0.2
Adapter    "icons-mfd-svg" : 1.0.2    , installed 1.0.2
Adapter    "icons-open-icon-library-png": 0.1.2   , installed 0.1.3
Adapter    "icons-ultimate-png": 1.0.1   , installed 1.0.1
Adapter    "influxdb"      : 1.9.4    , installed 1.9.4
Adapter    "info"          : 1.7.15   , installed 1.7.15
Adapter    "innogy-smarthome": 0.3.6
Adapter    "intesishome"   : 0.1.2
Adapter    "iogo"          : 0.6.5    , installed 0.6.5
Adapter    "iot"           : 1.8.11   , installed 1.8.11
Adapter    "iqontrol"      : 1.5.6    , installed 1.5.6
Adapter    "jarvis"        : 2.1.0
Adapter    "javascript"    : 4.10.10  , installed 4.10.9 [Updateable]
Adapter    "jeelink"       : 0.1.3
Controller "js-controller" : 3.2.8    , installed 3.2.8
Adapter    "js2fs"         : 0.1.5
Adapter    "kecontact"     : 1.0.1
Adapter    "klf200"        : 1.0.1    , installed 1.0.1
Adapter    "km200"         : 2.0.3
Adapter    "knmi-weather"  : 1.0.0
Adapter    "knx"           : 1.0.42   , installed 1.0.42
Adapter    "kodi"          : 2.0.4
Adapter    "kostal-piko-ba": 1.1.5
Adapter    "kress"         : 2.5.5
Adapter    "lametric"      : 1.1.2
Adapter    "landroid"      : 1.0.3
Adapter    "lcn"           : 1.0.2
Adapter    "legrand-ecocompteur": 1.0.0
Adapter    "letrika_comgw" : 0.0.5
Adapter    "lgtv"          : 1.1.10
Adapter    "lgtv-rs"       : 0.1.0
Adapter    "lgtv11"        : 1.0.5
Adapter    "lifx"          : 0.1.1
Adapter    "lightify"      : 0.2.16
Adapter    "link"          : 0.5.10
Adapter    "linkeddevices" : 1.4.2
Adapter    "linux-control" : 1.1.2
Adapter    "logparser"     : 1.1.0
Adapter    "lovelace"      : 1.4.2    , installed 1.4.2
Adapter    "loxone"        : 2.1.0
Adapter    "luftdaten"     : 1.0.1
Adapter    "lupusec"       : 1.2.9
Adapter    "luxtronik1"    : 0.3.0
Adapter    "material"      : 0.13.9   , installed 0.13.9
Adapter    "maxcube"       : 1.0.2
Adapter    "maxcul"        : 1.3.1
Adapter    "mbus"          : 2.3.1
Adapter    "mclighting"    : 0.1.1
Adapter    "megad"         : 1.2.1
Adapter    "megadd"        : 0.2.0
Adapter    "megaesp"       : 0.1.0
Adapter    "melcloud"      : 1.1.1
Adapter    "mercedesme"    : 0.0.43
Adapter    "mercury"       : 0.1.3
Adapter    "meross"        : 1.5.1
Adapter    "meteoalarm"    : 1.1.1
Adapter    "midea"         : 0.0.6
Adapter    "miele"         : 0.1.5
Adapter    "mielecloudservice": 2.0.3
Adapter    "mihome"        : 1.3.7
Adapter    "mihome-airpurifier": 0.1.8
Adapter    "mihome-lamp"   : 1.1.0
Adapter    "mihome-plug"   : 0.2.1
Adapter    "mihome-vacuum" : 2.1.1
Adapter    "miio"          : 0.0.13
Adapter    "mikrotik"      : 1.0.12
Adapter    "milight"       : 0.3.6
Adapter    "milight-smart-light": 1.2.0
Adapter    "minuvis"       : 1.2.0
Adapter    "mobile"        : 1.0.1    , installed 1.0.1
Adapter    "modbus"        : 3.2.3    , installed 3.2.2 [Updateable]
Adapter    "moma"          : 1.2.7    , installed 1.2.7
Adapter    "mpd"           : 1.0.5    , installed 1.0.5
Adapter    "mqtt"          : 2.3.3    , installed 2.3.2 [Updateable]
Adapter    "mqtt-client"   : 1.3.1
Adapter    "multicast"     : 0.1.5
Adapter    "musiccast"     : 0.1.5    , installed 0.1.5
Adapter    "mydlink"       : 1.1.7    , installed 1.1.7
Adapter    "myq"           : 0.1.1
Adapter    "mysensors"     : 2.0.1
Adapter    "mystrom"       : 0.0.2
Adapter    "mytime"        : 0.6.1
Adapter    "myvbus"        : 0.0.6
Adapter    "nanoleaf-lightpanels": 1.2.0   , installed 1.2.0
Adapter    "net-tools"     : 0.1.1
Adapter    "netatmo"       : 1.3.3
Adapter    "netatmo-crawler": 0.3.9
Adapter    "nibeuplink"    : 0.4.0
Adapter    "nina"          : 0.0.23
Adapter    "node-red"      : 2.0.4    , installed 2.0.4
Adapter    "noolitef"      : 0.0.2
Adapter    "nuki"          : 1.4.3    , installed 1.4.3
Adapter    "nuki-extended" : 2.3.0
Adapter    "nut"           : 1.4.1
Adapter    "octoprint"     : 1.0.6
Adapter    "odl"           : 1.1.4
Adapter    "oilfox"        : 2.1.0
Adapter    "onkyo"         : 2.0.3
Adapter    "onvif"         : 0.4.4    , installed 0.4.4
Adapter    "openhab"       : 1.1.0
Adapter    "openligadb"    : 1.2.0
Adapter    "opentherm"     : 0.1.9
Adapter    "openweathermap": 0.1.0
Adapter    "opi"           : 0.1.1
Adapter    "oppoplayer"    : 0.2.1
Adapter    "owfs"          : 0.6.4
Adapter    "owntracks"     : 1.0.0
Adapter    "panasonic-viera": 1.0.2
Adapter    "parser"        : 1.0.7    , installed 1.0.7
Adapter    "paw"           : 0.3.2    , installed 0.3.2
Adapter    "phantomjs"     : 1.1.2
Adapter    "philips-air"   : 0.1.0
Adapter    "pi-hole"       : 1.3.1
Adapter    "piface"        : 1.0.0
Adapter    "pimatic"       : 0.3.0
Adapter    "ping"          : 1.4.12   , installed 1.4.12
Adapter    "places"        : 1.0.0    , installed 1.0.0
Adapter    "plenticore"    : 2.1.6
Adapter    "plex"          : 0.9.1
Adapter    "plexconnect"   : 0.0.7
Adapter    "pollenflug"    : 1.0.6
Adapter    "procon-ip"     : 1.0.2
Adapter    "proxmox"       : 1.1.0
Adapter    "proxy"         : 1.2.1
Adapter    "pushbullet"    : 0.0.11
Adapter    "pushover"      : 2.0.3
Adapter    "pushsafer"     : 1.0.3
Adapter    "radar2"        : 2.0.1
Adapter    "radiohead"     : 1.1.1
Adapter    "rainbird"      : 0.2.2
Adapter    "rflink"        : 2.1.6
Adapter    "rickshaw"      : 1.0.0    , installed 1.0.0
Adapter    "ring"          : 1.1.3
Adapter    "roadtraffic"   : 0.2.0
Adapter    "robonect"      : 0.1.4
Adapter    "roomba"        : 1.1.1
Adapter    "rpi2"          : 1.2.0    , installed 1.2.0
Adapter    "rssfeed"       : 0.0.30
Adapter    "s7"            : 1.1.9
Adapter    "samsung"       : 0.2.9
Adapter    "sanext"        : 0.0.4
Adapter    "sayit"         : 1.12.2   , installed 1.12.2
Adapter    "sbfspot"       : 4.0.3
Adapter    "scenes"        : 2.3.6    , installed 2.3.4 [Updateable]
Adapter    "schoolfree"    : 0.7.0
Adapter    "schwoerer-ventcube": 1.3.0
Adapter    "senec"         : 1.0.12
Adapter    "seq"           : 0.2.6    , installed 0.2.5 [Updateable]
Adapter    "shelly"        : 4.0.4
Adapter    "shuttercontrol": 1.1.3
Adapter    "sia"           : 1.0.4
Adapter    "siegenia"      : 1.1.0
Adapter    "simple-api"    : 2.5.2    , installed 2.5.2
Adapter    "sma-em"        : 0.6.1-beta.0
Adapter    "smappee"       : 0.2.2
Adapter    "smartcontrol"  : 1.2.1
Adapter    "smartgarden"   : 1.0.2
Adapter    "smartmeter"    : 3.1.9    , installed 3.1.8 [Updateable]
Adapter    "snips"         : 1.5.1
Adapter    "snmp"          : 0.5.0
Adapter    "socketio"      : 3.1.4    , installed 3.1.4
Adapter    "solarlog"      : 2.0.1
Adapter    "solarviewdatareader": 0.2.1
Adapter    "solarwetter"   : 1.0.0    , installed 1.0.0
Adapter    "sonnen"        : 1.7.0
Adapter    "sonoff"        : 2.3.3    , installed 2.3.3
Adapter    "sonos"         : 2.1.1
Adapter    "sonus"         : 0.1.1
Adapter    "sony-bravia"   : 1.0.3
Adapter    "sourceanalytix": 0.4.8    , installed 0.4.8
Adapter    "spotify-premium": 1.0.0
Adapter    "sprinklecontrol": 0.1.2
Adapter    "sql"           : 1.15.5
Adapter    "squeezebox"    : 1.0.0
Adapter    "squeezeboxrpc" : 1.3.3
Adapter    "starline"      : 1.0.0
Adapter    "statistics"    : 1.0.2    , installed 1.0.2
Adapter    "stiebel-isg"   : 1.6.0
Adapter    "stockmarket"   : 0.0.2
Adapter    "sunnyportal"   : 0.1.5
Adapter    "swiss-weather-api": 0.3.2
Adapter    "synology"      : 0.1.18
Adapter    "systeminfo"    : 0.3.1
Adapter    "tado"          : 0.2.5
Adapter    "tahoma"        : 0.3.3
Adapter    "tankerkoenig"  : 2.0.9
Adapter    "telegram"      : 1.7.0    , installed 1.7.0
Adapter    "terminal"      : 0.1.2
Adapter    "tesla-motors"  : 0.3.1
Adapter    "text2command"  : 2.0.7    , installed 2.0.7
Adapter    "tileboard"     : 0.3.1    , installed 0.3.1
Adapter    "tinker"        : 1.1.0
Adapter    "tino"          : 1.0.0
Adapter    "tinyrx4"       : 1.0.0
Adapter    "todoist2"      : 0.8.5
Adapter    "tr-064"        : 4.2.3    , installed 4.2.3
Adapter    "tradfri"       : 2.6.5
Adapter    "trashschedule" : 1.0.3    , installed 1.0.3
Adapter    "tunnelbroker-endpoint-updater": 0.0.1
Adapter    "tuya"          : 3.5.3
Adapter    "tvspielfilm"   : 2.0.1
Adapter    "unifi"         : 0.5.8
Adapter    "unifi-protect" : 0.0.11
Adapter    "upnp"          : 1.0.16
Adapter    "vaillant"      : 0.0.11
Adapter    "valloxmv"      : 1.1.1
Adapter    "vcard"         : 0.0.9
Adapter    "vedirect"      : 0.1.2
Adapter    "velux"         : 0.0.6
Adapter    "viessmann"     : 1.3.3
Adapter    "viessmannapi"  : 1.3.2
Adapter    "virtualpowermeter": 1.3.0
Adapter    "vis"           : 1.3.7    , installed 1.3.7
Adapter    "vis-bars"      : 0.1.4    , installed 0.1.4
Adapter    "vis-canvas-gauges": 0.1.5   , installed 0.1.5
Adapter    "vis-colorpicker": 1.2.0   , installed 1.2.0
Adapter    "vis-fancyswitch": 1.1.0   , installed 1.1.0
Adapter    "vis-google-fonts": 0.1.0   , installed 0.1.0
Adapter    "vis-history"   : 1.0.0    , installed 1.0.0
Adapter    "vis-hqwidgets" : 1.1.7    , installed 1.1.7
Adapter    "vis-icontwo"   : 0.38.0
Adapter    "vis-inventwo"  : 2.7.4
Adapter    "vis-jqui-mfd"  : 1.0.12   , installed 1.0.12
Adapter    "vis-justgage"  : 1.0.2    , installed 1.0.2
Adapter    "vis-keyboard"  : 0.0.2
Adapter    "vis-lcars"     : 1.0.4
Adapter    "vis-map"       : 1.0.4    , installed 1.0.4
Adapter    "vis-material"  : 0.1.3    , installed 0.1.3
Adapter    "vis-material-advanced": 1.3.0
Adapter    "vis-material-webfont": 0.0.3   , installed 0.0.3
Adapter    "vis-materialdesign": 0.4.2
Adapter    "vis-metro"     : 1.1.2    , installed 1.1.2
Adapter    "vis-players"   : 0.1.6    , installed 0.1.6
Adapter    "vis-plumb"     : 1.0.2    , installed 1.0.2
Adapter    "vis-rgraph"    : 0.0.2    , installed 0.0.2
Adapter    "vis-timeandweather": 1.1.7   , installed 1.1.7
Adapter    "vis-weather"   : 2.5.2    , installed 2.5.2
Adapter    "vodafone-speedtest": 0.0.6
Adapter    "volvo"         : 0.0.3
Adapter    "vr200"         : 1.0.0
Adapter    "vw-connect"    : 0.0.25
Adapter    "weatherflow_udp": 0.0.15
Adapter    "weatherunderground": 3.3.0   , installed 3.2.5 [Updateable]
Adapter    "web"           : 3.2.3    , installed 3.2.3
Adapter    "web-speedy"    : 0.2.0
Adapter    "weishaupt-wem" : 0.0.8
Adapter    "whatsapp-cmb"  : 0.1.6
Adapter    "wiffi-wz"      : 2.2.0
Adapter    "wifilight"     : 1.1.0
Adapter    "windows-control": 0.1.5
Adapter    "wlanthermo-nano": 0.1.1
Adapter    "wled"          : 0.5.6
Adapter    "wm-bus"        : 0.3.1
Adapter    "wolf"          : 1.2.1
Adapter    "worx"          : 1.2.7
Adapter    "xbox"          : 0.7.3
Adapter    "xs1"           : 1.0.2
Adapter    "yahka"         : 0.13.1
Adapter    "yamaha"        : 0.4.0    , installed 0.4.0
Adapter    "yeelight-2"    : 1.0.3
Adapter    "youtube"       : 1.0.1
Adapter    "yr"            : 2.0.3
Adapter    "zigbee"        : 1.4.2    , installed 1.4.2
Adapter    "zoneminder"    : 0.3.3
Adapter    "zont"          : 0.5.4
Adapter    "zwave"         : 2.0.1
Adapter    "zwave2"        : 1.8.7
```
So it seems to fail for heating control... not sure why?

Maybe semver Version is important here, too? Therefore a list of installed semvers:
```
achim@Server:/opt/iobroker$ npm list semver
iobroker.inst@1.1.2 /opt/iobroker
├─┬ @serialport/bindings@8.0.7
│ └─┬ prebuild-install@5.3.3
│   └─┬ node-abi@2.13.0
│     └── semver@5.5.0  deduped
├─┬ iobroker@1.1.2
│ └── semver@5.5.0
├─┬ iobroker.admin@4.2.1
│ └── semver@7.3.4
├─┬ iobroker.info@1.7.15
│ └── semver@7.3.4
├─┬ iobroker.iogo@0.6.5
│ ├─┬ firebase@7.24.0
│ │ └─┬ @firebase/firestore@1.18.0
│ │   └─┬ @grpc/grpc-js@1.2.2
│ │     └── semver@6.3.0
│ └─┬ npm@6.14.10
│   ├─┬ init-package-json@1.10.3
│   │ └── semver@5.7.1  deduped
│   ├─┬ libnpm@3.0.1
│   │ └─┬ libnpmpublish@1.1.2
│   │   └── semver@5.7.1  deduped
│   ├─┬ lock-verify@2.1.0
│   │ └── semver@5.7.1  deduped
│   ├─┬ node-gyp@5.1.0
│   │ └── semver@5.7.1  deduped
│   ├─┬ normalize-package-data@2.5.0
│   │ └── semver@5.7.1  deduped
│   ├─┬ npm-install-checks@3.0.2
│   │ └── semver@5.7.1  deduped
│   ├─┬ npm-package-arg@6.1.1
│   │ └── semver@5.7.1  deduped
│   ├─┬ npm-pick-manifest@3.0.2
│   │ └── semver@5.7.1  deduped
│   ├─┬ pacote@9.5.12
│   │ └── semver@5.7.1  deduped
│   ├─┬ read-installed@4.0.3
│   │ └── semver@5.7.1  deduped
│   ├── semver@5.7.1
│   └─┬ update-notifier@2.5.0
│     ├─┬ latest-version@3.1.0
│     │ └─┬ package-json@4.0.1
│     │   └── semver@5.7.1  deduped
│     └─┬ semver-diff@2.1.0
│       └── semver@5.7.1  deduped
├─┬ iobroker.iot@1.8.11
│ ├─┬ canvas@2.6.1
│ │ └─┬ node-pre-gyp@0.11.0
│ │   └── semver@5.5.0  deduped
│ └─┬ sharp@0.26.2
│   └── semver@7.3.4
├─┬ iobroker.javascript@4.10.9
│ └── semver@7.3.4
├─┬ iobroker.js-controller@3.2.8
│ ├─┬ jsonwebtoken@8.5.1
│ │ └── semver@5.7.1
│ └── semver@7.3.4
├─┬ iobroker.lovelace@1.4.2
│ └─┬ pinyin@2.9.1
│   └─┬ nodejieba@2.5.1
│     └─┬ node-pre-gyp@0.14.0
│       └── semver@5.5.0  deduped
├─┬ iobroker.node-red@2.0.4
│ ├─┬ mongodb@3.6.3
│ │ └─┬ require_optional@1.0.1
│ │   └── semver@5.5.0  deduped
│ ├─┬ node-red@1.2.7
│ │ ├─┬ @node-red/runtime@1.2.7
│ │ │ └─┬ @node-red/registry@1.2.7
│ │ │   └── semver@6.3.0
│ │ ├─┬ bcrypt@3.0.6
│ │ │ └─┬ node-pre-gyp@0.12.0
│ │ │   └── semver@5.5.0  deduped
│ │ ├─┬ node-red-admin@0.2.7
│ │ │ └─┬ bcrypt@3.0.8
│ │ │   └─┬ node-pre-gyp@0.14.0
│ │ │     └── semver@5.5.0  deduped
│ │ └── semver@6.3.0
│ └─┬ node-red-node-email@1.8.3
│   └─┬ imap@0.8.19
│     └─┬ utf7@1.0.2
│       └── semver@5.3.0
├─┬ iobroker.onvif@0.4.4
│ ├─┬ sharp@0.25.4
│ │ └── semver@7.3.2
│ └─┬ urllib@2.36.1
│   └─┬ default-user-agent@1.0.0
│     └─┬ os-name@1.0.3
│       └─┬ win-release@1.1.1
│         └── semver@5.5.0  deduped
├─┬ iobroker.sourceanalytix@0.4.8
│ └─┬ npm@6.14.11
│   ├─┬ init-package-json@1.10.3
│   │ └── semver@5.7.1  deduped
│   ├─┬ libnpm@3.0.1
│   │ └─┬ libnpmpublish@1.1.2
│   │   └── semver@5.7.1  deduped
│   ├─┬ lock-verify@2.1.0
│   │ └── semver@5.7.1  deduped
│   ├─┬ node-gyp@5.1.0
│   │ └── semver@5.7.1  deduped
│   ├─┬ normalize-package-data@2.5.0
│   │ └── semver@5.7.1  deduped
│   ├─┬ npm-install-checks@3.0.2
│   │ └── semver@5.7.1  deduped
│   ├─┬ npm-package-arg@6.1.1
│   │ └── semver@5.7.1  deduped
│   ├─┬ npm-pick-manifest@3.0.2
│   │ └── semver@5.7.1  deduped
│   ├─┬ pacote@9.5.12
│   │ └── semver@5.7.1  deduped
│   ├─┬ read-installed@4.0.3
│   │ └── semver@5.7.1  deduped
│   ├── semver@5.7.1
│   └─┬ update-notifier@2.5.0
│     ├─┬ latest-version@3.1.0
│     │ └─┬ package-json@4.0.1
│     │   └── semver@5.7.1  deduped
│     └─┬ semver-diff@2.1.0
│       └── semver@5.7.1  deduped
└─┬ iobroker.vis-weather@2.5.2
  └─┬ npm@6.9.0
    ├─┬ init-package-json@1.10.3
    │ └── semver@5.5.0  deduped
    ├─┬ libnpm@2.0.1
    │ └─┬ libnpmpublish@1.1.3
    │   └── semver@5.7.1
    ├─┬ libnpmaccess@4.0.0
    │ └─┬ npm-package-arg@8.0.1
    │   └── semver@7.3.2
    ├─┬ libnpmorg@2.0.0
    │ └─┬ npm-registry-fetch@8.0.0
    │   └─┬ npm-package-arg@8.0.1
    │     └── semver@7.3.2
    ├─┬ libnpmsearch@3.0.0
    │ └─┬ npm-registry-fetch@8.0.0
    │   └─┬ npm-package-arg@8.0.1
    │     └── semver@7.3.2
    ├─┬ libnpmteam@2.0.1
    │ └─┬ npm-registry-fetch@8.0.0
    │   └─┬ npm-package-arg@8.0.1
    │     └── semver@7.3.2
    ├─┬ libnpx@10.2.3
    │ └─┬ yargs@11.1.1
    │   └─┬ os-locale@3.1.0
    │     └─┬ execa@1.0.0
    │       └─┬ cross-spawn@6.0.5
    │         └── semver@5.5.0  deduped
    ├─┬ lock-verify@2.2.0
    │ └── semver@5.5.0  deduped
    ├─┬ node-gyp@3.8.0
    │ └── semver@5.3.0
    ├─┬ normalize-package-data@2.5.0
    │ └── semver@5.7.1  deduped
    ├─┬ npm-install-checks@3.0.2
    │ └── semver@5.5.0  deduped
    ├─┬ npm-lifecycle@2.1.1
    │ └─┬ node-gyp@4.0.0
    │   └── semver@5.3.0
    ├─┬ npm-package-arg@6.1.1
    │ └── semver@5.7.1
    ├─┬ npm-pick-manifest@2.2.3
    │ └── semver@5.5.0  deduped
    ├─┬ npm-profile@5.0.1
    │ └─┬ npm-registry-fetch@8.0.0
    │   └─┬ npm-package-arg@8.0.1
    │     └── semver@7.3.2
    ├─┬ pacote@9.5.12
    │ ├─┬ normalize-package-data@2.4.0
    │ │ └── semver@5.5.0  deduped
    │ ├─┬ npm-pick-manifest@3.0.2
    │ │ └── semver@5.7.1  deduped
    │ └── semver@5.7.1
    ├─┬ read-installed@4.0.3
    │ └── semver@5.5.0  deduped
    ├── semver@5.7.1
    └─┬ update-notifier@2.5.0
      ├─┬ latest-version@3.1.0
      │ └─┬ package-json@4.0.1
      │   └── semver@5.5.0  deduped
      └─┬ semver-diff@2.1.0
        └── semver@5.5.0  deduped
```

**Comment by Apollon77** [comment]
I will try to catch such errors in 3.2.9

**Comment by Anzic23** [comment]
caught the same error. What needs to be done to fix it? js-controller 3.3.22
```
root@iobroker:/opt/iobroker# iob update
Used repository: Beta (latest)
hash unchanged, use cached sources
update done
/opt/iobroker/node_modules/semver/classes/semver.js:38
      throw new TypeError(`Invalid Version: ${version}`)
      ^

TypeError: Invalid Version: 1.6.0o
    at new SemVer (/opt/iobroker/node_modules/semver/classes/semver.js:38:13)
    at compare (/opt/iobroker/node_modules/semver/functions/compare.js:3:3)
    at Object.gte (/opt/iobroker/node_modules/semver/functions/gte.js:2:30)
    at Object.upToDate (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:153:19)
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupRepo.js:244:28
    at Array.forEach (<anonymous>)
    at updateInfo (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupRepo.js:241:30)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupRepo.js:208:37)
    at processImmediate (internal/timers.js:463:21)
root@iobroker:/opt/iobroker#

```

**Comment by foxriver76** [comment]
Fixe in https://github.com/ioBroker/ioBroker.js-controller/commit/3d44a9d2526ff4da47047a838619404a01fc127a

**Comment by Anzic23** [comment]
> Fixed in [3d44a9d](https://github.com/ioBroker/ioBroker.js-controller/commit/3d44a9d2526ff4da47047a838619404a01fc127a)
> 
> I think this is not fixed before next controller release

Do I need to install the controller version 4.0.0-alpha? Can I somehow fix it on the current version? Make these fixes in setupRepo.js and tools.js ?

**Comment by foxriver76** [comment]
The adapter which has the invalid version should be fixed asap, please do NOT install a controller alpha version.

**Comment by foxriver76** [comment]
Can you check in admin which of the adapters offers the invalid upgrade to version `1.6.0o`?

**Comment by Apollon77** [comment]
I would more assume that one adater installed has such an weird number ... I could not imagine that the repo is wrong, needs to be a local adapter. So, did you installed any GitHub versions or such?

**Comment by Anzic23** [comment]
![image](https://user-images.githubusercontent.com/37106885/149678634-1e12abd1-3a7e-4d64-b7bd-7c96a257fd08.png)
zigbee
Updated via github - the error is gone.

**Comment by Apollon77** [comment]
The interesting question stays ... where this version came from

**Comment by Anzic23** [comment]
> The interesting question stays ... where this version came from

from the developer, he gave me a link so that I would install this version, since the adapter did not start. Perhaps it was some kind of temporary version, with specific edits for my case.
