### ISSUE TITLE
Zigbee adapter crash on setState

### ISSUE THREAD

**Issue by asgothian** [ioBroker/ioBroker.js-controller#1215]
Hello,

with the update to js-controller 3.2, the zigbee adapter is prone to crash when trying to set a value to an object, which cannot always be caught in the adapter itself.

An attempt to prevent the error with a try/catch block fails.

The code used is

```
try {
     this.adapter.setState(id, value, true);
} catch { }
```

The ID is correct, the value is causing the issue, when the value is
```
{"effect":"firework","speed":9.375,"colors":[{"r":255,"g":0,"b":0},{"r":0,"g":255,"b":0},{"r":0,"g":0,"b":255}]}
```

```
2021-01-28 16:42:32.163 - error: zigbee.0 (2643) The state contains the forbidden properties effect, speed, colors!
--
2021-01-28 16:42:32.167 - error: zigbee.0 (2643) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-01-28 16:42:32.168 - error: zigbee.0 (2643) unhandled promise rejection: The state contains the forbidden properties effect, speed, colors!
2021-01-28 16:42:32.169 - error: zigbee.0 (2643) Error: The state contains the forbidden properties effect, speed, colors!
at validateSetStateObjectArgument (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5848:23)
at Zigbee.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5935:21)
at Immediate.adapter.getObject (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:253:38)
at runCallback (timers.js:706:11)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)
2021-01-28 16:42:32.170 - error: zigbee.0 (2643) The state contains the forbidden properties effect, speed, colors!
```

with the js controller 3.1.x this would generate a warning.

While i can understand that the attempt to set a state with forbidden properties raises an error and the state does not get set i can not understand why the adapter is crashed due to this error.

This may not be directly an issue for js-controller, but the change in js-controller does cause the system to crash. The function setState itself is defined in @iobroker/adapter-core.

A.

**Comment by foxriver76** [comment]
either use `setStateAsync` inside try catch block or use callback style and check for the err.

**Comment by Apollon77** [comment]
In fact you can use the error callback as existing all the time or, as @foxriver76 proposed use await with the Async method in a try/catch

**Comment by Apollon77** [comment]
@asgothian On the other side ... try catch is not really the solution here. you need to make sure that you do not have such invalid state objects that you want to set! Else it is semply NOT set at all with js.cotnroller 3.2 ... so basically this is "The way to go"

**Comment by foxriver76** [comment]
Ah now I see if you set a JSON value you have to use `setState(Id, {val: {„effect“: ...}}, true)` Else it Id assumed as an iob state object

**Comment by foxriver76** [comment]
Or stringify the value of course

**Comment by asgothian** [comment]
Actually, i don't want the value to be set at all.. the fact that the adapter reaches there is an error which is not easily fixed, as it is caused by raw transmission data getting al the way through. Catching this 'correctly' is one of the tasks we have identified. I was aware of the issue due to the warnings we had before, and i thought i had eliminated those since none were reported anymore, but apparently i was mistaken.

For now we use the async/try/catch method to ensure nothing dies, and raise errors in the log for each case we get.

**Comment by Apollon77** [comment]
but then you  ould check the "typeof value !== 'object' && value !==null" and only log this case ...

**Comment by asgothian** [comment]
I have been thinking that too, but am not sure that function is never called with valid objects - yet.
