### ISSUE TITLE
CLI iobroker upgrade fails

### ISSUE THREAD

**Issue by Grothesk242** [ioBroker/ioBroker.js-controller#1303]
With latest js-controller 3.3.1 the upgrade via CLI fails with following message in STDOUT

```
pi@raspberrypi:~ $ nodejs -v && npm -v && iobroker -v
v12.22.1
6.14.12
3.3.1
pi@raspberrypi:~ $ iobroker upgrade
Uncaught Rejection: TypeError: Cannot read property 'indexOf' of undefined
    at Upgrade.upgradeAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpgrade.js:328:21)
    at Upgrade._upgradeAdapterHelper (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpgrade.js:156:14)
    at Upgrade.upgradeAdapterHelper (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpgrade.js:136:18)
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:989:37
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:2615:45)
    at processImmediate (internal/timers.js:463:21)
```

**Comment by Apollon77** [comment]
Thank you!, WIll be fixed in 3.3.2
