### ISSUE TITLE
Log Level of an adapter instance has no effect to transfered log messages to Seq

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.js-controller#1322]
Admin 5.0.11
js-controller 3.3.5

I ran [Seq ](https://datalust.co/seq)as a logger and configured this in the expert settings in Admin5. The log data arrive in Seq as expected :-)

In the configuration for Seq in Admin5 the log level  is set in my configuration to Info (if I set this Seq log level to debug I will receive for all adapters th debug logs but this is not helpfull if you want only the debug level for a single adapter).

If I now set the log level for a adapter instance from Info to Debug, the new debug information are displayed in the iobroker log, but not in Seq.

It would be great if the selected log level of an instance has an affect to the log messages for Seq as well.

**Comment by Apollon77** [comment]
does "debug" come to seq too if you set the "loglevel" in the seq basic settinsgs tzo debug?
I would expect that the setting in the "seq" thingy defines the" maximum loglevel send to seq" and if this is "Info" then also only "info" is send (and warn, error)

**Comment by Feuer-sturm** [comment]
@Apollon77 If I set loglevel to "debug" in the seq basic settings then the I receive for all adapters the debug logs in Seq. None  of the adapter instances is set to "debug".

So the seq basic settings is not the maximum level which is transmitted, it switches the log level for the whole iobroker system from info to debug.

**Comment by Apollon77** [comment]
Can you try to manually adjust iobroker.json file please and remove this "logLevel" entry in the seq transport ... does it work then?

**Comment by Feuer-sturm** [comment]
@Apollon77 I did the following steps
- Set debug level in seq basic settings in Admin 5
- remove debug value in attribute level
```
      "seq1": {
        "type": "seq",
        "enabled": true,
        "serverUrl": "http://192.168.178.73:5341",
        "serverUrlComment": "The http(s) URL including port of the seq server. If you use HTTPS a real certificate is needed; se$
        "apiKey": "DpMCJBOaFz9jKbGKTozU",
        "apiKeyComment": "The apiKey of the seq system",
        "level": "",
        "eol": ""
      }
```
- set in one instance (proxmox) log level to debug

In ioBroker log the debug logs from proxmox are inclueded. In Seq no debug logs for proxmox are available

**Comment by Apollon77** [comment]
Hm ... then we need to dig deep in winston why it is that way :-(

**Comment by foxriver76** [comment]
Plan is to change to https://github.com/datalust/winston-seq

**Comment by foxriver76** [comment]
@Feuer-sturm if you have a test system you could try the current development version, we have ported to another seq module which hopefully fixes this issue too. Unfortunately nobody has tested it until now. 

If you want to give it a try, you can install the dev version by calling 

`npm i iobroker.js-controller@dev --production` inside your `/opt/iobroker/` folder.

**Comment by Feuer-sturm** [comment]
@foxriver76 Sure, I can test it in the next days and give a feedback.

**Comment by Apollon77** [comment]
@arteck @DutchmenNL ... please put your test reults also here!

**Comment by Feuer-sturm** [comment]
Here my first feedback

## Run 1
Host Settings
![grafik](https://user-images.githubusercontent.com/25422320/148127886-14051018-e994-4173-8063-4f2a75459002.png)
![grafik](https://user-images.githubusercontent.com/25422320/148127938-3968a8d4-8b04-43a5-b416-c41e0381dd6c.png)


Debug messages for ical.5 are activated. In the log of iobroker the debug messages are available. In Seq no debug messages were received.

iobroker log:

```
2022-01-04 22:30:11.355 - debug: ical.5 (4903) Checking unprocessed event 18 null 3Schicht = false, state = false
2022-01-04 22:30:11.355 - debug: ical.5 (4903) Checking unprocessed event 19 null 3Schicht = false, state = false
2022-01-04 22:30:11.356 - debug: ical.5 (4903) Checking unprocessed event 20 null 3Schicht = false, state = false
2022-01-04 22:30:12.971 - info: dwd.0 (4892) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2022-01-04 22:30:13.523 - info: host.ioBrokerTestsystem instance system.adapter.dwd.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2022-01-04 22:30:16.366 - debug: ical.5 (4903) Plugin sentry destroyed
2022-01-04 22:30:16.367 - info: ical.5 (4903) Terminated (NO_ERROR): Without reason
2022-01-04 22:30:16.917 - info: host.ioBrokerTestsystem instance system.adapter.ical.5 terminated with code 0 (NO_ERROR)
```

Seq Log:
```
04 Jan 2022 22:30:16.919 iobrokerTestsystem host.ioBrokerTestsystem instance system.adapter.ical.5 terminated with code 0 (NO_ERROR)
04 Jan 2022 22:30:13.525 iobrokerTestsystem host.ioBrokerTestsystem instance system.adapter.dwd.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
04 Jan 2022 22:30:11.203 iobrokerTestsystem ical.5 (4903) processing URL: ioBrokerTesting https://calendar.google.com/calendar/ical/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/basic.ics
04 Jan 2022 22:30:10.749 iobrokerTestsystem ical.5 (4903) starting. Version 1.11.6 in /opt/iobroker/node_modules/iobroker.ical, node: v14.18.1, js-controller: 4.0.0-alpha.39-20220104-4a58ced4
04 Jan 2022 22:30:04.941 iobrokerTestsystem dwd.0 (4892) starting. Version 2.7.7 in /opt/iobroker/node_modules/iobroker.dwd, node: v14.18.1, js-controller: 4.0.0-alpha.39-20220104-4a58ced4
04 Jan 2022 22:30:04.383 iobrokerTestsystem host.ioBrokerTestsystem instance system.adapter.ical.5 started with pid 4903 
```

## Run 2 - Changing host seq settings to debug
Host settings:
![grafik](https://user-images.githubusercontent.com/25422320/148132639-b1bf80f6-b6bc-4963-b133-c8e93921cd59.png)

Seq log:
Debug messages are available but Seq receives the debug messages from all adapters and not only from ical.5


## Run 3 - Not all errors from iobroker log are transported to SEQ
During start of iobroker the following error are available in iobroker log but not in Seq log

iobroker log
```
2022-01-04 23:33:15.310 - info: nina.0 (6080) starting. Version 0.0.25 in /opt/iobroker/node_modules/iobroker.nina, node: v14.18.1, js-controller: 4.0.0-alpha.39-20220104-4a58ced4
2022-01-04 23:33:15.463 - info: nina.0 (6080) Found AGS for: xxx
2022-01-04 23:33:15.797 - error: nina.0 (6080) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-01-04 23:33:15.811 - error: nina.0 (6080) unhandled promise rejection: Cannot read property 'members' of undefined
2022-01-04 23:33:15.818 - error: nina.0 (6080) TypeError: Cannot read property 'members' of undefined
at Object.removeIdFromAllEnums (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2560:36)
at Immediate. (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/lib/adapter/adapter.js:3584:41)
at runNextTicks (internal/process/task_queues.js:60:5)
at processImmediate (internal/timers.js:437:9)
2022-01-04 23:33:15.823 - error: nina.0 (6080) Cannot read property 'members' of undefined
2022-01-04 23:33:15.829 - error: nina.0 (6080) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-01-04 23:33:15.835 - error: nina.0 (6080) unhandled promise rejection: Cannot read property 'members' of undefined
2022-01-04 23:33:15.838 - error: nina.0 (6080) TypeError: Cannot read property 'members' of undefined
at Object.removeIdFromAllEnums (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2560:36)
at Immediate. (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/lib/adapter/adapter.js:3584:41)
at runNextTicks (internal/process/task_queues.js:60:5)
at processImmediate (internal/timers.js:437:9)
2022-01-04 23:33:15.840 - error: nina.0 (6080) Cannot read property 'members' of undefined
2022-01-04 23:33:15.843 - error: nina.0 (6080) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-01-04 23:33:15.850 - error: nina.0 (6080) unhandled promise rejection: Cannot read property 'members' of undefined
2022-01-04 23:33:15.852 - error: nina.0 (6080) TypeError: Cannot read property 'members' of undefined
at Object.removeIdFromAllEnums (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2560:36)
at Immediate. (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/lib/adapter/adapter.js:3584:41)
2022-01-04 23:33:15.857 - error: nina.0 (6080) Cannot read property 'members' of undefined
2022-01-04 23:33:15.870 - info: nina.0 (6080) terminating
2022-01-04 23:33:15.880 - warn: nina.0 (6080) Terminated (UNCAUGHT_EXCEPTION): Without reason
```

Seq log:
```
04 Jan 2022 23:33:17.265 iobrokerTestsystem host.ioBrokerTestsystem Restart adapter system.adapter.nina.0 because enabled
04 Jan 2022 23:33:17.263 iobrokerTestsystem host.ioBrokerTestsystem instance system.adapter.nina.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
04 Jan 2022 23:33:16.175 iobrokerTestsystem host.ioBrokerTestsystem instance system.adapter.info.0 started with pid 6110
04 Jan 2022 23:33:12.368 iobrokerTestsystem simple-api.0 (6065) http server listening on port 8087 
```


The same I can see with daswetter.0 adapter

iobroker log
```
2022-01-04 23:33:40.726 - warn: coronavirus-statistics.0 (6039) Could not remove coronavirus-statistics.0.Germany.Bundesland.Hessen._Impfungen.rkiZweitimpfungenKumulativ from enums: Cannot read property 'members' of undefined
2022-01-04 23:33:41.479 - error: daswetter.0 (5956) force terminate
2022-01-04 23:33:41.485 - warn: daswetter.0 (5956) Terminated (UNKNOWN_ERROR): Without reason
2022-01-04 23:33:41.787 - warn: coronavirus-statistics.0 (6039) Could not remove coronavirus-statistics.0.Germany.Bundesland.Rheinland-Pfalz._Impfungen.rkiZweitimpfungenKumulativ from enums: Cannot read property 'members' of undefined
2022-01-04 23:33:42.068 - warn: daswetter.0 (5956) get state error: Connection is closed.
2022-01-04 23:33:42.082 - error: daswetter.0 (5956) exception in await insertIntoList [Error: DB closed]
2022-01-04 23:33:42.156 - error: daswetter.0 (5956) Cannot check object existence of "daswetter.0.NextHours.Location_1.Day_4.Hour_8.snowline_value": Connection is closed.
2022-01-04 23:33:42.159 - error: daswetter.0 (5956) exception in await insertIntoList [Error: Could not check object existence of daswetter.0.NextHours.Location_1.Day_4.Hour_8.snowline_value: Cannot check object existence of "daswetter.0.NextHours.Location_1.Day_4.Hour_8.snowline_value": Connection is closed.]
2022-01-04 23:33:42.161 - error: daswetter.0 (5956) Cannot check object existence of "daswetter.0.NextHours.Location_1.Day_4.Hour_8.windchill_value": Connection is closed.
2022-01-04 23:33:42.166 - error: daswetter.0 (5956) exception in await insertIntoList [Error: Could not check object existence of daswetter.0.NextHours.Location_1.Day_4.Hour_8.windchill_value: Cannot check object existence of "daswetter.0.NextHours.Location_1.Day_4.Hour_8.windchill_value": Connection is closed.]
2022-01-04 23:33:42.187 - error: daswetter.0 (5956) Cannot check object existence of "daswetter.0.NextHours.Location_1.Day_4.sunshineDuration": Connection is closed.
2022-01-04 23:33:42.190 - error: daswetter.0 (5956) exception in await insertIntoList [Error: Could not check object existence of daswetter.0.NextHours.Location_1.Day_4.sunshineDuration: Cannot check object existence of "daswetter.0.NextHours.Location_1.Day_4.sunshineDuration": Connection is closed.]
2022-01-04 23:33:42.224 - error: daswetter.0 (5956) Cannot check object existence of "daswetter.0.NextHours.Location_1.Day_5": Connection is closed.
2022-01-04 23:33:42.226 - error: daswetter.0 (5956) exception in await insertIntoList [Error: Could not check object existence of daswetter.0.NextHours.Location_1.Day_5: Cannot check object existence of "daswetter.0.NextHours.Location_1.Day_5": Connection is closed.]
2022-01-04 23:33:42.238 - error: daswetter.0 (5956) Cannot check object existence of "daswetter.0.NextHours.Location_1.Day_5.day_name": Connection is closed.
2022-01-04 23:33:42.398 - error: host.ioBrokerTestsystem instance system.adapter.daswetter.0 terminated with code 15 (UNKNOWN_ERROR)
```

Seq log

```
04 Jan 2022 23:33:43.462 iobrokerTestsystem coronavirus-statistics.0 (6039) Could not remove coronavirus-statistics.0.Germany.Bundesland.Baden-Württemberg._Impfungen.rkiZweitimpfungenKumulativ from enums: Cannot read property 'members' of undefined
04 Jan 2022 23:33:42.400 iobrokerTestsystem host.ioBrokerTestsystem instance system.adapter.daswetter.0 terminated with code 15 (UNKNOWN_ERROR)
04 Jan 2022 23:33:41.790 iobrokerTestsystem coronavirus-statistics.0 (6039) Could not remove coronavirus-statistics.0.Germany.Bundesland.Rheinland-Pfalz._Impfungen.rkiZweitimpfungenKumulativ from enums: Cannot read property 'members' of undefined
04 Jan 2022 23:33:40.728 iobrokerTestsystem coronavirus-statistics.0 (6039) Could not remove coronavirus-statistics.0.Germany.Bundesland.Hessen._Impfungen.rkiZweitimpfungenKumulativ fr
```

**Comment by foxriver76** [comment]
So to sum it up the problems are:

- seq always applies the log level from the seq config not respecting the adapter log level
- some logs are not sent to seq (I don't see a pattern yet)

For the second one you could start the controller from command line and check for log lines with `SEQ error:`

To start from command line on linux: `node /opt/iobroker/node_modules/iobroker.js-controller/main.js`

**Comment by Feuer-sturm** [comment]
@foxriver76 I executed the command you mentioned. 
During startup of iobroker there were once again the error messages from daswetter.0 which are available in iobroker log but not in SEQ.

This is the output in the terminal:

```
proxmox@ioBrokerTestsystem:/$ node /opt/iobroker/node_modules/iobroker.js-controller/main.js
host.ioBrokerTestsystem check instance "system.adapter.admin.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.javascript.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.telegram.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.scenes.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.influxdb.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.history.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.ical.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.ical.1" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.ical.2" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.ical.3" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.hm-rpc.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.hm-rega.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.tr-064.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.hue.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.ical.4" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.mqtt.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.samsung-community.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.ical.5" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.web.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.vis.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.vis-timeandweather.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.vis-metro.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.vis-jqui-mfd.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.vis-map.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.tankerkoenig.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.vis-justgage.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.vis-history.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.fritzbox.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.daswetter.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.valloxmv.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.proxmox.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.socketio.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.vis-materialdesign.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.logparser.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.spotify-premium.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.fully-tablet-control.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.rainbird.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.dwd.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.worx.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.vis-fancyswitch.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.unifi.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.coronavirus-statistics.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.sayit.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.vis-google-fonts.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.simple-api.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.seq.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.nina.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.web-speedy.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.backitup.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.trashschedule.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.history.1" for host "ioBrokerNew"
host.ioBrokerTestsystem check instance "system.adapter.info.0" for host "ioBrokerTestsystem"
host.ioBrokerTestsystem check instance "system.adapter.benchmark.0" for host "ioBrokerTestsystem"
================================== > LOG REDIRECT system.adapter.admin.0 => true [system.adapter.admin.0.logging]
Cannot parse "/Hintergrundbild/vis-views.json
Cannot parse "/Muellicons/vis-views.json
Cannot parse "/bewaesserung/vis-views.json
Cannot parse "/daswettercom/vis-views.json
Cannot parse "/spotify/vis-views.json
Cannot parse "/unifi/vis-views.json
Send diag info: {"uuid":"e9b6d157-03dd-1c64-fcd9-ec7c8d6990bd","language":"de","country":"Germany","hosts":[{"version":"4.0.0","platform":"Javascript/Node.js","type":"linux"},{"version":"3.3.22","platform":"Javascript/Node.js","type":"linux"}],"node":"v14.18.1","arch":"x64","adapters":{"admin":{"version":"5.2.3","platform":"Javascript/Node.js"},"ical":{"version":"1.11.6","platform":"Javascript/Node.js"},"web":{"version":"3.4.16","platform":"Javascript/Node.js"},"vis":{"version":"1.4.7","platform":"Javascript/Node.js"},"vis-timeandweather":{"version":"1.1.7","platform":"Javascript/Node.js"},"fritzbox":{"version":"0.3.1","platform":"Javascript/Node.js"},"vis-metro":{"version":"1.1.2","platform":"Javascript/Node.js"},"vis-jqui-mfd":{"version":"1.0.12","platform":"Javascript/Node.js"},"vis-map":{"version":"1.0.4","platform":"Javascript/Node.js"},"icons-mfd-svg":{"version":"1.0.2","platform":"javascript/Node.js"},"icons-mfd-png":{"version":"1.0.2","platform":"javascript/Node.js"},"tankerkoenig":{"version":"2.1.1","platform":"javascript/Node.js"},"vis-justgage":{"version":"1.0.2","platform":"Javascript/Node.js"},"javascript":{"version":"5.2.18","platform":"Javascript/Node.js"},"vis-history":{"version":"1.0.0","platform":"Javascript/Node.js"},"telegram":{"version":"1.10.0","platform":"Javascript/Node.js"},"icons-ultimate-png":{"version":"1.0.1","platform":"javascript/Node.js"},"radar":{"version":"1.1.3","platform":"Javascript/Node.js"},"daswetter":{"version":"3.0.9","platform":"Javascript/Node.js"},"hm-rpc":{"version":"1.15.0","platform":"Javascript/Node.js"},"hm-rega":{"version":"3.0.33","platform":"Javascript/Node.js"},"valloxmv":{"version":"1.1.3","platform":"Javascript/Node.js"},"icons-material-png":{"version":"0.1.0","platform":"javascript/Node.js"},"scenes":{"version":"2.3.8","platform":"Javascript/Node.js"},"proxmox":{"version":"1.3.4","platform":"Javascript/Node.js"},"influxdb":{"version":"2.4.0","platform":"Javascript/Node.js"},"socketio":{"version":"3.1.5","platform":"Javascript/Node.js"},"tr-064":{"version":"4.2.15","platform":"Javascript/Node.js"},"vis-materialdesign":{"version":"0.5.9","platform":"Javascript/Node.js"},"logparser":{"version":"1.1.0","platform":"Javascript/Node.js"},"simple-api":{"version":"2.6.2","platform":"Javascript/Node.js"},"spotify-premium":{"version":"1.1.4","platform":"Javascript/Node.js"},"fully-tablet-control":{"version":"0.3.4-0","platform":"Javascript/Node.js"},"rainbird":{"version":"0.2.3","platform":"Javascript/Node.js"},"dwd":{"version":"2.7.7","platform":"Javascript/Node.js"},"worx":{"version":"1.5.5","platform":"Javascript/Node.js"},"vis-fancyswitch":{"version":"1.1.0","platform":"Javascript/Node.js"},"unifi":{"version":"0.5.10","platform":"Javascript/Node.js"},"coronavirus-statistics":{"version":"0.8.7","platform":"Javascript/Node.js"},"hue":{"version":"3.5.31","platform":"Javascript/Node.js"},"sayit":{"version":"1.12.3","platform":"Javascript/Node.js"},"vis-google-fonts":{"version":"1.0.3","platform":"Javascript/Node.js"},"mqtt":{"version":"2.4.1","platform":"Javascript/Node.js"},"seq":{"version":"0.2.10","platform":"Javascript/Node.js"},"samsung-community":{"version":"0.5.0","platform":"Javascript/Node.js"},"nina":{"version":"0.0.25","platform":"Javascript/Node.js"},"web-speedy":{"version":"0.2.0","platform":"Javascript/Node.js"},"backitup":{"version":"2.2.2","platform":"Javascript/Node.js"},"trashschedule":{"version":"1.4.1","platform":"Javascript/Node.js"},"history":{"version":"1.10.5","platform":"Javascript/Node.js"},"discovery":{"version":"2.7.5","platform":"Javascript/Node.js"},"info":{"version":"1.9.16","platform":"Javascript/Node.js"},"benchmark":{"version":"0.4.0","platform":"Javascript/Node.js"},"devices":{"version":"1.0.9","platform":"Javascript/Node.js"}},"statesType":"file","objectsType":"file","model":"Intel(R) Celeron(R) CPU  N3150  @ 1.60GHz","cpus":4,"mem":3145728000,"ostype":"Linux","vis":698}
/bin/sh: 1: iw: not found

/bin/sh: 1: iw: not found

/bin/sh: 1: hcitool: not found

Cannot parse "/Hintergrundbild/vis-views.json
Cannot parse "/Muellicons/vis-views.json
Cannot parse "/bewaesserung/vis-views.json
Cannot parse "/daswettercom/vis-views.json
Cannot parse "/spotify/vis-views.json
Cannot parse "/unifi/vis-views.json
Send diag info: {"uuid":"e9b6d157-03dd-1c64-fcd9-ec7c8d6990bd","language":"de","country":"Germany","hosts":[{"version":"4.0.0","platform":"Javascript/Node.js","type":"linux"},{"version":"3.3.22","platform":"Javascript/Node.js","type":"linux"}],"node":"v14.18.1","arch":"x64","adapters":{"admin":{"version":"5.2.3","platform":"Javascript/Node.js"},"ical":{"version":"1.11.6","platform":"Javascript/Node.js"},"web":{"version":"3.4.16","platform":"Javascript/Node.js"},"vis":{"version":"1.4.7","platform":"Javascript/Node.js"},"vis-timeandweather":{"version":"1.1.7","platform":"Javascript/Node.js"},"fritzbox":{"version":"0.3.1","platform":"Javascript/Node.js"},"vis-metro":{"version":"1.1.2","platform":"Javascript/Node.js"},"vis-jqui-mfd":{"version":"1.0.12","platform":"Javascript/Node.js"},"vis-map":{"version":"1.0.4","platform":"Javascript/Node.js"},"icons-mfd-svg":{"version":"1.0.2","platform":"javascript/Node.js"},"icons-mfd-png":{"version":"1.0.2","platform":"javascript/Node.js"},"tankerkoenig":{"version":"2.1.1","platform":"javascript/Node.js"},"vis-justgage":{"version":"1.0.2","platform":"Javascript/Node.js"},"javascript":{"version":"5.2.18","platform":"Javascript/Node.js"},"vis-history":{"version":"1.0.0","platform":"Javascript/Node.js"},"telegram":{"version":"1.10.0","platform":"Javascript/Node.js"},"icons-ultimate-png":{"version":"1.0.1","platform":"javascript/Node.js"},"radar":{"version":"1.1.3","platform":"Javascript/Node.js"},"daswetter":{"version":"3.0.9","platform":"Javascript/Node.js"},"hm-rpc":{"version":"1.15.0","platform":"Javascript/Node.js"},"hm-rega":{"version":"3.0.33","platform":"Javascript/Node.js"},"valloxmv":{"version":"1.1.3","platform":"Javascript/Node.js"},"icons-material-png":{"version":"0.1.0","platform":"javascript/Node.js"},"scenes":{"version":"2.3.8","platform":"Javascript/Node.js"},"proxmox":{"version":"1.3.4","platform":"Javascript/Node.js"},"influxdb":{"version":"2.4.0","platform":"Javascript/Node.js"},"socketio":{"version":"3.1.5","platform":"Javascript/Node.js"},"tr-064":{"version":"4.2.15","platform":"Javascript/Node.js"},"vis-materialdesign":{"version":"0.5.9","platform":"Javascript/Node.js"},"logparser":{"version":"1.1.0","platform":"Javascript/Node.js"},"simple-api":{"version":"2.6.2","platform":"Javascript/Node.js"},"spotify-premium":{"version":"1.1.4","platform":"Javascript/Node.js"},"fully-tablet-control":{"version":"0.3.4-0","platform":"Javascript/Node.js"},"rainbird":{"version":"0.2.3","platform":"Javascript/Node.js"},"dwd":{"version":"2.7.7","platform":"Javascript/Node.js"},"worx":{"version":"1.5.5","platform":"Javascript/Node.js"},"vis-fancyswitch":{"version":"1.1.0","platform":"Javascript/Node.js"},"unifi":{"version":"0.5.10","platform":"Javascript/Node.js"},"coronavirus-statistics":{"version":"0.8.7","platform":"Javascript/Node.js"},"hue":{"version":"3.5.31","platform":"Javascript/Node.js"},"sayit":{"version":"1.12.3","platform":"Javascript/Node.js"},"vis-google-fonts":{"version":"1.0.3","platform":"Javascript/Node.js"},"mqtt":{"version":"2.4.1","platform":"Javascript/Node.js"},"seq":{"version":"0.2.10","platform":"Javascript/Node.js"},"samsung-community":{"version":"0.5.0","platform":"Javascript/Node.js"},"nina":{"version":"0.0.25","platform":"Javascript/Node.js"},"web-speedy":{"version":"0.2.0","platform":"Javascript/Node.js"},"backitup":{"version":"2.2.2","platform":"Javascript/Node.js"},"trashschedule":{"version":"1.4.1","platform":"Javascript/Node.js"},"history":{"version":"1.10.5","platform":"Javascript/Node.js"},"discovery":{"version":"2.7.5","platform":"Javascript/Node.js"},"info":{"version":"1.9.16","platform":"Javascript/Node.js"},"benchmark":{"version":"0.4.0","platform":"Javascript/Node.js"},"devices":{"version":"1.0.9","platform":"Javascript/Node.js"}},"statesType":"file","objectsType":"file","model":"Intel(R) Celeron(R) CPU  N3150  @ 1.60GHz","cpus":4,"mem":3145728000,"ostype":"Linux","vis":698}
^C^C^C^C================================== > LOG REDIRECT system.adapter.admin.0 => false [Process stopped]
================================== > LOG REDIRECT system.adapter.javascript.0 => false [Process stopped]
================================== > LOG REDIRECT system.adapter.admin.0 => false [system.adapter.admin.0.logging]
================================== > LOG REDIRECT system.adapter.javascript.0 => false [system.adapter.javascript.0.logging]

```

**Comment by Apollon77** [comment]
@Feuer-sturm Can you please test one thing: start up all e.g. with info ... now change the loglevel in admin from one instance via the "No restart" way ... do you THEN get debug logs from the instance? maybe use an instance like web which should log something when you do a call. Thank you!

**Comment by Feuer-sturm** [comment]
@Apollon77 

iobroker.json:
```
      "seq1": {
        "type": "seq",
        "enabled": true,
        "serverUrl": "http://192.168.178.73:5341",
        "serverUrlComment": "The http(s) URL including port of the seq server. >
        "apiKey": "xxxxx",
        "apiKeyComment": "The apiKey of the seq system",
        "eol": "",
        "level": "info"
      }
    }
  },
```


iobroker log
```
2022-01-10 20:15:19.976 - info: web.0 (671) Loglevel changed from "info" to "debug"
2022-01-10 20:16:11.851 - info: web.0 (671) ==>Connected system.user.admin from 192.168.178.20
2022-01-10 20:16:11.865 - debug: web.0 (671) Connection from vis.0
2022-01-10 20:16:12.530 - debug: web.0 (671) 2022-01-10T19:16:12.529Z Request authenticate [system.user.admin]
```

Seq log
```
10 Jan 2022 20:16:12.531 iobrokerTestsystem web.0 (671) 2022-01-10T19:16:12.529Z Request authenticate [system.user.admin]
10 Jan 2022 20:16:11.867 iobrokerTestsystem web.0 (671) Connection from vis.0
10 Jan 2022 20:16:11.854 iobrokerTestsystem web.0 (671) ==>Connected system.user.admin from 192.168.178.20
10 Jan 2022 20:15:19.979 iobrokerTestsystem web.0 (671) Loglevel changed from "info" to "debug" 
```

I double checked this with the hue Adapter and here it worked as well. I can see the debug messages in Seq. :partying_face:
