### ISSUE TITLE
High load average

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.js-controller#1323]
Hi, i changed to a new raspi 4 - and exact at the same time the new controller version came out (3.3.1). Since then i have high processor loads (load average always betwen 0.7 and 1.0). Running htop shows js-controller is responsible for that.

But i am not shure, if it started with the controller-update or with my system change from tinkerboard to raspi 4b (8 gb). 

Is anyone else expierence similar problems? Any ideas how to find the problem and how to fix it?

It was a clean fresh installation. PivCCU and HA-Bridge is running on the raspi, nothing else. Everything should be up to date,
js-controller 3.3.5
node v12.22.1
npm v6.14.12.

![image](https://user-images.githubusercontent.com/49171332/116794325-836de600-aacc-11eb-8c33-14dd886be15b.png)

**Comment by Apollon77** [comment]
Is the system still logging the many logs because of invalid states? Because this can prodice load ... if you set loglevel to error (controller 3.3.1-3.3.4)/warn (3.3.5) is then load normalizting?

**Comment by sbormann** [comment]
I set the log level to error, so i think this is not the problem.

**Comment by Apollon77** [comment]
Ok but I summarize: on a new raspi4 host with a new controller you have higher CPU load then compared to your old system with an older controller? Honestly ... with this how could I compare?
All other settings are the same? ALso the same SD card? (because a sow sd card can have effect on higher cpu usage in controller ...

But honestly ... no idea where to start debugging this

YOu can try to downgrade controller and see what happens. There should be not really changes that could have such a result

**Comment by sbormann** [comment]
Hi,
thank you for your suggestions. I downgraded js-controller - without any changes. So i think the problem is not related to the new js-controller version.

I also tried to uninsall und reinstall iobroker (but i left the iobroker-data directory). All adapers were reinstalled correctly, but with the follwing error message. Load average is still at ~1.0.

This ist the error i accounter on every adapter upgrade, maybe that points to the right direction:
````
NPM version: 6.14.12
npm install iobroker.info@1.7.15 --loglevel error --prefix "/opt/iobroker" (System call)
../authenticate_pam.cc: In function ‘void after_doing_auth(uv_work_t*, int)’:
../authenticate_pam.cc:107:87: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(m->callback), 1, args);
                                                                                       ^
In file included from ../authenticate_pam.cc:23:
../../nan/nan.h:1026:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../authenticate_pam.cc:107:87: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(m->callback), 1, args);
                                                                                       ^
In file included from ../authenticate_pam.cc:23:
../../nan/nan.h:1026:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../authenticate_pam.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Authenticate(Nan::NAN_METHOD_ARGS_TYPE)’:
../authenticate_pam.cc:147:83: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   Local<Value> res = options->Get(Nan::New<String>("serviceName").ToLocalChecked());
                                                                                   ^
In file included from /home/iobroker/.cache/node-gyp/12.22.1/include/node/v8-internal.h:14,
                 from /home/iobroker/.cache/node-gyp/12.22.1/include/node/v8.h:27,
                 from /home/iobroker/.cache/node-gyp/12.22.1/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/12.22.1/include/node/v8.h:3553:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
                                                   ^~~
/home/iobroker/.cache/node-gyp/12.22.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../authenticate_pam.cc:150:69: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’
    serviceName->WriteUtf8(m->serviceName, sizeof(m->serviceName) - 1);
                                                                     ^
In file included from /home/iobroker/.cache/node-gyp/12.22.1/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/12.22.1/include/node/v8.h:2878:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^~~~~~~~~
/home/iobroker/.cache/node-gyp/12.22.1/include/node/v8.h:2878:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’
../authenticate_pam.cc:152:69: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   res = options->Get(Nan::New<String>("remoteHost").ToLocalChecked());
                                                                     ^
In file included from /home/iobroker/.cache/node-gyp/12.22.1/include/node/v8-internal.h:14,
                 from /home/iobroker/.cache/node-gyp/12.22.1/include/node/v8.h:27,
                 from /home/iobroker/.cache/node-gyp/12.22.1/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/12.22.1/include/node/v8.h:3553:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
                                                   ^~~
/home/iobroker/.cache/node-gyp/12.22.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../authenticate_pam.cc:155:66: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’
    remoteHost->WriteUtf8(m->remoteHost, sizeof(m->remoteHost) - 1);
                                                                  ^
In file included from /home/iobroker/.cache/node-gyp/12.22.1/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/12.22.1/include/node/v8.h:2878:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^~~~~~~~~
/home/iobroker/.cache/node-gyp/12.22.1/include/node/v8.h:2878:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’
../authenticate_pam.cc:160:58: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’
  username->WriteUtf8(m->username, sizeof(m->username) - 1);
                                                          ^
In file included from /home/iobroker/.cache/node-gyp/12.22.1/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/12.22.1/include/node/v8.h:2878:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^~~~~~~~~
/home/iobroker/.cache/node-gyp/12.22.1/include/node/v8.h:2878:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’
../authenticate_pam.cc:161:58: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’
  password->WriteUtf8(m->password, sizeof(m->password) - 1);
                                                          ^
In file included from /home/iobroker/.cache/node-gyp/12.22.1/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/12.22.1/include/node/v8.h:2878:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^~~~~~~~~
/home/iobroker/.cache/node-gyp/12.22.1/include/node/v8.h:2878:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’
../authenticate_pam.cc: At global scope:
../authenticate_pam.cc:170:11: error: variable or field ‘init’ declared void
 void init(Handle<Object> exports) {
           ^~~~~~
../authenticate_pam.cc:170:11: error: ‘Handle’ was not declared in this scope
../authenticate_pam.cc:170:11: note: suggested alternative: ‘rand_r’
 void init(Handle<Object> exports) {
           ^~~~~~
           rand_r
../authenticate_pam.cc:170:24: error: expected primary-expression before ‘>’ token
 void init(Handle<Object> exports) {
                        ^
../authenticate_pam.cc:170:26: error: ‘exports’ was not declared in this scope
 void init(Handle<Object> exports) {
                          ^~~~~~~
In file included from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
../authenticate_pam.cc:175:31: error: ‘init’ was not declared in this scope
 NODE_MODULE(authenticate_pam, init);
                               ^~~~
/home/iobroker/.cache/node-gyp/12.22.1/include/node/node.h:736:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../authenticate_pam.cc:175:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(authenticate_pam, init);
 ^~~~~~~~~~~
../authenticate_pam.cc:175:31: note: suggested alternative: ‘int’
 NODE_MODULE(authenticate_pam, init);
                               ^~~~
/home/iobroker/.cache/node-gyp/12.22.1/include/node/node.h:736:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../authenticate_pam.cc:175:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(authenticate_pam, init);
 ^~~~~~~~~~~
make: *** [authenticate_pam.target.mk:109: Release/obj.target/authenticate_pam/authenticate_pam.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.10.17-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/authenticate-pam
gyp ERR! node -v v12.22.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
````

It seems to be related to authenticate_pam.cc.

Any ideas?
If not, i will close the issue and try a complete new install and import all adapter settings one by one manually.

**Comment by Apollon77** [comment]
The npm warnings are from optional modules ... ignore

For Load ... honestly  your system is having an otehr processor. load onf 1 means that one core is "used", but in fact to really compare the CPU % is much better. So lead can differe a lot betwen procesors

**Comment by sbormann** [comment]
Ok, thank you ingo for your hints and tipps! I will now wait and watch the system. Greetings!
