### ISSUE TITLE
[pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.js-controller#1351]
js-controller 3.2.16
Node.js v12.21.0

```


2021-05-10 11:45:39.563 - info: host.DESKTOP-BNCL75L(SmartHome) "system.adapter.history.0" disabled
--
2021-05-10 11:45:39.570 - info: host.DESKTOP-BNCL75L(SmartHome) stopInstance system.adapter.history.0 (force=false, process=true)
2021-05-10 11:45:42.636 - info: host.DESKTOP-BNCL75L(SmartHome) "system.adapter.knx.2" disabled
2021-05-10 11:45:42.636 - info: host.DESKTOP-BNCL75L(SmartHome) stopInstance system.adapter.knx.2 (force=false, process=true)
2021-05-10 11:45:42.647 - info: knx.2 (19885) Got terminate signal TERMINATE_YOURSELF
2021-05-10 11:45:42.672 - info: knx.2 (19885) terminating
2021-05-10 11:45:42.673 - info: knx.2 (19885) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2021-05-10 11:45:42.690 - info: host.DESKTOP-BNCL75L(SmartHome) stopInstance system.adapter.knx.2 send kill signal
2021-05-10 11:45:43.318 - info: host.DESKTOP-BNCL75L(SmartHome) instance system.adapter.knx.2 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2021-05-10 11:45:49.571 - info: host.DESKTOP-BNCL75L(SmartHome) stopInstance timeout 10000 system.adapter.history.0 killing pid 18480
2021-05-10 11:45:59.462 - info: host.DESKTOP-BNCL75L(SmartHome) "system.adapter.knx.2" enabled
2021-05-10 11:45:59.657 - info: host.DESKTOP-BNCL75L(SmartHome) instance system.adapter.knx.2 started with pid 10631
2021-05-10 11:46:02.458 - info: knx.2 (10631) starting. Version 1.0.45 in /opt/iobroker/node_modules/iobroker.knx, node: v12.21.0, js-controller: 3.2.16
2021-05-10 11:46:02.997 - info: knx.2 (10631) knx license is OK.
2021-05-10 11:46:03.001 - info: knx.2 (10631) Connecting to knx GW: 192.168.137.13:3671 with phy. Adr: 1.1.249
2021-05-10 11:52:27.752 - error: host.DESKTOP-BNCL75L(SmartHome) Caught by controller[1]: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-05-10 11:52:27.753 - error: host.DESKTOP-BNCL75L(SmartHome) Caught by controller[2]: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2021-05-10 11:52:27.753 - error: host.DESKTOP-BNCL75L(SmartHome) Caught by controller[3]: Error: EBADF: bad file descriptor, write
2021-05-10 11:52:27.753 - error: host.DESKTOP-BNCL75L(SmartHome) Caught by controller[4]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2021-05-10 11:52:27.753 - error: host.DESKTOP-BNCL75L(SmartHome) Caught by controller[4]: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
2021-05-10 11:52:27.754 - error: host.DESKTOP-BNCL75L(SmartHome) Caught by controller[4]: at doWrite (_stream_writable.js:399:19)
2021-05-10 11:52:27.754 - error: host.DESKTOP-BNCL75L(SmartHome) Caught by controller[4]: at writeOrBuffer (_stream_writable.js:387:5)
2021-05-10 11:52:27.754 - error: host.DESKTOP-BNCL75L(SmartHome) Caught by controller[4]: at WriteStream.Writable.write (_stream_writable.js:318:11)
2021-05-10 11:52:27.754 - error: host.DESKTOP-BNCL75L(SmartHome) Caught by controller[4]: at Object. (/opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js:616:26)
2021-05-10 11:52:27.754 - error: host.DESKTOP-BNCL75L(SmartHome) Caught by controller[4]: at DailyRotateFile.log (/opt/iobroker/node_modules/winston-daily-rotate-file/daily-rotate-file.js:157:20)
2021-05-10 11:52:27.754 - error: host.DESKTOP-BNCL75L(SmartHome) Caught by controller[4]: at DailyRotateFile._write (/opt/iobroker/node_modules/winston-transport/index.js:103:17)
2021-05-10 11:52:27.755 - error: host.DESKTOP-BNCL75L(SmartHome) Caught by controller[4]: at doWrite (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:428:64)
2021-05-10 11:52:27.755 - error: host.DESKTOP-BNCL75L(SmartHome) Caught by controller[4]: at writeOrBuffer (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:417:5)
2021-05-10 11:52:27.755 - error: host.DESKTOP-BNCL75L(SmartHome) Caught by controller[4]: at DailyRotateFile.Writable.write (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:334:11)
2021-05-10 11:52:27.755 - error: host.DESKTOP-BNCL75L(SmartHome) Caught by controller[4]: at DerivedLogger.ondata (/opt/iobroker/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:681:20)
2021-05-10 11:52:27.755 - info: host.DESKTOP-BNCL75L(SmartHome) instance system.adapter.history.0 terminated with code 1 (JS_CONTROLLER_STOPPED)


```

**Comment by Apollon77** [comment]
The thing about pidusage is just a warning and have no effect!

The issue is "Error: EBADF: bad file descriptor, write" which indicates a file system issue! (and could also have caused the other error) Please check and fix your filesystem!
