### ISSUE TITLE
ioBroker.upnp adapter crashes ioBroker.js-controller with "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by jens-maus** [ioBroker/ioBroker.js-controller#139]
I don't know if this isn't a fault of ioBroker.upnp but here it crashes js-controller as soon as it had finished to initialize with the following log output:

```
[...]
2017-02-18 21:14:08.457  - infoESC: upnp.0 Found 20 devices
2017-02-18 21:14:35.859  - errorESC: uncaught exception: Maximum call stack size exceeded
[... here it terminates all adapter, etc ...]
2017-02-18 21:14:35.878  - errorESC: RangeError: Maximum call stack size exceeded
    at onEnd (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io/node_modules/engine.io/lib/transports/websocket.js:118:52)
    at Sender.frameAndSend (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Sender.js:235:38)
    at /opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Sender.js:126:12
    at Sender.applyExtensions (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Sender.js:287:5)
    at /opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Sender.js:120:10
    at Sender.flush (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Sender.js:268:3)
    at /opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Sender.js:270:10
    at /opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Sender.js:127:7
    at Sender.applyExtensions (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Sender.js:287:5)
    at /opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Sender.js:120:10
```

**Comment by GermanBluefox** [comment]
This must be fixed now
