### ISSUE TITLE
this.enums in adapter.js needs to be initialized "flat" ...

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1654]
... and not structured. the adapter.getEnums is returning a two level structure  and this is not comparible to the structiure from tools.

**Comment by Apollon77** [comment]
ANd maybe add a buiard in tools function that deletes from enum? 

```
benchmark.0 (3830) TypeError: Cannot read property 'members' of undefined
    at Object.removeIdFromAllEnums (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:2560:36)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/lib/adapter/adapter.js:3584:41)
```
