### ISSUE TITLE
Local rebuild not working

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#1659]
Wrong directory is used:

```
2022-01-09 22:54:13.116  - info: host.io-test4 iobroker npm-rebuild: Rebuilding native modules in /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node ...
```

```
2022-01-09 22:54:13.130  - error: host.io-test4 iobroker npm-rebuild: Uncaught Rejection: Error: Command failed with ENOTDIR: npm rebuild --loglevel errorspawn ENOTDIR    at ChildProcess.spawn (internal/child_process.js:405:11)    at spawn (child_process.js:677:9)    at Object.spawnWithSignal [as spawn] (child_process.js:911:17)    at Object.execa [as default] (/opt/iobroker/node_modules/@alcalzone/pak/node_modules/execa/index.js:83:26)    at Npm.command (/opt/iobroker/node_modules/@alcalzone/pak/build/lib/package-managers/npm/index.js:152:40)    at Npm.rebuild (/opt/iobroker/node_modules/@alcalzone/pak/build/lib/package-managers/npm/index.js:227:21)    at Object.rebuildNodeModules (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:1559:16)    at async processCommand (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:854:28)
```
We can not use the found path directly but need to find the "module root":
* search to LAST node_modules in the string
* check if next Path entry starts with @ 
* if yes: include this and the next entry
* if no: just include this

**Comment by AlCalzone** [comment]
> search to LAST node_modules in the string
    check if next Path entry starts with @
    if yes: include this and the next entry
    if no: just include this

Alternative proposal:
```
start at path.dirname(modulename)
while not at the filesystem root:
  check if package.json exists in current dir
  if yes, break while
  if not, go up one level

rebuild here
```

**Comment by Apollon77** [comment]
alsoan idea ... but basiclly should end in "the same", or?

**Comment by AlCalzone** [comment]
Yeah, but it requires less on assumptions. In the end, you'll have to rebuild at the level where the `package.json` of the affected dependency is found. My approach makes that explicit.
