### ISSUE TITLE
[CLI] list objects leads to error

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#1738]
```
pi@raspberrypi4:~ $ iobroker list objects admin.0.*
admin.0.connected                      : state     - Info about connected socket clients
admin.0.info                           : channel   - Information
admin.0.info.connection                : state     - Info about connected socket clients
admin.0.info.lastUpdateCheck           : state     - Timestamp of last update check
admin.0.info.newUpdates                : state     - Indicator if new adapter updates are available
admin.0.info.newsETag                  : state     - Etag for news feed
admin.0.info.newsFeed                  : state     - Last news feed as JSON
admin.0.info.newsLastId                : state     - last seen news ID
admin.0.info.newsfeed                  : state     - Last news feed as JSON
admin.0.info.updatesJson               : state     - JSON string with adapter update information
admin.0.info.updatesList               : state     - List of adapters to update
admin.0.info.updatesNumber             : state     - Number of adapters to update
/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupList.js:284
                                name = name[lang] || name.en;
                                           ^

TypeError: Cannot read property 'de' of null
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupList.js:284:44)
    at processImmediate (internal/timers.js:466:21)
```

https://github.com/ioBroker/ioBroker.js-controller/blob/fd9503254056dd5fba57972394c61bdd5d04fddb/lib/setup/setupList.js#L283-L285

js-controller 3.3.22

Don't know which object is affected... 😢

**Comment by klein0r** [comment]
Wrapped the line in a try/catch block: These objects lead to the problem:

```
info.0.sysinfo.usb.dev0.null
info.0.sysinfo.usb.dev1.null
info.0.sysinfo.usb.dev2.null
info.0.sysinfo.usb.dev3.null
info.0.sysinfo.usb.dev4.null
info.0.sysinfo.usb.dev5.null
```

```
pi@raspberrypi4:~ $ iobroker object get info.0.sysinfo.usb.dev0.null
```

```json
{"type":"channel","common":{"name":null,"role":"info"},"native":{},"from":"system.adapter.info.0","user":"system.user.admin","ts":1627114771374,"_id":"info.0.sysinfo.usb.dev0.null","acl":{"object":1636,"owner":"system.user.admin","ownerGroup":"system.group.administrator"}}
```

``null`` === ``typeof object``

**Comment by foxriver76** [comment]
yeah we need to check for real objects, will be part of 4.0. thanks for reporting
