### ISSUE TITLE
Error in GUI (in den Host Einstellung Tab "Log")

### ISSUE THREAD

**Issue by blackeagle998** [ioBroker/ioBroker.js-controller#1842]
Hallo,

wenn ich bei den Einstellungen des Hosts auf den Reiter LOG gehe, kommt eine Seite mit der Meldung "Error in GUI" und dem Hinweis, den Fehler aus der Entwicklerkonsole zu posten, das wäre dieser hier:
TypeError: Cannot read properties of undefined (reading 'includes')
    at BaseSettingsLog.js:77:65
    at Array.forEach (<anonymous>)
    at new s (BaseSettingsLog.js:75:41)
    at zc (react-dom.production.min.js:135:172)
    at Uo (react-dom.production.min.js:181:146)
    at Zi (react-dom.production.min.js:269:427)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at ke (react-dom.production.min.js:292:101)
    at Yt (react-dom.production.min.js:73:352)
    at HTMLBodyElement.a (helpers.ts:98:17)

js-controller: 4.0.15
Admin: 5.3.1
node: 14.18.2
nodejs: 14.18.2
npm: 6.14.11

**Comment by Apollon77** [comment]
Bitte im Admin öffnen bzw schauen ob der Fehler schon berichtet ist (glaube schon)

**Comment by Berchemer** [comment]
Sorry...
Habe hier js-controller _**v4.0.21**_ und wenn ich unter Hosts auf EInstellungen und dort auf den Tab "Log" gehe, erhalte ich heute noch folgende Fehlermeldung, wenn ich in Firefox "Konsole" öffne:

```
> iobroker.admin@5.3.1 index.js:18:8
> [2022-03-16T13:59:49.256Z] Try to connect instrument.ts:125:32
> [2022-03-16T13:59:52.263Z] Start reconnect 0 instrument.ts:125:32
> Firefox kann keine Verbindung zu dem Server unter ws://XX.My.IP.YY:8081/?sid=1647439189256&name=admin aufbauen. socket.io.js:94:21
> [2022-03-16T13:59:52.263Z] Try to connect instrument.ts:125:32
> [2022-03-16T13:59:52.265Z] Start reconnect 1 instrument.ts:125:32
> Die Verbindung zu ws://XX.My.IP.YY:8081/?sid=1647439189256&name=admin wurde unterbrochen, während die Seite geladen wurde. socket.io.js:94:21
> Firefox kann keine Verbindung zu dem Server unter ws://XX.My.IP.YY:8081/?sid=1647439192264&name=admin aufbauen. socket.io.js:94:21
> [2022-03-16T13:59:52.265Z] ws connection error: CLOSE_ABNORMAL instrument.ts:125:32
> [2022-03-16T13:59:52.265Z] Reconnect is already running 1 instrument.ts:125:32
> [2022-03-16T13:59:52.267Z] Reconnect is already running 1 instrument.ts:125:32
> [2022-03-16T13:59:52.267Z] ws connection error: CLOSE_ABNORMAL instrument.ts:125:32
> Die Verbindung zu ws://XX.My.IP.YY:8081/?sid=1647439192264&name=admin wurde unterbrochen, während die Seite geladen wurde. socket.io.js:94:21
> [2022-03-16T13:59:52.267Z] Reconnect is already running 1 instrument.ts:125:32
> [2022-03-16T13:59:53.277Z] Try to connect instrument.ts:125:32
> [2022-03-16T13:59:56.278Z] Start reconnect 2 instrument.ts:125:32
> Firefox kann keine Verbindung zu dem Server unter ws://XX.My.IP.YY:8081/?sid=1647439193277&name=admin aufbauen. socket.io.js:94:21
> Die Verbindung zu ws://XX.My.IP.YY:8081/?sid=1647439193277&name=admin wurde unterbrochen, während die Seite geladen wurde. socket.io.js:94:21
> [2022-03-16T13:59:56.279Z] Reconnect is already running 2 instrument.ts:125:32
> [2022-03-16T13:59:56.280Z] ws connection error: CLOSE_ABNORMAL instrument.ts:125:32
> [2022-03-16T13:59:56.280Z] Reconnect is already running 2 instrument.ts:125:32
> [2022-03-16T13:59:58.280Z] Try to connect instrument.ts:125:32
> Translate: time instrument.ts:125:32
> Translate: timeOffset instrument.ts:125:32
> Translate: You can enter more than one address divided by comma instrument.ts:125:32
> TypeError: n.transport[t].maxSize is null
>     e BaseSettingsLog.js:77
>     s BaseSettingsLog.js:75
>     React 8
>     unstable_runWithPriority scheduler.production.min.js:18
>     React 5
>     a helpers.ts:98
> instrument.ts:125:32
```

Weiterhin folgende grafische Ausgabe.
![2022-03-16 - 15_11 - ioBroker Error](https://user-images.githubusercontent.com/44316663/158611111-5eff1c8d-6cd9-428f-9f75-c6dfc441c299.PNG)

**Comment by Apollon77** [comment]
Yes this is an Admin isue and already known there
