### ISSUE TITLE
Async function without a catch block, or by rejecting a promise which was not handled with .catch()

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.js-controller#1959]
```
2022-07-18 07:13:43.864  - error: host.LAPTOP-V8VFHQ1P Cannot find view "system" for search "instance" : Connection is closed.
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[1]: Error: DB closed
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[1]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[1]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[1]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[2]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[2]: Error: DB closed
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[2]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[2]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[2]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[3]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[4]: Error: DB closed
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[4]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[4]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[4]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[5]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[6]: Error: DB closed
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[6]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[6]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[6]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[7]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.865  - error: host.LAPTOP-V8VFHQ1P Caught by controller[7]: Error: DB closed
2022-07-18 07:13:43.866  - error: host.LAPTOP-V8VFHQ1P Caught by controller[7]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.866  - error: host.LAPTOP-V8VFHQ1P Caught by controller[7]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.866  - error: host.LAPTOP-V8VFHQ1P Caught by controller[7]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.866  - error: host.LAPTOP-V8VFHQ1P Caught by controller[8]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.866  - error: host.LAPTOP-V8VFHQ1P Caught by controller[9]: Error: DB closed
2022-07-18 07:13:43.866  - error: host.LAPTOP-V8VFHQ1P Caught by controller[9]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.866  - error: host.LAPTOP-V8VFHQ1P Caught by controller[9]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.866  - error: host.LAPTOP-V8VFHQ1P Caught by controller[9]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.866  - error: host.LAPTOP-V8VFHQ1P Caught by controller[10]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.866  - error: host.LAPTOP-V8VFHQ1P Caught by controller[10]: Error: DB closed
2022-07-18 07:13:43.866  - error: host.LAPTOP-V8VFHQ1P Caught by controller[10]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.866  - error: host.LAPTOP-V8VFHQ1P Caught by controller[10]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.866  - error: host.LAPTOP-V8VFHQ1P Caught by controller[10]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.867  - error: host.LAPTOP-V8VFHQ1P Caught by controller[11]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.867  - error: host.LAPTOP-V8VFHQ1P Caught by controller[11]: Error: DB closed
2022-07-18 07:13:43.867  - error: host.LAPTOP-V8VFHQ1P Caught by controller[11]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.867  - error: host.LAPTOP-V8VFHQ1P Caught by controller[11]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.867  - error: host.LAPTOP-V8VFHQ1P Caught by controller[11]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.867  - error: host.LAPTOP-V8VFHQ1P Caught by controller[12]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.867  - error: host.LAPTOP-V8VFHQ1P Caught by controller[13]: Error: DB closed
2022-07-18 07:13:43.867  - error: host.LAPTOP-V8VFHQ1P Caught by controller[13]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.867  - error: host.LAPTOP-V8VFHQ1P Caught by controller[13]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.867  - error: host.LAPTOP-V8VFHQ1P Caught by controller[13]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.867  - error: host.LAPTOP-V8VFHQ1P Caught by controller[14]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.867  - error: host.LAPTOP-V8VFHQ1P Caught by controller[14]: Error: DB closed
2022-07-18 07:13:43.867  - error: host.LAPTOP-V8VFHQ1P Caught by controller[14]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.867  - error: host.LAPTOP-V8VFHQ1P Caught by controller[14]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.867  - error: host.LAPTOP-V8VFHQ1P Caught by controller[14]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.867  - error: host.LAPTOP-V8VFHQ1P Caught by controller[15]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[15]: Error: DB closed
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[15]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[15]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[15]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[16]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[16]: Error: DB closed
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[16]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[16]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[16]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[17]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[18]: Error: DB closed
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[18]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[18]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[18]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[19]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[19]: Error: DB closed
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[19]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[19]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[19]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[20]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[21]: Error: DB closed
2022-07-18 07:13:43.868  - error: host.LAPTOP-V8VFHQ1P Caught by controller[21]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.869  - error: host.LAPTOP-V8VFHQ1P Caught by controller[21]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.869  - error: host.LAPTOP-V8VFHQ1P Caught by controller[21]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.869  - error: host.LAPTOP-V8VFHQ1P Caught by controller[22]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.869  - error: host.LAPTOP-V8VFHQ1P Caught by controller[23]: Error: DB closed
2022-07-18 07:13:43.869  - error: host.LAPTOP-V8VFHQ1P Caught by controller[23]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.869  - error: host.LAPTOP-V8VFHQ1P Caught by controller[23]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.869  - error: host.LAPTOP-V8VFHQ1P Caught by controller[23]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.869  - error: host.LAPTOP-V8VFHQ1P Caught by controller[24]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.869  - error: host.LAPTOP-V8VFHQ1P Caught by controller[24]: Error: DB closed
2022-07-18 07:13:43.869  - error: host.LAPTOP-V8VFHQ1P Caught by controller[24]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.869  - error: host.LAPTOP-V8VFHQ1P Caught by controller[24]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.869  - error: host.LAPTOP-V8VFHQ1P Caught by controller[24]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.869  - error: host.LAPTOP-V8VFHQ1P Caught by controller[25]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-18 07:13:43.869  - error: host.LAPTOP-V8VFHQ1P Caught by controller[26]: Error: DB closed
2022-07-18 07:13:43.869  - error: host.LAPTOP-V8VFHQ1P Caught by controller[26]:     at Object.maybeCallbackWithError (C:\pWork\node_modules\@iobroker\js-controller-common\src\lib\common\maybeCallback.ts:136:17)
2022-07-18 07:13:43.869  - error: host.LAPTOP-V8VFHQ1P Caught by controller[26]:     at Immediate.<anonymous> (C:\pWork\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.js:6084:38)
2022-07-18 07:13:43.869  - error: host.LAPTOP-V8VFHQ1P Caught by controller[26]:     at processImmediate (node:internal/timers:468:21)
2022-07-18 07:13:43.869  - warn: host.LAPTOP-V8VFHQ1P instance system.adapter.javascript.0 terminated due to SIGTERM
2022-07-18 07:13:43.869  - info: host.LAPTOP-V8VFHQ1P instance system.adapter.javascript.0 terminated with code null ()
2022-07-18 07:13:43.869  - warn: host.LAPTOP-V8VFHQ1P get state error: Connection is closed.
2022-07-18 07:13:45.314  - warn: openweathermap.0 (14620) Cannot connect/reconnect to objects DB. Terminating
2022-07-18 07:13:45.315  - info: openweathermap.0 (14620) Terminated (NO_ERROR): Without reason
2022-07-18 07:13:45.315  - warn: openweathermap.0 (14620) Cannot connect/reconnect to objects DB. Terminating
2022-07-18 07:13:45.315  - warn: openweathermap.0 (14620) Cannot connect/reconnect to objects DB. Terminating
2022-07-18 07:13:45.834  - error: host.LAPTOP-V8VFHQ1P Cannot find view "system" for search "instance" : Connection is closed.
2022-07-18 07:13:45.834  - info: host.LAPTOP-V8VFHQ1P instance system.adapter.openweathermap.0 terminated with code 0 (NO_ERROR)
2022-07-18 07:13:45.834  - warn: host.LAPTOP-V8VFHQ1P get state error: Connection is closed.
```

Version: 4.1.0-alpha.35-20220602-3de539a6

We should catch it and handle it properly. Happens if DB is closed without stopping iob.

**Comment by Apollon77** [comment]
Hm ... in fact the adapter needs to make sure to not execute code any longer after unload ?! So it is more an javascript adapter issue?

Should this then not be an issue for the javascript dapter tzo catch that?
