### ISSUE TITLE
applyViewFunc: Uncaught Rejection: TypeError: Cannot read properties of null (reading '_id')

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#2028]
We should make sure for Redis and sets (applyViewFunc) to check that the obj is really defined when we iterate over the set objects. if the entry is NOT an object then we should assume a broken set index

Uncaught Rejection: TypeError: Cannot read properties of null (reading '_id')
    at /opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:3422:42
    at Array.map (<anonymous>)
    at ObjectsInRedisClient._applyViewFunc (/opt/iobroker/node_modules/@iobroker/db-objects-redis/lib/objects/objectsInRedisClient.js:3414:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Reaction I would say:
* We should ignore this one "broken" object for this call to not crash
* Minimum we should log an error from the host to tell the user in the log that sets are somehow outdated and should be rebuild (by running iob o deactivateSets && iob o activateSets). Additional to log we could send a "notification" for showing in admin
* Alternative is to trigger an (async - so after answering the call do it in background) check of the index ... so da alegacy search and check entry by entry - problem is that this is (again) not atomic so it could go wrong ... so no idea if this isthe best idea

**Comment by Apollon77** [comment]
PS: Innew codebase the place where it would break could be https://github.com/ioBroker/ioBroker.js-controller/blob/master/packages/db-objects-redis/src/lib/objects/objectsInRedisClient.ts#L3835
