### ISSUE TITLE
Backupfehler

### ISSUE THREAD

**Issue by willi5** [ioBroker/ioBroker.js-controller#2050]
System ist Windows 11 auf dem Updatestand vom21.11.2022

Neue Installation mit mit neuer Windows "Installer.exe".
iobroker läuft.
iobroker stop
Überschreiben von iobroker-data mit einer gesicherten Version von einem anderen PC (Versionen sind aktuell).
iobroker start
Nach der üblichen Wartezeit läuft iobroker einwandfrei.Scheinbar.
Jetzt tauchen Fehler auf.

Backup mit "Backitup" funktioniert. 
Backup mit iobroker "backup" produziert folgende Meldung:
c:\ioBroker> iobroker backup
[host.EG](http://host.eg/) Cannot read config file: Cannot read properties of undefined (reading 'hostname')
[host.EG](http://host.eg/) 20445 states saved
[host.EG](http://host.eg/) 30253 objects saved
Backup created: c:\ioBroker\backups\2022_11_20-12_23_02_backupiobroker.tar.gz

Restore mit "Backitup" funktioniert nicht. Restore mit "iobroker restore 0" produziert folgende Meldung:

c:\ioBroker> iobroker restore 0
host.Dieter Using backup file iobroker_2022_11_14-19_20_10_backupiobroker.tar.gz
iobroker controller daemon is not running
host.Dieter OK.
Uncaught Rejection: TypeError: Cannot read properties of undefined (reading 'hostname')
at BackupRestore._restoreAfterStop (c:\ioBroker\node_modules\iobroker.js-controller\lib\setup\setupBackup.js:696:52)
at Daemon.<anonymous> (c:\ioBroker\node_modules\iobroker.js-controller\lib\setup\setupBackup.js:1128:49)
at Daemon.emit (node:events:539:35)
at Daemon.emit (node:domain:475:12)
at Daemon._kill (c:\ioBroker\node_modules\daemonize2\lib\daemonize.js:246:14)
at Daemon.stop (c:\ioBroker\node_modules\daemonize2\lib\daemonize.js:185:17)
at c:\ioBroker\node_modules\iobroker.js-controller\lib\setup\setupBackup.js:1132:24
at processTicksAndRejections (node:internal/process/task_queues:96:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read properties of undefined (reading 'hostname')
at BackupRestore._restoreAfterStop (c:\ioBroker\node_modules\iobroker.js-controller\lib\setup\setupBackup.js:696:52)
at Daemon.<anonymous> (c:\ioBroker\node_modules\iobroker.js-controller\lib\setup\setupBackup.js:1128:49)
at Daemon.emit (node:events:539:35)
at Daemon.emit (node:domain:475:12)
at Daemon._kill (c:\ioBroker\node_modules\daemonize2\lib\daemonize.js:246:14)
at Daemon.stop (c:\ioBroker\node_modules\daemonize2\lib\daemonize.js:185:17)
at c:\ioBroker\node_modules\iobroker.js-controller\lib\setup\setupBackup.js:1132:24
at processTicksAndRejections (node:internal/process/task_queues:96:5)

Außerdem funktioniert der Befehl "iobroker restore 0" nicht mehr. Statt dessen muss er jetzt so aussehen: ".\iobroker restore 0" oder ".\iobroker backup".

**Comment by Apollon77** [comment]
duplicate to https://github.com/ioBroker/ioBroker.js-controller/issues/1889
