### ISSUE TITLE
"Cannot read property of null" when using  node/npm installed via snap

### ISSUE THREAD

**Issue by hschwane** [ioBroker/ioBroker.js-controller#2058]
Getting the following error while using npm and node installed via snap:

```
NPM version: 
/[...path...]/.dev-server/default/node_modules/iobroker.js-controller/lib/preinstallCheck.js:111
    if (v1.major > v2.major) {
           ^

TypeError: Cannot read property 'major' of null
    at gt (/[...path...]/.dev-server/default/node_modules/iobroker.js-controller/lib/preinstallCheck.js:111:12)
    at gte (/[...path...]/.dev-server/default/node_modules/iobroker.js-controller/lib/preinstallCheck.js:191:12)
    at /[...path...]/.dev-server/default/node_modules/iobroker.js-controller/lib/preinstallCheck.js:40:29
...
```

Afterwards I reinstalled node and npm using apt and it works fine now. Still, you might want to handle that somewhat more gracefully.

**Comment by Apollon77** [comment]
We should catch the case that npm version could not be determined
