### ISSUE TITLE
Compavt mode groups not working js-controller 5

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#2182]
```
023-03-31 09:56:18.643  - info: host.io-test compactgroup controller 1 terminated with code 1 (JS_CONTROLLER_STOPPED)
2023-03-31 09:56:18.661  - error: host.io-test Caught by controller[0]: internal/modules/cjs/loader.js:934
2023-03-31 09:56:18.661  - error: host.io-test Caught by controller[0]:   throw err;
2023-03-31 09:56:18.661  - error: host.io-test Caught by controller[0]:   ^
2023-03-31 09:56:18.661  - error: host.io-test Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/build/compactgroupController.js'
2023-03-31 09:56:18.662  - error: host.io-test Caught by controller[0]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
2023-03-31 09:56:18.662  - error: host.io-test Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:774:27)
2023-03-31 09:56:18.662  - error: host.io-test Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
2023-03-31 09:56:18.662  - error: host.io-test Caught by controller[0]:     at internal/main/run_main_module.js:17:47 {
2023-03-31 09:56:18.662  - error: host.io-test Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
2023-03-31 09:56:18.662  - error: host.io-test Caught by controller[0]:   requireStack: []
2023-03-31 09:56:18.663  - error: host.io-test Caught by controller[0]: }
2023-03-31 09:56:18.663  - info: host.io-test Restart compact group controller 1
2023-03-31 09:56:18.663  - debug: host.io-test Instances: ["system.adapter.admin.2"]

```

**Comment by foxriver76** [comment]
The module is one dir above build dir, have to check who is requiring it how
