### ISSUE TITLE
npm-rebuild throw err

### ISSUE THREAD

**Issue by ChrMaass** [ioBroker/ioBroker.js-controller#2265]
After updating to js-controller v5 I got this error in der initial Log:

```
2023-05-23 18:46:55.956 - error: host.iobroker Caught by controller[0]: /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9222
2023-05-23 18:46:55.957 - error: host.iobroker Caught by controller[0]: throw new Error(`Unknown objects type: ${this._config.objects.type}: ${err.message}`);
2023-05-23 18:46:55.957 - error: host.iobroker Caught by controller[0]: ^
2023-05-23 18:46:55.957 - error: host.iobroker Caught by controller[0]: Error: Unknown objects type: jsonl: Cannot find module '/opt/iobroker/node_modules/semver/index.js'. Please verify that the package.json has a valid "main" entry
2023-05-23 18:46:55.957 - error: host.iobroker Caught by controller[0]: at AdapterClass._init (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9222:23)
2023-05-23 18:46:55.957 - error: host.iobroker Caught by controller[0]: at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-05-23 18:46:55.957 - error: host.iobroker Caught by controller[0]: Node.js v18.16.0
2023-05-23 18:46:55.958 - error: host.iobroker instance system.adapter.web.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2023-05-23 18:46:55.958 - info: host.iobroker Adapter system.adapter.web.0 needs rebuild and will be restarted afterwards.
2023-05-23 18:46:55.959 - info: host.iobroker system.adapter.web.0 will be rebuilt
2023-05-23 18:46:55.960 - warn: host.iobroker adapter "web" seems to be installed for a different version of Node.js. Trying to rebuild it... 1 attempt
2023-05-23 18:46:55.960 - info: host.iobroker iobroker rebuild
2023-05-23 18:46:56.370 - info: renault.0 (76431) Feature not found for VF1AG000966405665. Ignore lock-status for updates.
2023-05-23 18:46:56.508 - error: host.iobroker iobroker npm-rebuild: node:internal/modules/cjs/loader:1078 throw err; ^Error: Cannot find module './internal/re'Require stack:- /opt/iobroker/node_modules/semver/index.js- /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js- /opt/iobroker/node_modules/@iobroker/js-controller-common/build/index.js- /opt/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup.js- /opt/iobroker/node_modules/@iobroker/js-controller-cli/build/index.js- /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15) at Module._load (node:internal/modules/cjs/loader:920:27) at Module.require (node:internal/modules/cjs/loader:1141:19) at require (node:internal/modules/cjs/helpers:110:18) at Object. (/opt/iobroker/node_modules/semver/index.js:2:20) at Module._compile (node:internal/modules/cjs/loader:1254:14) at Module._extensions..js (node:internal/modules/cjs/loader:1308:10) at Module.load (node:internal/modules/cjs/loader:1117:32) at Module._load (node:internal/modules/cjs/loader:958:12) at Module.require (node:internal/modules/cjs/loader:1141:19) { code: 'MODULE_NOT_FOUND', requireStack: [ '/opt/iobroker/node_modules/semver/index.js', '/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js', '/opt/iobroker/node_modules/@iobroker/js-controller-common/build/index.js', '/opt/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup.js', '/opt/iobroker/node_modules/@iobroker/js-controller-cli/build/index.js', '/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js' ]}Node.js v18.16.0
2023-05-23 18:46:56.514 - info: host.iobroker iobroker npm-rebuild: exit 1 
```

**Comment by Apollon77** [comment]
Please try to reinstall controller and see if that error happens again - and please check if that path exists

**Comment by foxriver76** [comment]
Please reopen if it occurs again
