### ISSUE TITLE
adapter iobroker.mercury can't start on 5.0.3

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.js-controller#2299]
On controller version 4.0.24, the adapter worked, after the update it does not start. The logs have this error:

```
2023-06-15 00:11:07.154 - error: mercury.0 (790662) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2023-06-15 00:11:07.156 - error: mercury.0 (790662) unhandled promise rejection: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker.js-controller/build/../../iobroker-data/mercury_0/'
2023-06-15 00:11:07.158 - error: mercury.0 (790662) Error: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker.js-controller/build/../../iobroker-data/mercury_0/'
at Object.mkdirSync (node:fs:1396:3)
at Object.main [as ready] (/opt/iobroker/node_modules/iobroker.mercury/main.js:370:33)
at AdapterClass._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9015:31)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8995:26
2023-06-15 00:11:07.159 - error: mercury.0 (790662) Exception-Code: ENOENT: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker.js-controller/build/../../iobroker-data/mercury_0/'
2023-06-15 00:11:07.664 - warn: mercury.0 (790662) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-06-15 00:11:08.344 - error: host.iobroker instance system.adapter.mercury.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-06-15 00:11:08.344 - info: host.iobroker Restart adapter system.adapter.mercury.0 because enabled
2023-06-15 00:11:33.636 - error: hp-ilo.0 (789647) Request error: Error: connect EHOSTUNREACH 192.168.1.11:443 , URL: https://192.168.1.11/rest/v1/Chassis/1/Thermal
2023-06-15 00:11:38.483 - info: host.iobroker instance system.adapter.mercury.0 started with pid 790785
2023-06-15 00:11:39.470 - error: mercury.0 (790785) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-06-15 00:11:39.471 - error: mercury.0 (790785) unhandled promise rejection: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker.js-controller/build/../../iobroker-data/mercury_0/'
2023-06-15 00:11:39.473 - error: mercury.0 (790785) Error: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker.js-controller/build/../../iobroker-data/mercury_0/'


```

link to line with code - https://github.com/instalator/ioBroker.mercury/blob/main/main.js#LL370C8-L370C8

**Comment by Anzic23** [comment]
looks like a local problem. After removing the adapter and installing it back - the performance was restored.
