### ISSUE TITLE
node-red: Kein Adapterstart nach update auf JS-Controler 5.0.2

### ISSUE THREAD

**Issue by luieiob** [ioBroker/ioBroker.js-controller#2308]
Adapter wird nicht mehr grün nach update auf JS-Controler 5.0.2

`node-red.0
2023-06-13 17:02:11.255	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

node-red.0
2023-06-13 17:02:11.254	info	terminating

node-red.0
2023-06-13 17:02:10.750	error	Parameter "chainedName" needs to be of type "string" but type "undefined" has been passed

node-red.0
2023-06-13 17:02:10.750	error	Error: Parameter "chainedName" needs to be of type "string" but type "undefined" has been passed at Validator.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/validator.js:168:19) at AdapterClass.getCertificates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:1450:31) at writeSettings (/opt/iobroker/node_modules/iobroker.node-red/main.js:340:17) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.node-red/main.js:566:21) at process.processImmediate (node:internal/timers:478:21)

node-red.0
2023-06-13 17:02:10.748	error	uncaught exception: Parameter "chainedName" needs to be of type "string" but type "undefined" has been passed

node-red.0
2023-06-13 17:02:10.686	info	starting. Version 4.0.3 (non-npm: ioBroker/ioBroker.node-red) in /opt/iobroker/node_modules/iobroker.node-red, node: v18.16.0, js-controller: 5.0.2
`

**Comment by m4d-D3v1l** [comment]
Schon jemand eine Lösung gefunden ?

**Comment by Apollon77** [comment]
Wartena uf js-controller fix
