### ISSUE TITLE
Web adapter crashes with Error The pattern "http://192.168.188.111/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=95270002HD1PH3TA&user=user&password=password" is not a valid ID pattern

### ISSUE THREAD

**Issue by flispy** [ioBroker/ioBroker.js-controller#2444]
After upgrading js controller to version 5.0.12 the web adapter is restarting in a loop and then terminates.
my log says:

<img width="1769" alt="Bildschirmfoto 2023-09-20 um 11 03 11" src="https://github.com/ioBroker/ioBroker.js-controller/assets/15381702/17d64cbf-0a44-4fca-9a09-74c145c0c2bf">

with the old JS controller 4.x, in my VIS it was showing a snapshot from my camera. And I am wondering why this is not working anymore.

```
2023-09-20 10:39:28.427 - warn: host.iobroker-Server States 192.168.188.211:34678 Error from InMemDB: Error: The pattern "http://192.168.188.80/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=95270002HD1PH3TA&user=user&password=password" is not a valid ID pattern
--
at Object.pattern2RegEx (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)
at StatesInMemoryServer.handleSubscribe (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/inMemFileDB.ts:324:59)
at StatesInMemoryServer._subscribeForClient (/opt/iobroker/node_modules/@iobroker/db-states-file/src/lib/states/statesInMemFileDB.js:258:14)
at RedisHandler. (/opt/iobroker/node_modules/@iobroker/db-states-jsonl/src/lib/states/statesInMemServerRedis.js:395:26)
at RedisHandler.emit (node:events:514:28)
at RedisHandler.emit (node:domain:489:12)
at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/redisHandler.ts:209:37)
at processImmediate (node:internal/timers:476:21)
2023-09-20 10:42:05.848 - info: admin.0 (948) ==> Connected system.user.admin from ::ffff:192.168.188.111
2023-09-20 10:43:47.557 - info: admin.0 (948) <== Disconnect system.user.admin from ::ffff:192.168.188.111 admin
2023-09-20 10:45:01.523 - info: admin.0 (948) <== Disconnect system.user.admin from ::ffff:192.168.188.111
2023-09-20 10:45:30.162 - info: admin.0 (948) ==> Connected system.user.admin from ::ffff:192.168.188.111
2023-09-20 10:45:38.434 - info: admin.0 (948) <== Disconnect system.user.admin from ::ffff:192.168.188.111
2023-09-20 10:46:16.093 - info: admin.0 (948) ==> Connected system.user.admin from ::ffff:192.168.188.111
2023-09-20 10:46:29.878 - warn: host.iobroker-Server States 192.168.188.211:54372 Error from InMemDB: Error: The pattern "http://192.168.188.80/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=95270002HD1PH3TA&user=user&password=password" is not a valid ID pattern
at Object.pattern2RegEx (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2497:15)
at StatesInMemoryServer.handleSubscribe (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/inMemFileDB.ts:324:59)
at StatesInMemoryServer._subscribeForClient (/opt/iobroker/node_modules/@iobroker/db-states-file/src/lib/states/statesInMemFileDB.js:258:14)
at RedisHandler. (/opt/iobroker/node_modules/@iobroker/db-states-jsonl/src/lib/states/statesInMemServerRedis.js:395:26)
at RedisHandler.emit (node:events:514:28)
at RedisHandler.emit (node:domain:489:12)
at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/redisHandler.ts:209:37)
at processImmediate (node:internal/timers:476:21)
```

I have a multi instance with two servers running:
iobroker-master
Plattform: linux
Betriebssystem: linux
Architektur: x64
CPUs: 4
Geschwindigkeit: 1000 MHz
Modell: 12th Gen Intel(R) Core(TM) i3-1220P
RAM: 7.95 GB
System-Betriebszeit: 1 T. 15:19:35
Node.js: v18.17.1
time: 1695201167178
timeOffset: -120
NPM: 9.6.7
Anzahl der Adapter: 499
Datenträgergröße: 31.33 GB
freier Festplattenspeicher: 22.58 GB
Aktive Instanzen: 43
Hostname: iobroker-master

iobroker
Plattform: linux
Betriebssystem: linux
Architektur: x64
CPUs: 4
Geschwindigkeit: 1497 MHz
Modell: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
RAM: 11.74 GB
System-Betriebszeit: 1 T. 15:20:13
Node.js: v18.17.1
time: 1695201167300
timeOffset: -120
NPM: 9.6.7
Anzahl der Adapter: 499
Datenträgergröße: 30.83 GB
freier Festplattenspeicher: 12.8 GB
Aktive Instanzen: 7
Hostname: iobroker

<img width="242" alt="Bildschirmfoto 2023-09-20 um 11 19 54" src="https://github.com/ioBroker/ioBroker.js-controller/assets/15381702/8b607faf-8f9a-4efa-bc92-3bbedb7766ce">
<img width="944" alt="Bildschirmfoto 2023-09-20 um 11 19 29" src="https://github.com/ioBroker/ioBroker.js-controller/assets/15381702/baf0ce67-6e83-485d-a960-8ab577e31390">

**Comment by foxriver76** [comment]
installed web adapter version?

**Comment by flispy** [comment]
web: 6.1.2 but in instances it is showing 6.1.1 - see screenshots in issue

**Comment by foxriver76** [comment]
then it seems like, 6.1.1 is still running somehow, it should not crash with 6.1.2, you could try `iob upload web`

**Comment by flispy** [comment]
still showing 6.1.1 in instances after restarting

**Comment by foxriver76** [comment]
and the log on adapter start should also log the version. Is it saying 6.1.1 or 6.1.2?

**Comment by flispy** [comment]
`starting. Version 6.1.1 in /opt/iobroker/node_modules/iobroker.web, node: v18.17.1, js-controller: 5.0.12`

**Comment by foxriver76** [comment]
yes, then somehow old version running.. hm.. try  `iob upgrade web@6.1.2`

**Comment by flispy** [comment]
```
iobroker@iobroker:~$ iob upgrade web@6.1.2
Would you like to reinstall version 6.1.2 of web now? [(y)es, (n)o]: 
```

**Comment by flispy** [comment]
version on slave host was not updated and update was not shown in admin panel. Thanks @foxriver76 for helping
