### ISSUE TITLE
Admin Stürzt bei Fehlendem Teil im JSON ab und startet nicht mehr / restart loop

### ISSUE THREAD

**Issue by Frank795** [ioBroker/ioBroker.js-controller#2541]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Der Admin Adapter Stürzt komplett ab wenn Bei einem Alias das Quell-JSON nicht komplett ist. 
Ich habe Zigbee Taster Die beim Drücken den Zustand in den "action" Part im Jason schreiben, wenn längere Zeit keine Taste betätigt wurde "verschwindet" "action" aus dem JSON und der Admin schmiert ab.

Ich Hoffe ich konnte das einigermaßen beschreiben..... Wenn nicht dann bitte Fragen :) 

hier noch die JSON und die Alias config:

Alias Config :
`{
  "common": {
    "name": "action",
    "desc": "Manuell erzeugt",
    "role": "state",
    "type": "string",
    "read": true,
    "write": true,
    "def": "",
    "alias": {
      "id": "mqtt.0.zigbee2mqtt.BTN_Schlafzimmer",
      "read": "JSON.parse(val).action"
    }
  },
  "type": "state",
  "native": {},
  "_id": "alias.0.Test.Taster.action",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.frank",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.frank",
  "ts": 1700678627470
}` 

JSON ohne Action 
`
{
  "battery": 51,
  "last_seen": "2023-11-22T19:15:02+01:00",
  "linkquality": 109,
  "power_outage_count": 86,
  "voltage": 2927
}`

JSON mit action
`{
  "action": "button_6_single",
  "battery": 79,
  "last_seen": "2023-11-22T20:12:08+01:00",
  "linkquality": 109,
  "power_outage_count": 86,
  "voltage": 2968
}`

### To Reproduce

siehe Beschreibung  

### Expected behavior

Admin sollte nicht abstürzen. 

### Screenshots & Logfiles

`
2023-11-22 20:04:05.836  - error: javascript.0 (318522) An error happened which is most likely from one of your scripts, but the originating script could not be detected.
2023-11-22 20:04:05.836  - error: javascript.0 (318522) Error: Cannot read properties of undefined (reading 'toString')
2023-11-22 20:04:05.837  - error: javascript.0 (318522) TypeError: Cannot read properties of undefined (reading 'toString')
    at Object.formatAliasValue (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2759:35)
    at AdapterClass._getForeignState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:8852:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-22 20:04:05.848  - error: admin.0 (318317) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-11-22 20:04:05.849  - error: admin.0 (318317) unhandled promise rejection: Cannot read properties of undefined (reading 'toString')
2023-11-22 20:04:05.954  - error: admin.0 (318317) TypeError: Cannot read properties of undefined (reading 'toString')
    at Object.formatAliasValue (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2759:35)
    at Admin._getForeignState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:8852:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-22 20:04:05.955  - error: admin.0 (318317) Cannot read properties of undefined (reading 'toString')
2023-11-22 20:04:05.963  - warn: admin.0 (318317) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-11-22 20:04:06.507  - error: host.iobroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-11-22 20:04:06.508  - error: host.iobroker Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'toString')
2023-11-22 20:04:06.508  - error: host.iobroker Caught by controller[0]:     at Object.formatAliasValue (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2759:35)
2023-11-22 20:04:06.508  - error: host.iobroker Caught by controller[0]:     at Admin._getForeignState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:8852:31)
2023-11-22 20:04:06.508  - error: host.iobroker Caught by controller[0]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-22 20:04:06.508  - error: host.iobroker instance system.adapter.admin.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
`

### Adapter version

6.12.0

### js-controller version

5.0.16

### Node version

18.18.2

### Operating system

Debian 12

**Comment by foxriver76** [comment]
TODO for controller: if the users `transform` function returns `undefined` return `null` instead, like we do when an exception happens during the users function.
