### ISSUE TITLE
Greenlock problem

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.js-controller#258]
****

2018-09-14 01:23:29.604 - debug: web.0 system.adapter.admin.1: logging false
--
2018-09-14 01:23:29.607 - debug: cloud.0 system.adapter.admin.1: logging false
2018-09-14 01:23:29.615 - debug: cloud.1 system.adapter.admin.1: logging false
2018-09-14 01:23:29.618 - debug: backitup.0 system.adapter.admin.1: logging false
2018-09-14 01:23:29.621 - error: Caught by controller[0]: ==========================================================
2018-09-14 01:23:29.623 - error: Caught by controller[0]: == greenlock.js (v2.2.0+) ==
2018-09-14 01:23:29.624 - error: Caught by controller[0]: ==========================================================
2018-09-14 01:23:29.624 - error: Caught by controller[0]: Please specify 'version' option:
2018-09-14 01:23:29.624 - error: Caught by controller[0]: 'draft-12' for Let's Encrypt v2 and ACME draft 12
2018-09-14 01:23:29.624 - error: Caught by controller[0]: ('v02' is an alias of 'draft-12'
2018-09-14 01:23:29.625 - error: Caught by controller[0]: or
2018-09-14 01:23:29.625 - error: Caught by controller[0]: 'v01' for Let's Encrypt v1 (deprecated)
2018-09-14 01:23:29.625 - error: Caught by controller[0]: (also 'npm install --save le-acme-core' as this legacy dependency will soon be removed)
2018-09-14 01:23:29.625 - error: Caught by controller[0]: This will be required in versions v2.3+
2018-09-14 01:23:29.626 - error: Caught by controller[0]: Detected Let's Encrypt v02 URL. Changing version to draft-12.
2018-09-14 01:23:29.626 - error: Caught by controller[1]: TypeError: util.promisify is not a function
2018-09-14 01:23:29.626 - error: Caught by controller[1]: at /mnt/opt/iobroker/node_modules/greenlock/index.js:17:33
2018-09-14 01:23:29.627 - error: Caught by controller[1]: at Array.forEach (native)
2018-09-14 01:23:29.627 - error: Caught by controller[1]: at promisifyAllSelf (/mnt/opt/iobroker/node_modules/greenlock/index.js:15:20)
2018-09-14 01:23:29.627 - error: Caught by controller[1]: at Object.Greenlock.create (/mnt/opt/iobroker/node_modules/greenlock/index.js:258:13)
2018-09-14 01:23:29.628 - error: Caught by controller[1]: at Object.createServer (/mnt/opt/iobroker/node_modules/iobroker.js-controller/lib/letsencrypt.js:55:26)
2018-09-14 01:23:29.628 - error: Caught by controller[1]: at __construct (/mnt/opt/iobroker/node_modules/iobroker.admin/lib/web.js:426:32)
2018-09-14 01:23:29.628 - error: Caught by controller[1]: at new Web (/mnt/opt/iobroker/node_modules/iobroker.admin/lib/web.js:457:7)
2018-09-14 01:23:29.628 - error: Caught by controller[1]: at /mnt/opt/iobroker/node_modules/iobroker.admin/main.js:292:29
2018-09-14 01:23:29.629 - error: Caught by controller[1]: at Socket. (/mnt/opt/iobroker/node_modules/iobroker.admin/main.js:351:35)
2018-09-14 01:23:29.629 - error: Caught by controller[1]: at Socket.onack (/mnt/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
2018-09-14 01:23:29.629 - error: Caught by controller[1]: at Socket.onpacket (/mnt/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
2018-09-14 01:23:29.629 - error: Caught by controller[1]: at Manager. (/mnt/opt/iobroker/node_modules/component-bind/index.js:21:15)
2018-09-14 01:23:29.630 - error: Caught by controller[1]: at Manager.Emitter.emit (/mnt/opt/iobroker/node_modules/component-emitter/index.js:133:20)
2018-09-14 01:23:29.630 - error: Caught by controller[1]: at Manager.ondecoded (/mnt/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:332:8)
2018-09-14 01:23:29.630 - error: Caught by controller[1]: at Decoder. (/mnt/opt/iobroker/node_modules/component-bind/index.js:21:15)
2018-09-14 01:23:29.630 - error: Caught by controller[1]: at Decoder.Emitter.emit (/mnt/opt/iobroker/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
2018-09-14 01:23:29.631 - error: Caught by controller[2]: 2018-09-14 01:23:29.455 - admin.1 uncaught exception: util.promisify is not a function
2018-09-14 01:23:29.631 - error: Caught by controller[3]: 2018-09-14 01:23:29.458 - admin.1 TypeError: util.promisify is not a function
2018-09-14 01:23:29.631 - error: Caught by controller[3]: at /mnt/opt/iobroker/node_modules/greenlock/index.js:17:33
2018-09-14 01:23:29.632 - error: Caught by controller[3]: at Array.forEach (native)
2018-09-14 01:23:29.632 - error: Caught by controller[3]: at promisifyAllSelf (/mnt/opt/iobroker/node_modules/greenlock/index.js:15:20)
2018-09-14 01:23:29.632 - error: Caught by controller[3]: at Object.Greenlock.create (/mnt/opt/iobroker/node_modules/greenlock/index.js:258:13)
2018-09-14 01:23:29.632 - error: Caught by controller[3]: at Object.createServer (/mnt/opt/iobroker/node_modules/iobroker.js-controller/lib/letsencrypt.js:55:26)
2018-09-14 01:23:29.633 - error: Caught by controller[3]: at __construct (/mnt/opt/iobroker/node_modules/iobroker.admin/lib/web.js:426:32)
2018-09-14 01:23:29.633 - error: Caught by controller[3]: at new Web (/mnt/opt/iobroker/node_modules/iobroker.admin/lib/web.js:457:7)
2018-09-14 01:23:29.633 - error: Caught by controller[3]: at /mnt/opt/iobroker/node_modules/iobroker.admin/main.js:292:29
2018-09-14 01:23:29.634 - error: Caught by controller[3]: at Socket. (/mnt/opt/iobroker/node_modules/iobroker.admin/main.js:351:35)
2018-09-14 01:23:29.634 - error: Caught by controller[3]: at Socket.onack (/mnt/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
2018-09-14 01:23:29.634 - error: Caught by controller[3]: at Socket.onpacket (/mnt/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
2018-09-14 01:23:29.634 - error: Caught by controller[3]: at Manager. (/mnt/opt/iobroker/node_modules/component-bind/index.js:21:15)
2018-09-14 01:23:29.635 - error: Caught by controller[3]: at Manager.Emitter.emit (/mnt/opt/iobroker/node_modules/component-emitter/index.js:133:20)
2018-09-14 01:23:29.635 - error: Caught by controller[3]: at Manager.ondecoded (/mnt/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:332:8)
2018-09-14 01:23:29.635 - error: Caught by controller[3]: at Decoder. (/mnt/opt/iobroker/node_modules/component-bind/index.js:21:15)
2018-09-14 01:23:29.635 - error: Caught by controller[3]: at Decoder.Emitter.emit (/mnt/opt/iobroker/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
2018-09-14 01:23:29.636 - error: host.odroid instance system.adapter.admin.1 terminated with code 0 (OK)
2018-09-14 01:23:29.636 - info: host.odroid Restart adapter system.adapter.admin.1 because enabled

**Comment by peterbaumert** [comment]
having the same issue, is there any workaround?

**Comment by Apollon77** [comment]
Please try js.controller 1.5.7 from latest

**Comment by Apollon77** [comment]
1.5.7 is released, so I close here

**Comment by peterbaumert** [comment]
same on 1.5.7 for me

**Comment by adeptp** [comment]
host.bananapipro	2019-03-30 13:03:32.164	error	instance system.adapter.web.1 terminated with code 0 (OK)
Caught	2019-03-30 13:03:32.163	error	by controller[0]: at Decoder.add (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-parser/index.js:246:12)
Caught	2019-03-30 13:03:32.162	error	by controller[0]: at Decoder.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:134:20)
Caught	2019-03-30 13:03:32.161	error	by controller[0]: at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught	2019-03-30 13:03:32.161	error	by controller[0]: at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:332:8)
Caught	2019-03-30 13:03:32.160	error	by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
Caught	2019-03-30 13:03:32.159	error	by controller[0]: at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught	2019-03-30 13:03:32.158	error	by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
Caught	2019-03-30 13:03:32.157	error	by controller[0]: at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
Caught	2019-03-30 13:03:32.157	error	by controller[0]: at Socket.that.getForeignObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:724:21)
Caught	2019-03-30 13:03:32.156	error	by controller[0]: at adapter.getCertificates (/opt/iobroker/node_modules/iobroker.web/main.js:239:29)
Caught	2019-03-30 13:03:32.155	error	by controller[0]: at initWebServer (/opt/iobroker/node_modules/iobroker.web/main.js:847:28)
Caught	2019-03-30 13:03:32.154	error	by controller[0]: at Object.createServer (/opt/iobroker/node_modules/iobroker.js-controller/lib/letsencrypt.js:55:26)
Caught	2019-03-30 13:03:32.153	error	by controller[0]: at Object.Greenlock.create (/opt/iobroker/node_modules/greenlock/index.js:266:13)
Caught	2019-03-30 13:03:32.153	error	by controller[0]: at promisifyAllSelf (/opt/iobroker/node_modules/greenlock/index.js:16:20)
Caught	2019-03-30 13:03:32.152	error	by controller[0]: at Array.forEach (native)
Caught	2019-03-30 13:03:32.149	error	by controller[0]: at /opt/iobroker/node_modules/greenlock/index.js:18:33
Caught	2019-03-30 13:03:32.147	error	by controller[0]: TypeError: util.promisify is not a function

 js.controller 1.5.7

**Comment by Apollon77** [comment]
is this fixed?
