### ISSUE TITLE
[bug]: View/attempted delete of channel with non-ascii character crashes Admin (appears to cause whole IOB restart)

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.js-controller#2613]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

I was doing a bit of work on smartmeter and as part of that some channels with non-ascii characters were created in error by that adatper. Eg:

```JSON
{
  "type": "channel",
  "common": {
    "name": "0617641392\u0002"
  },
  "native": {},
  "from": "system.adapter.smartmeter.0",
  "user": "system.user.admin",
  "ts": 1679559871712,
  "_id": "smartmeter.0.0617641392\u0002",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

Attempting to delete this channel with Admin causes it to crash.

Attempting to edit this channel (the above JSON) with Admin opens the edit window before crashing Admin adatper.

Both of the above also cause js-controller to restart too (see log below).

### To Reproduce

Appears to happen when trying to manipulate channels with with non-ascii characters in the name/id.

### Expected behavior

One should be able to view/edit channels as normal.

### Screenshots & Logfiles

```
2024-02-16 18:38:13.252  - ^[[31merror^[[39m: host.pl uncaught exception: The pattern "smartmeter.0.0617641392^B.*" is not a valid ID pattern
2024-02-16 18:38:13.253  - ^[[31merror^[[39m: host.pl Error: The pattern "smartmeter.0.0617641392^B.*" is not a valid ID pattern
    at Object.pattern2RegEx (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2470:15)
    at ObjectsInMemoryServer._getKeys (/opt/iobroker/node_modules/@iobroker/db-objects-file/src/lib/objects/objectsInMemFileDB.js:850:36)
    at ObjectsInMemoryServer._handleScanOrKeys (/opt/iobroker/node_modules/@iobroker/db-objects-jsonl/src/lib/objects/objectsInMemServerRedis.js:904:29)
    at RedisHandler.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-objects-jsonl/src/lib/objects/objectsInMemServerRedis.js:733:25)
    at RedisHandler.emit (node:events:513:28)
    at RedisHandler.emit (node:domain:489:12)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/redisHandler.ts:209:37)
    at processImmediate (node:internal/timers:466:21)
```

### Adapter version

6.13.16

### js-controller version

5.0.17

### Node version

v16.20.2

### Operating system

Raspbian GNU/Linux 11 (bullseye)

**Comment by foxriver76** [comment]
Can you tell us with which method the channel has been created? I tried via a `setForeignObjectAsync('smartmeter.0.0617641392\u0002')` and the controller correctly replaces it `Used invalid characters: smartmeter.0.0617641392 changed to smartmeter.0.0617641392_`

**Comment by raintonr** [comment]
> Can you tell us with which method the channel has been created?

It was done in my fork of smartmeter with `adapter.setObjectNotExists`:

https://github.com/Apollon77/ioBroker.smartmeter/pull/330/files#diff-4655601d6375e21eed77db1c2a39ffdc7df32c62b2ee85396a18c697387ab117R111

**Comment by foxriver76** [comment]
Can you somehow reproduce it with a string not with api data so I could reproduce this too? I tried a lot also with setObjectNotExists, no luck in reproducing
