### ISSUE TITLE
[enhancement]: check all active repositories for blocked versions (js-controller 6.x)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.js-controller#2718]
### No existing issues.

- [X] There is no existing issue for my request.

### Description

https://github.com/ioBroker/ioBroker.js-controller/blob/b4514c4c9ffbcac00057394c3741291adf3c946c/packages/controller/src/lib/blocklistManager.ts#L111-L113

### Why?

Maybe the current adapter isn't in the first active repo.

**Comment by foxriver76** [comment]
Hm okay, this would be really edgy.. I think the multi repo approach is just used by some customers of ioBroker GmbH to get additional non-public available adapters. But yes, should maybe be checked too.

**Comment by klein0r** [comment]
Okay, but it isn't ensured that the default `stable` / `beta` repository has index 0

And bonus check: Add check if `repo` has been set. Maybe the list of `activeRepo` contains a key which is not available in `system.repositories`.

**Comment by foxriver76** [comment]
As said for more than 99.9 % of installations there will be only one activeRepo, thus it is edgy af but as also stated yes should  maybe be checked too ;-)

**Comment by klein0r** [comment]
> thus it is edgy af

😄 yes, but I've got an exception (don't know why, objects are correct and `json: null` should be handled) and saw the `[0]`.

```
Uncaught Rejection: TypeError: Cannot read properties of undefined (reading 'json')
    at BlocklistManager.internalIsAdapterVersionBlocked (file:///home/mkleine/ioBroker.javascript/.dev-server/default/node_modules/iobroker.js-controller/build/esm/lib/blocklistManager.js:69:35)
    at BlocklistManager.isAdapterVersionBlocked (file:///home/mkleine/ioBroker.javascript/.dev-server/default/node_modules/iobroker.js-controller/build/esm/lib/blocklistManager.js:58:21)
    at async startInstance (file:///home/mkleine/ioBroker.javascript/.dev-server/default/node_modules/iobroker.js-controller/build/esm/main.js:3196:23)
Cannot read properties of undefined (reading 'json')
TypeError: Cannot read properties of undefined (reading 'json')
    at BlocklistManager.internalIsAdapterVersionBlocked (file:///home/mkleine/ioBroker.javascript/.dev-server/default/node_modules/iobroker.js-controller/build/esm/lib/blocklistManager.js:69:35)
    at BlocklistManager.isAdapterVersionBlocked (file:///home/mkleine/ioBroker.javascript/.dev-server/default/node_modules/iobroker.js-controller/build/esm/lib/blocklistManager.js:58:21)
    at async startInstance (file:///home/mkleine/ioBroker.javascript/.dev-server/default/node_modules/iobroker.js-controller/build/esm/main.js:3196:23)
2024-05-02 11:29:24.380  - error: host.dev-javascript-iobroker-dev uncaught exception: Cannot read properties of undefined (reading 'json')
2024-05-02 11:29:24.381  - error: host.dev-javascript-iobroker-dev TypeError: Cannot read properties of undefined (reading 'json')
    at BlocklistManager.internalIsAdapterVersionBlocked (file:///home/mkleine/ioBroker.javascript/.dev-server/default/node_modules/iobroker.js-controller/build/esm/lib/blocklistManager.js:69:35)
    at BlocklistManager.isAdapterVersionBlocked (file:///home/mkleine/ioBroker.javascript/.dev-server/default/node_modules/iobroker.js-controller/build/esm/lib/blocklistManager.js:58:21)
    at async startInstance (file:///home/mkleine/ioBroker.javascript/.dev-server/default/node_modules/iobroker.js-controller/build/esm/main.js:3196:23)
```

**Comment by foxriver76** [comment]
Out of curiosity: Can you show your `activeRepo` array? And it is not a valid key of  your sytem repo repositories?

**Comment by klein0r** [comment]
It was just a new installation with `dev-server setup --jsController dev`. Unable to start the dev-server because of that issue. But ObjectDB-jsonl looked fine. I have to check if I can reproduce that issue with another new dev-server setup.

**Comment by foxriver76** [comment]
Okay, that's interesting, because with the default objects this should not happen, activeRepo is normally `["stable"]` and sys.repo has stable with `json: null`

**Comment by foxriver76** [comment]
Okay, dev-server still sets a string to activeRepo https://github.com/ioBroker/dev-server/blob/91127821af24b31b370b53b2215789a983c5056d/src/index.ts#L1404
