### ISSUE TITLE
Error during Logfile delete under Windows 10 Build 1809 NPM 6.4.1 Nodes.js 10.14.1

### ISSUE THREAD

**Issue by KL-AU-S** [ioBroker/ioBroker.js-controller#283]
Durng the deletion of the Logfile iobroker crashes see LOG:

2018-12-04 10:51:50.182  - [34mdebug[39m: admin.0 system.adapter.admin.0: logging true
2018-12-04 10:52:01.953  - [31merror[39m: uncaught exception: Callback must be a function
2018-12-04 10:52:01.968  - [31merror[39m: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1156:14)
    at processMessage (C:\ioBroker\node_modules\iobroker.js-controller\controller.js:1417:44)
    at change (C:\ioBroker\node_modules\iobroker.js-controller\controller.js:226:25)
    at Immediate.<anonymous> (C:\ioBroker\node_modules\iobroker.js-controller\lib\states\statesInMemServer.js:536:25)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
2018-12-04 10:52:01.972  - [32minfo[39m: iobroker _restart
2018-12-04 10:52:05.070  - [32minfo[39m: iobroker Starting node restart.js
2018-12-04 10:52:05.298  - [32minfo[39m: iobroker exit 0
2018-12-04 10:52:10.808  - [32minfo[39m: host.DESKTOP-006CT2J instance system.adapter.discovery.0 terminated with code 4294967295 ()
2018-12-04 10:52:11.730  - [32minfo[39m: host.DESKTOP-006CT2J instance system.adapter.cloud.0 terminated with code 4294967295 ()
2018-12-04 10:52:12.163  - [32minfo[39m: host.DESKTOP-006CT2J force terminating
2018-12-04 10:52:12.164  - [32minfo[39m: Adapter admin still running
2018-12-04 10:52:12.222  - [32minfo[39m: Adapter mihome-vacuum still running
2018-12-04 10:52:12.225  - [32minfo[39m: Adapter javascript still running
2018-12-04 10:52:12.225  - [32minfo[39m: Adapter web still running
2018-12-04 10:52:12.250  - [32minfo[39m: Adapter scenes still running
2018-12-04 10:52:12.250  - [32minfo[39m: Adapter mihome still running
2018-12-04 10:52:12.251  - [32minfo[39m: Adapter maxcube still running
2018-12-04 10:52:12.251  - [32minfo[39m: Adapter shelly still running
2018-12-04 10:52:12.252  - [32minfo[39m: Adapter broadlink2 still running
2018-12-04 10:52:12.253  - [32minfo[39m: Adapter broadlink2 still running
2018-12-04 10:52:12.253  - [32minfo[39m: Adapter alexa2 still running
2018-12-04 10:52:12.254  - [32minfo[39m: Adapter yeelight-2 still running
2018-12-04 10:52:13.180  - [31merror[39m: host.DESKTOP-006CT2J instance system.adapter.mihome-vacuum.0 terminated with code 4294967295 ()
2018-12-04 10:52:13.181  - [32minfo[39m: host.DESKTOP-006CT2J Restart adapter system.adapter.mihome-vacuum.0 because enabled
2018-12-04 10:52:13.428  - [31merror[39m: host.DESKTOP-006CT2J instance system.adapter.javascript.0 terminated with code 4294967295 ()
2018-12-04 10:52:13.429  - [32minfo[39m: host.DESKTOP-006CT2J Restart adapter system.adapter.javascript.0 because enabled
2018-12-04 10:52:28.502  - [32minfo[39m: host.DESKTOP-006CT2J iobroker.js-controller version 1.4.2 js-controller starting
2018-12-04 10:52:28.540  - [32minfo[39m: host.DESKTOP-006CT2J Copyright (c) 2014-2018 bluefox, 2014 hobbyquaker
2018-12-04 10:52:28.540  - [32minfo[39m: host.DESKTOP-006CT2J hostname: DESKTOP-006CT2J, node: v10.14.1
2018-12-04 10:52:28.578  - [32minfo[39m: host.DESKTOP-006CT2J ip addresses: fe80::4141:36e6:c949:69a 192.168.0.139

**Comment by AlCalzone** [comment]
The problem is [here](https://github.com/ioBroker/ioBroker.js-controller/blob/master/controller.js#L1649) in v1.5.3
The callback parameter is not optional: https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback

**Comment by Apollon77** [comment]
We should simply switch to writeFileSync or ?!

**Comment by Apollon77** [comment]
1.6.0-dev has already fixed that ... so we should backport it in 1.5.x

**Comment by AlCalzone** [comment]
The async version is fine as we don't have to wait for the file being written. We just need to pass an empty callback

**Comment by Apollon77** [comment]
proposed this ecause it was changed in 1.6.0-dev that way by using Sync method

**Comment by Apollon77** [comment]
;-) i wiould try to stay consitent ... so when we say we do not need to wait then we should change in 1.6.0-dev too ... just "the same" :-)
