### ISSUE TITLE
[bug]: Keine Master/Slave Verbindung möglich

### ISSUE THREAD

**Issue by GWehst** [ioBroker/ioBroker.js-controller#2971]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

Guten Tag,
ich habe ein Problem mit Master/Slave.
Nach der Umstellung auf Bookwurm und Nodejs v20.18.0 bekomme ich keine Kopplung hin.
Es sind beide Rpi4 mit 8Gb(Master und 4Gb(Slave)
der Master sagt:
Please check the binding of the configured jsonl server to allow remote connections.
Please restart ioBroker for the changes to take effect: "iobroker restart"

Multihost discovery server: enabled
Discovery authentication: enabled
Persistent activation: disabled
Objects: jsonl on 0.0.0.0
States: jsonl on 0.0.0.0

DerSlave antwortet:
Error: No configuration received!
at file:///opt/iobroker/node_modules/@iobroker/js-controller-cli/src/lib/setup/setupMultihost.ts:339:26
at onFinished (file:///opt/iobroker/node_modules/@iobroker/js-controller-cli/src/lib/setup/multihostClient.ts:267:21)
at Timeout. (file:///opt/iobroker/node_modules/@iobroker/js-controller-cli/src/lib/setup/multihostClient.ts:98:17)
at listOnTimeout (node:internal/timers:581:17)
at processTimers (node:internal/timers:519:7)

Ich komme nicht wirklich weiter.
MfG

### JS-controller version

6.0.11

### Node version

20.18.0

**Comment by Apollon77** [comment]
>  Please restart ioBroker for the changes to take effect: "iobroker restart"

Did you do that and tried again?

**Comment by GWehst** [comment]
Ja, 
Master: iobroker multihost enable
               iobroker restart
Slave: iobroker multihost connect
           iobroker restart

**Comment by GWehst** [comment]
Guten Abend,
hat jemand eine Idee wie ich das Problem lösen könnte?
Mit freundlichen Grüßen

**Comment by mcm1957** [comment]
Ja, hab ich dir schon geraten:
https://github.com/ioBroker/ioBroker.js-controller/issues/2706#issuecomment-2486173750

> I suggest to ask such questions at our forum. https://forum.iobtoker.net

Es ist zwar nicht auszuschließen, dass ein bisher unbekannter Fehler im js-controller vorliegt aber wahrscheinlicher ist derzeit eine spezielle Konstellation deines Systems. Im Forum (https::/forum.iobroker.net) werden mit Sicherheit mehr Helfer einen Tipp haben.

**Comment by GWehst** [comment]
Vielen Dank
