### ISSUE TITLE
controller update: Cannot read property 'resolve' of undefined

### ISSUE THREAD

**Issue by p33k** [ioBroker/ioBroker.js-controller#364]
I get an error when I try to update js controller on my Windows 10 ioBroker installation:

```
C:\iobroker>node node_modules/iobroker.js-controller/iobroker.js upgrade self
Update js-controller from @1.5.3 to @1.5.7
NPM version: 6.7.0
npm install iobroker.js-controller@1.5.7 --unsafe-perm --production --save --prefix "C:/iobroker" (System call)
npm ERR! Cannot read property 'resolve' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\keven\AppData\Roaming\npm-cache\_logs\2019-04-11T21_19_01_039Z-debug.log
Host "ioServer" (win32) updated
Starting node restart.js
```

debug log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\iobroker\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'iobroker.js-controller@1.5.7',
1 verbose cli   '--unsafe-perm',
1 verbose cli   '--production',
1 verbose cli   '--save',
1 verbose cli   '--prefix',
1 verbose cli   'C:/iobroker' ]
2 info using npm@6.7.0
3 info using node@v10.15.0
4 verbose npm-session 17e19e338959579b
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for iobroker.js-controller@1.5.7 Cannot read property 'resolve' of undefined
8 timing stage:rollbackFailedOptional Completed in 16ms
9 timing stage:runTopLevelLifecycles Completed in 78ms
10 verbose stack TypeError: Cannot read property 'resolve' of undefined
10 verbose stack     at regFetch (C:\iobroker\node_modules\npm\node_modules\npm-registry-fetch\index.js:76:23)
10 verbose stack     at fetchPackument (C:\iobroker\node_modules\npm\node_modules\pacote\lib\fetchers\registry\packument.js:42:10)
10 verbose stack     at packument (C:\iobroker\node_modules\npm\node_modules\pacote\lib\fetchers\registry\packument.js:20:10)
10 verbose stack     at getManifest (C:\iobroker\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:22:10)
10 verbose stack     at manifest (C:\iobroker\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:13:10)
10 verbose stack     at Object.manifest (C:\iobroker\node_modules\npm\node_modules\pacote\lib\fetchers\registry\index.js:17:12)
10 verbose stack     at Object.Fetcher#manifest [as manifest] (C:\iobroker\node_modules\npm\node_modules\pacote\node_modules\protoduck\node_modules\genfun\lib\genfun.js:15:38)
10 verbose stack     at manifest (C:\iobroker\node_modules\npm\node_modules\pacote\lib\fetch.js:23:18)
10 verbose stack     at pinflight (C:\iobroker\node_modules\npm\node_modules\pacote\manifest.js:24:12)
10 verbose stack     at C:\iobroker\node_modules\npm\node_modules\promise-inflight\inflight.js:29:24
10 verbose stack     at Promise._execute (C:\iobroker\node_modules\npm\node_modules\bluebird\js\release\debuggability.js:313:9)
10 verbose stack     at Promise._resolveFromExecutor (C:\iobroker\node_modules\npm\node_modules\bluebird\js\release\promise.js:483:18)
10 verbose stack     at new Promise (C:\iobroker\node_modules\npm\node_modules\bluebird\js\release\promise.js:79:10)
10 verbose stack     at _inflight (C:\iobroker\node_modules\npm\node_modules\promise-inflight\inflight.js:28:25)
10 verbose stack     at C:\iobroker\node_modules\npm\node_modules\promise-inflight\inflight.js:22:14
10 verbose stack     at tryCatcher (C:\iobroker\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose cwd C:\iobroker
12 verbose Windows_NT 10.0.16299
```

What is the problem here?

**Comment by Apollon77** [comment]
Please try latest npm or npm 6.4.1. this error seems to come from npm in my understanding.

**Comment by Stabilostick** [comment]
With the new version of the Windows Setup for ioBroker I use npm 6.9.0 with no problems till now.

See https://forum.iobroker.net/post/247974
