### ISSUE TITLE
Start Redis failed.

### ISSUE THREAD

**Issue by SchumyHao** [ioBroker/ioBroker.js-controller#369]
My ioBroker system enabled multihost system, and works for a long time.

Today, I want to setup redis on master system. The setup step like this:

```bash
# iobroker system is running
> sudo apt-get update
> sudo apt-get install redis-server
> redis-server

> sudo nano /etc/redis/redis.conf
# set bind 0.0.0.0
> sudo service redis-server restart
systemctl status redis-server.service

● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-04-27 11:37:39 CST; 1min 32s ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
  Process: 5252 ExecStop=/bin/kill -s TERM $MAINPID (code=exited, status=0/SUCCESS)
  Process: 5256 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf (code=exited, status=0/SUCCESS)
 Main PID: 5278 (redis-server)
    Tasks: 4 (limit: 4915)
   CGroup: /system.slice/redis-server.service
           └─5278 /usr/bin/redis-server 0.0.0.0:6379

4月 27 11:37:38 schumy-virtual-machine systemd[1]: Starting Advanced key-value store...
4月 27 11:37:39 schumy-virtual-machine systemd[1]: redis-server.service: Can't open PID file /var/run/redis/redis-server.pid (yet?) after start: No such file 
4月 27 11:37:39 schumy-virtual-machine systemd[1]: Started Advanced key-value store. 

> iobroker setup custom

Type of objects DB [(f)ile, (c)ouch, (r)edis], default [file]: r
Host / Unix Socket of objects DB(redis), default[127.0.0.1]:
Port of objects DB(redis), default[6379]: 
Type of states DB [(f)file, (r)edis], default [redis]: 
Host / Unix Socket of states DB (redis), default[127.0.0.1]: 
Port of states DB (redis), default[6379]: 
Host name of this machine [schumy-virtual-machine]: 
creating conf/iobroker.json

> iobroker restart
> iobroker status

iobroker is not running

Objects type: redis
States  type: redis
```

ioBroker service seems not running.

The log shows like this
```
4月 27 12:17:55 schumy-virtual-machine systemd[1]: Stopped ioBroker Server.
4月 27 12:17:55 schumy-virtual-machine systemd[1]: Started ioBroker Server.
4月 27 12:17:55 schumy-virtual-machine bash[15233]: /opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInRedis.js:969
4月 27 12:17:55 schumy-virtual-machine bash[15233]:         if (regUser.test(id) || regGroup.test(id)) {
4月 27 12:17:55 schumy-virtual-machine bash[15233]:                          ^
4月 27 12:17:55 schumy-virtual-machine bash[15233]: ReferenceError: id is not defined
4月 27 12:17:55 schumy-virtual-machine bash[15233]:     at checkObjectRights (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInRedis.js:969:26)
4月 27 12:17:55 schumy-virtual-machine bash[15233]:     at ObjectsInRedis.subscribe (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInRedis.js:1041:13)
4月 27 12:17:55 schumy-virtual-machine bash[15233]:     at init (/opt/iobroker/node_modules/iobroker.js-controller/controller.js:2828:13)
4月 27 12:17:55 schumy-virtual-machine bash[15233]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/controller.js:2879:1)
4月 27 12:17:55 schumy-virtual-machine bash[15233]:     at Module._compile (module.js:653:30)
4月 27 12:17:55 schumy-virtual-machine bash[15233]:     at Object.Module._extensions..js (module.js:664:10)
4月 27 12:17:55 schumy-virtual-machine bash[15233]:     at Module.load (module.js:566:32)
4月 27 12:17:55 schumy-virtual-machine bash[15233]:     at tryModuleLoad (module.js:506:12)
4月 27 12:17:55 schumy-virtual-machine bash[15233]:     at Function.Module._load (module.js:498:3)
4月 27 12:17:55 schumy-virtual-machine bash[15233]:     at Function.Module.runMain (module.js:694:10)
4月 27 12:17:55 schumy-virtual-machine systemd[1]: iobroker.service: Main process exited, code=exited, status=1/FAILURE
4月 27 12:17:55 schumy-virtual-machine systemd[1]: iobroker.service: Failed with result 'exit-code'.
```

Did I missed some settings?

**Comment by SchumyHao** [comment]
Redis settings

```
schumy@schumy-virtual-machine:~$ redis-cli
127.0.0.1:6379> PING
PONG
127.0.0.1:6379> INFO
# Server
redis_version:4.0.9
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:76095d16786fbcba
redis_mode:standalone
os:Linux 4.15.0-46-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:7.3.0
process_id:14471
run_id:cbe509f37db7fc935cde108c394804d6249feec1
tcp_port:6379
uptime_in_seconds:5755
uptime_in_days:0
hz:10
lru_clock:12838396
executable:/usr/bin/redis-server
config_file:/etc/redis/redis.conf

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:841280
used_memory_human:821.56K
used_memory_rss:4038656
used_memory_rss_human:3.85M
used_memory_peak:940736
used_memory_peak_human:918.69K
used_memory_peak_perc:89.43%
used_memory_overhead:832126
used_memory_startup:782496
used_memory_dataset:9154
used_memory_dataset_perc:15.57%
total_system_memory:7307538432
total_system_memory_human:6.81G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:4.80
mem_allocator:jemalloc-3.6.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1556336513
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:21
total_commands_processed:12
instantaneous_ops_per_sec:0
total_net_input_bytes:185
total_net_output_bytes:37528
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:262b75131ae359c583558fbdaef4095b206211a6
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:5.16
used_cpu_user:1.90
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Cluster
cluster_enabled:0

# Keyspace
```

**Comment by Apollon77** [comment]
Which js-Controller? Before 2.0.0 (GitHub) redis is only supported for states!! Change objects back to files and you are good.

**Comment by SchumyHao** [comment]
thanks, i,ll try to fix this settings

**Comment by SchumyHao** [comment]
Thanks @Apollon77 . After set objects to files, this issue fixed.
