### ISSUE TITLE
[2.0.0] TypeError: Cannot read property 'psubscribe' of null (objects-redis)

### ISSUE THREAD

**Issue by Juweii** [ioBroker/ioBroker.js-controller#378]
I found a problem after upgrading my slave of my multihost setup to master branch:
```
2019-05-28 11:50:48.534  - ^[[32minfo^[[39m: host.CaraNET iobroker.js-controller version 2.0.0 js-controller starting
2019-05-28 11:50:48.574  - ^[[32minfo^[[39m: host.CaraNET Copyright (c) 2014-2019 bluefox, 2014 hobbyquaker
2019-05-28 11:50:48.580  - ^[[32minfo^[[39m: host.CaraNET hostname: CaraNET, node: v10.15.3
2019-05-28 11:50:48.591  - ^[[32minfo^[[39m: host.CaraNET ip addresses: 192.168.0.2
2019-05-28 11:50:50.114  - ^[[32minfo^[[39m: Objects using TCP/Redis protocol not available, falling back to socket.io protocol
2019-05-28 11:50:50.513  - ^[[32minfo^[[39m: host.CaraNET {"type":"file","server":false} connected
2019-05-28 11:50:50.528  - ^[[31merror^[[39m: host.CaraNET uncaught exception: Cannot read property 'psubscribe' of null
2019-05-28 11:50:50.542  - ^[[31merror^[[39m: host.CaraNET TypeError: Cannot read property 'psubscribe' of null
    at _0x15e8fc._subscribe (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:40434)
    at _0x591885.(anonymous function) (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:40880)
    at Object.checkObjectRights (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsUtils.js:540:16)
    at _0x15e8fc.subscribeConfig (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:40707)
    at _0x15e8fc.subscribe (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:40994)
    at createObjects (/opt/iobroker/node_modules/iobroker.js-controller/main.js:2965:17)
    at Object.connected (/opt/iobroker/node_modules/iobroker.js-controller/main.js:369:26)
    at Socket.ObjectsInMemClient.client.on (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemClientSocketIo.js:89:76)
    at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
    at Socket.emit (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:138:10)
2019-05-28 11:50:50.571  - ^[[32minfo^[[39m: host.CaraNET iobroker _restart
2019-05-28 11:50:50.636  - ^[[32minfo^[[39m: host.CaraNET terminated
```

The multihost master is still 1.5.11 from npm.

I just wanted to test compact mode on my slave and not to kill the master server.
Is that an issue of mixing latest (1.5.11) with current master branch?

**Comment by Juweii** [comment]
Commit 191b331 works, looks like thats a problem of 7181abd (2 Apr).

**Comment by Apollon77** [comment]
When did you installed from GitHub? Please try very latest master.

In fact a great test case and I also had this problem but fixed in the meantime (i thought). I will check the code once you confirm it is really "github latest" ;-)
The 2.0.0 is changing the communication protocol completely but I addad a fallback ... but it seems that this makes problems in your case :-(
Also it would be a great idea for "compact only on one hast" ... never thought about that oportunity :-)

**Comment by Juweii** [comment]
I used the very latest master when i wrote my issue :)
Also tried some older ones without success until i found the root cause commit which changed the behavior you described.

**Comment by Apollon77** [comment]
Congrats ... you found a place that I did not considered for the fallback handling changes :-)

Please try

npm i --prefix /opt/iobroker/ --save --production --unsafe-perm https://github.com/ioBroker/ioBroker.js-controller#slave-redis-fix

Works with this?

**Comment by Juweii** [comment]
Hello @Apollon77,

thank you for the quick fix, now i get another error:
```
2019-05-29 06:32:01.656  - ^[[31merror^[[39m: host.CaraNET uncaught exception: Cannot read property 'getObjects' of null
2019-05-29 06:32:01.666  - ^[[31merror^[[39m: host.CaraNET TypeError: Cannot read property 'getObjects' of null
    at states.getKeys (/opt/iobroker/node_modules/iobroker.js-controller/main.js:2935:25)
    at client.keys (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:441:17)
    at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-05-29 06:32:01.694  - ^[[32minfo^[[39m: host.CaraNET iobroker _restart
2019-05-29 06:32:01.755  - ^[[32minfo^[[39m: host.CaraNET terminated
```

**Comment by Apollon77** [comment]
Yes ... found it ... branch updated for next test when you have time (sunday or after is completely ok).

Your feedback is very important because we were not able to test the new stuff that deep, so it is great progress! Thank you very much

**Comment by Apollon77** [comment]
Please not install from branch ... use master instead ... changes are incorporated already

**Comment by Juweii** [comment]
```
2019-06-03 12:23:53.274  - info: Objects using TCP/Redis protocol not available, falling back to socket.io protocol
2019-06-03 12:23:53.986  - info: host.CaraNET {"type":"file","server":false} connected
2019-06-03 12:23:54.328  - error: host.CaraNET uncaught exception: Cannot read property 'setState' of null
```

**Comment by Juweii** [comment]
Ah, nvm... It's working after the second start.

**Comment by Apollon77** [comment]
Do you have a stack trace (more error lines) to the error above?

Can you maybe check some more starts if the error happens again?

**Comment by Juweii** [comment]
I don't have a stack trace, that was the only message.
However, seems to work even after some more restarts. Thank you again for your work!

**Comment by Apollon77** [comment]
Thank you for testing.

**Comment by Juweii** [comment]
Hmm, same issue after reboot:
```
2019-06-06 18:32:11.895  - info: Objects using TCP/Redis protocol not available, falling back to socket.io protocol
2019-06-06 18:32:12.622  - info: host.CaraNET {"type":"file","server":false} connected
2019-06-06 18:32:13.017  - error: host.CaraNET uncaught exception: Cannot read property 'setState' of null
```
No more info, no stack trace. 
Seems thats happening only sporadic times, not on every start. Means I can restart several times without any issue and on the other day there's the error again.

**Comment by Apollon77** [comment]
Hm ... can you set logging from controller to debug please? You can do that in iobroker-data/iobroker.json

Maybe we get more insight then.

**Comment by Apollon77** [comment]
Ps: is the controller crashing in this case or is it only logging that but still works?

**Comment by Juweii** [comment]
It's crashing

**Comment by Apollon77** [comment]
I have enhanced logging so that stack trace is now printed in this case too ... please install newest master again and then we should see more about the reason.
As info: I'm available today and then on vacation for roughly 2 weeks ... so depending on how fast you experience it again fix could take some days ...

**Comment by Juweii** [comment]
OK, I updated the controller and restarted 3 times, it did not happen to crash. I will keep an eye on it. It's not that important to disturb you in your holidays, so have a nice time!

**Comment by Apollon77** [comment]
Please update this issue with any findings, I will take care of them after my vacation or someone else takes it ... we will see.
It is important to have exactly those reality tests with teh 2.0.0 :-)

**Comment by Juweii** [comment]
Hello @Apollon77 ,
sorry for the late response, but the issue seems to be solved.
I have another problem where i need to reboot my router (the one with the slave) frequently by watchdog and that way the issue would have been visible already. But it wasnt the last weeks, so thanks again for your work!

**Comment by Apollon77** [comment]
Thank you for the update
