### ISSUE TITLE
[2.0.0] Exception "Cannot read property 'setState' of null" at start time

### ISSUE THREAD

**Issue by Stabilostick** [ioBroker/ioBroker.js-controller#395]
Habe mit der aktuellen js-controller 2.0.0-Version das folgende Start-Problem (direkt nach der Installation):

```
2019-06-21 23:43:45.014  - [32minfo[39m: host.ARBEITSZIMMER iobroker.js-controller version 2.0.0 js-controller starting
2019-06-21 23:43:45.021  - [32minfo[39m: host.ARBEITSZIMMER Copyright (c) 2014-2019 bluefox, 2014 hobbyquaker
2019-06-21 23:43:45.021  - [32minfo[39m: host.ARBEITSZIMMER hostname: ARBEITSZIMMER, node: v10.16.0
2019-06-21 23:43:45.028  - [32minfo[39m: host.ARBEITSZIMMER ip addresses: fe80::10b3:228f:5b23:fa97 192.168.179.64 fe80::386a:874c:3959:9b57 169.254.155.87
2019-06-21 23:43:45.096  - [34mdebug[39m: host.ARBEITSZIMMER  Redis inMem-objects listening on port 9001
2019-06-21 23:43:45.105  - [32minfo[39m: host.ARBEITSZIMMER {"type":"file","server":true} connected
2019-06-21 23:43:45.117  - [32minfo[39m: host.ARBEITSZIMMER 3 instances found
2019-06-21 23:43:45.117  - [34mdebug[39m: host.ARBEITSZIMMER check instance "system.adapter.admin.0" for host "ARBEITSZIMMER"
2019-06-21 23:43:45.119  - [34mdebug[39m: host.ARBEITSZIMMER check instance "system.adapter.discovery.0" for host "ARBEITSZIMMER"
2019-06-21 23:43:45.120  - [34mdebug[39m: host.ARBEITSZIMMER check instance "system.adapter.info.0" for host "ARBEITSZIMMER"
2019-06-21 23:43:45.121  - [32minfo[39m: host.ARBEITSZIMMER starting 3 instances
2019-06-21 23:43:45.126  - [34mdebug[39m: host.ARBEITSZIMMER  Redis inMem-states listening on port 9000
2019-06-21 23:43:45.139  - [34mdebug[39m: host.ARBEITSZIMMER startInstance admin.0 loglevel=info
2019-06-21 23:43:45.155  - [31merror[39m: host.ARBEITSZIMMER uncaught exception: Cannot read property 'setState' of null
2019-06-21 23:43:45.156  - [31merror[39m: host.ARBEITSZIMMER TypeError: Cannot read property 'setState' of null
    at startInstance (C:\Program Files\iobroker\SmartHome76\node_modules\iobroker.js-controller\main.js:2449:28)
    at Timeout.procs.(anonymous function).restartTimer._id (C:\Program Files\iobroker\SmartHome76\node_modules\iobroker.js-controller\main.js:1923:64)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2019-06-21 23:43:45.157  - [34mdebug[39m: host.ARBEITSZIMMER stop isStopping=0 isDaemon=false allInstancesStopped=false
2019-06-21 23:43:45.160  - [32minfo[39m: host.ARBEITSZIMMER iobroker _restart
2019-06-21 23:43:45.180  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.host.ARBEITSZIMMER.alive {"val":true,"ack":true,"ts":1561153425180,"q":0,"from":"system.host.ARBEITSZIMMER","lc":1561153425180}
2019-06-21 23:43:45.196  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.host.ARBEITSZIMMER.memRss {"val":44.43,"ack":true,"ts":1561153425196,"q":0,"from":"system.host.ARBEITSZIMMER","lc":1561153425196}
2019-06-21 23:43:45.197  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.host.ARBEITSZIMMER.memHeapTotal {"val":30.05,"ack":true,"ts":1561153425197,"q":0,"from":"system.host.ARBEITSZIMMER","lc":1561152338130}
2019-06-21 23:43:45.197  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.host.ARBEITSZIMMER.memHeapUsed {"val":19.96,"ack":true,"ts":1561153425197,"q":0,"from":"system.host.ARBEITSZIMMER","lc":1561153425197}
2019-06-21 23:43:45.200  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.host.ARBEITSZIMMER.load {"val":2.25,"ack":true,"ts":1561153425200,"q":0,"from":"system.host.ARBEITSZIMMER","lc":1561153425200}
2019-06-21 23:43:45.200  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.host.ARBEITSZIMMER.uptime {"val":1,"ack":true,"ts":1561153425200,"q":0,"from":"system.host.ARBEITSZIMMER","lc":1561152305940}
2019-06-21 23:43:45.200  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.host.ARBEITSZIMMER.mem {"val":30.1,"ack":true,"ts":1561153425200,"q":0,"from":"system.host.ARBEITSZIMMER","lc":1561153425200}
2019-06-21 23:43:45.201  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.host.ARBEITSZIMMER.freemem {"val":4920,"ack":true,"ts":1561153425201,"q":0,"from":"system.host.ARBEITSZIMMER","lc":1561153425201}
2019-06-21 23:43:45.215  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.host.ARBEITSZIMMER.inputCount {"val":0,"ack":true,"ts":1561153425215,"q":0,"from":"system.host.ARBEITSZIMMER","lc":1561152305958}
2019-06-21 23:43:45.215  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.host.ARBEITSZIMMER.outputCount {"val":10,"ack":true,"ts":1561153425215,"q":0,"from":"system.host.ARBEITSZIMMER","lc":1561152305959}
2019-06-21 23:43:45.525  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.host.ARBEITSZIMMER.diskSize {"val":487579,"ack":true,"ts":1561153425525,"q":0,"from":"system.host.ARBEITSZIMMER","lc":1561152306268}
2019-06-21 23:43:45.526  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.host.ARBEITSZIMMER.diskFree {"val":101191,"ack":true,"ts":1561153425526,"q":0,"from":"system.host.ARBEITSZIMMER","lc":1561153425526}
2019-06-21 23:43:45.993  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.host.ARBEITSZIMMER.cpu {"val":"0.00","ack":true,"ts":1561153425993,"q":0,"from":"system.host.ARBEITSZIMMER","lc":1561152306758}
2019-06-21 23:43:45.994  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.host.ARBEITSZIMMER.cputime {"val":1.015,"ack":true,"ts":1561153425994,"q":0,"from":"system.host.ARBEITSZIMMER","lc":1561153425994}
2019-06-21 23:43:46.564  - [32minfo[39m: host.ARBEITSZIMMER iobroker Starting node restart.js
2019-06-21 23:43:47.578  - [32minfo[39m: starting. Version 3.6.2 in C:/Program Files/iobroker/SmartHome76/node_modules/iobroker.admin, node: v10.16.0
2019-06-21 23:43:47.592  - [32minfo[39m: host.ARBEITSZIMMER iobroker exit 0
2019-06-21 23:43:47.603  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.adapter.admin.0.alive {"val":true,"ack":true,"ts":1561153427602,"q":0,"from":"system.adapter.admin.0","lc":1561153427602}
2019-06-21 23:43:47.609  - [32minfo[39m: admin.0 requesting all states
2019-06-21 23:43:47.608  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.adapter.admin.0.connected {"val":true,"ack":true,"ts":1561153427603,"q":0,"from":"system.adapter.admin.0","lc":1561153427603}
2019-06-21 23:43:47.609  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.adapter.admin.0.memRss {"val":48.68,"ack":true,"ts":1561153427603,"q":0,"from":"system.adapter.admin.0","lc":1561153427603}
2019-06-21 23:43:47.610  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.adapter.admin.0.memHeapTotal {"val":34.75,"ack":true,"ts":1561153427604,"q":0,"from":"system.adapter.admin.0","lc":1561153427604}
2019-06-21 23:43:47.610  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.adapter.admin.0.memHeapUsed {"val":20.65,"ack":true,"ts":1561153427604,"q":0,"from":"system.adapter.admin.0","lc":1561153427604}
2019-06-21 23:43:47.611  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.adapter.admin.0.uptime {"val":2,"ack":true,"ts":1561153427604,"q":0,"from":"system.adapter.admin.0","lc":1561152308073}
2019-06-21 23:43:47.611  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.adapter.admin.0.inputCount {"val":0,"ack":true,"ts":1561153427605,"q":0,"from":"system.adapter.admin.0","lc":1561152308073}
2019-06-21 23:43:47.611  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.adapter.admin.0.outputCount {"val":8,"ack":true,"ts":1561153427605,"q":0,"from":"system.adapter.admin.0","lc":1561152308073}
2019-06-21 23:43:47.611  - [32minfo[39m: admin.0 requesting all objects
2019-06-21 23:43:47.613  - [32minfo[39m: admin.0 Request actual repository...
2019-06-21 23:43:47.758  - [32minfo[39m: host.ARBEITSZIMMER Update repository "default" under "http://download.iobroker.net/sources-dist.json"
2019-06-21 23:43:47.824  - [32minfo[39m: admin.0 received all objects
2019-06-21 23:43:47.891  - [32minfo[39m: admin.0 received all states
2019-06-21 23:43:47.915  - [32minfo[39m: admin.0 http server listening on port 8081
2019-06-21 23:43:47.915  - [32minfo[39m: admin.0 Use link "http://localhost:8081" to configure.
2019-06-21 23:43:48.300  - [35msilly[39m: host.ARBEITSZIMMER memory publish admin.0.info.updatesNumber {"val":0,"ack":true,"ts":1561153428300,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1561152308527}
2019-06-21 23:43:48.301  - [35msilly[39m: host.ARBEITSZIMMER memory publish admin.0.info.updatesList {"val":"","ack":true,"ts":1561153428300,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1561152308528}
2019-06-21 23:43:48.301  - [35msilly[39m: host.ARBEITSZIMMER memory publish admin.0.info.newUpdates {"val":false,"ack":true,"ts":1561153428301,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1561152308528}
2019-06-21 23:43:48.301  - [35msilly[39m: host.ARBEITSZIMMER memory publish admin.0.info.updatesJson {"val":"{}","ack":true,"ts":1561153428301,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1561152308529}
2019-06-21 23:43:48.302  - [35msilly[39m: host.ARBEITSZIMMER memory publish admin.0.info.lastUpdateCheck {"val":"2019-06-21T23:43:48.299Z","ack":true,"ts":1561153428302,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1561153428302}
2019-06-21 23:43:48.318  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.adapter.admin.0.cpu {"val":"0.00","ack":true,"ts":1561153428318,"q":0,"from":"system.adapter.admin.0","lc":1561152308645}
2019-06-21 23:43:48.319  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.adapter.admin.0.cputime {"val":2.907,"ack":true,"ts":1561153428318,"q":0,"from":"system.adapter.admin.0","lc":1561153428318}
2019-06-21 23:43:48.434  - [35msilly[39m: Redis Publish State messagebox.system.adapter.admin.0={"command":"getRepository","message":{"admin":{"meta":"https://raw.githubusercontent.com/ioBroker/ioBroker.admin/master/io-package.json","icon":"https://raw.githubusercontent.com/ioBroker/ioBroker.admin/master/admin/admin.png","type":"general","published":"2014-12-04T18:45:44.907Z","versionDate":"2019-05-05T21:40:16.000Z","stars":186,"issues":84,"score":130.57018,"name":"admin","title":"Admin","version":"3.6.2","news":{"3.6.4":{"en":"Update nodejs recommendation message and check to recommend nodejs 

[...]

/zwave.png","compact":true,"onlyWWW":false,"singletonHost":true,"messagebox":true,"enabled":true,"config":{"minWidth":800,"width":1224,"height":600}}},"hash":"7abb69fd04523f87c13918339b050058"},"latest":{"link":"http://download.iobroker.net/sources-dist-latest.json","json":null}},"oldRepositories":{"sources":{"link":"conf/sources-dist.json","json":null},"online":{"link":"https://raw.githubusercontent.com/ioBroker/ioBroker.repositories/master/sources-dist.json","json":null}}},"acl":{"owner":"system.user.admin","ownerGroup":"system.group.administrator","object":1604},"from":"system.host.ARBEITSZIMMER","ts":1561153428492}
2019-06-21 23:43:48.722  - [35msilly[39m: host.ARBEITSZIMMER memory publish admin.0.info.updatesNumber {"val":0,"ack":true,"ts":1561153428722,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1561152308527}
2019-06-21 23:43:48.723  - [35msilly[39m: host.ARBEITSZIMMER memory publish admin.0.info.updatesList {"val":"","ack":true,"ts":1561153428722,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1561152308528}
2019-06-21 23:43:48.723  - [35msilly[39m: host.ARBEITSZIMMER memory publish admin.0.info.newUpdates {"val":false,"ack":true,"ts":1561153428723,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1561152308528}
2019-06-21 23:43:48.724  - [35msilly[39m: host.ARBEITSZIMMER memory publish admin.0.info.updatesJson {"val":"{}","ack":true,"ts":1561153428723,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1561152308529}
2019-06-21 23:43:48.724  - [35msilly[39m: host.ARBEITSZIMMER memory publish admin.0.info.lastUpdateCheck {"val":"2019-06-21T23:43:48.722Z","ack":true,"ts":1561153428723,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1561153428723}
2019-06-21 23:43:48.933  - [35msilly[39m: host.ARBEITSZIMMER memory publish admin.0.connected {"val":"[0]","ack":true,"ts":1561153428933,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1561153428933}
2019-06-21 23:43:50.383  - [35msilly[39m: host.ARBEITSZIMMER memory publish admin.0.connected {"val":"[1]noname","ack":true,"ts":1561153430383,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1561153430383}
2019-06-21 23:43:55.204  - [35msilly[39m: Objects 127.0.0.1:53673 Redis connection close
2019-06-21 23:43:55.205  - [35msilly[39m: Objects 127.0.0.1:53674 Redis connection close
2019-06-21 23:43:55.205  - [35msilly[39m: host.ARBEITSZIMMER memory publish system.host.ARBEITSZIMMER.alive {"val":false,"ack":true,"ts":1561153435205,"q":0,"from":"system.host.ARBEITSZIMMER","lc":1561153435205}
2019-06-21 23:43:55.205  - [35msilly[39m: Redis Publish State system.host.ARBEITSZIMMER.alive={"val":false,"ack":true,"ts":1561153435205,"q":0,"from":"system.host.ARBEITSZIMMER","lc":1561153435205}
2019-06-21 23:43:55.206  - [32minfo[39m: host.ARBEITSZIMMER force terminating
2019-06-21 23:43:55.206  - [32minfo[39m: host.ARBEITSZIMMER Adapter admin still running
2019-06-21 23:43:55.207  - [35msilly[39m: Redis Publish State system.host.ARBEITSZIMMER.alive={"val":null,"ack":true,"ts":1561153435207,"q":0,"from":"system.host.ARBEITSZIMMER","lc":1561153435205}
2019-06-21 23:43:55.222  - [35msilly[39m: States 127.0.0.1:53675 Redis connection close
2019-06-21 23:43:55.223  - [35msilly[39m: States 127.0.0.1:53676 Redis connection close
```

OS: Windows

Die Installation habe ich so durchgeführt:

1. npm i iobroker
1. npm i
1. Verzeichnisse 'iobroker-data' und 'node_modules/iobroker.js-controller' gelöscht
1. npm install https://github.com/iobroker/iobroker.js-controller/tarball/master --production

Installation verlief ohne relevante Fehler.

**Comment by Apollon77** [comment]
problem is main.js#L359 basically together with the timing issue that states DB is not connected early enough (why ever).
@GermanBluefox @AlCalzone 
So basically we should refactor the logic so that this part of the code is only executed once objects and states db are both connected.I will prepare a PR
