### ISSUE TITLE
Keylength of defaultPublic certificate is too small

### ISSUE THREAD

**Issue by Stabilostick** [ioBroker/ioBroker.js-controller#399]
Keylength of default certificate is 1024bits. This generates problems with default security settings in newer node.js versions (10-12):

```
2019-07-07 17:00:45.619  - error: admin.0 uncaught exception: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
2019-07-07 17:00:45.619  - error: admin.0 Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
    at Object.createSecureContext (_tls_common.js:135:17)
    at Server (_tls_wrap.js:870:27)
    at new Server (https.js:62:14)
    at Object.createServer (https.js:85:10)
    at Object.createServer (/opt/iobroker/node_modules/iobroker.js-controller/lib/letsencrypt.js:174:39)
    at __construct (/opt/iobroker/node_modules/iobroker.admin/lib/web.js:446:32)
    at new Web (/opt/iobroker/node_modules/iobroker.admin/lib/web.js:477:7)
    at getData (/opt/iobroker/node_modules/iobroker.admin/main.js:388:39)
    at Socket.adapter.objects.getObjectList (/opt/iobroker/node_modules/iobroker.admin/main.js:441:35)
    at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
2019-07-07 17:00:45.620  - info: admin.0 terminating https server on port 8081
```

**Comment by Apollon77** [comment]
Fixed by 1.5.13
