### ISSUE TITLE
"user-files" in einem eigenen Ordner hochladen brings error

### ISSUE THREAD

**Issue by Pocky2507** [ioBroker/ioBroker.js-controller#455]
Ich habe meine Images im Ordner:
`/opt/iobroker/iobroker-data/files/Eigene Images`

Die Images sind seid dem js.contoller 2.0 nicht mehr sichtbar.
Es treten folgende Fehlermeldungen auf:

`host.rockpro64	2019-09-20 09:24:05.324	error	at Object.checkFileRights (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsUtils.js:226:17)
host.rockpro64	2019-09-20 09:24:05.324	error	at ObjectsInMemoryServer.getUserGroup (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:201:22)
host.rockpro64	2019-09-20 09:24:05.324	error	at Object.getUserGroup (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsUtils.js:333:25)
host.rockpro64	2019-09-20 09:24:05.324	error	at ObjectsInMemoryServer.utils.getUserGroup (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:203:22)
host.rockpro64	2019-09-20 09:24:05.324	error	at ObjectsInMemoryServer.objects.getUserGroup (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsUtils.js:230:13)
host.rockpro64	2019-09-20 09:24:05.324	error	at checkFileRights (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsUtils.js:244:13)
host.rockpro64	2019-09-20 09:24:05.324	error	at ObjectsInMemoryServer.checkFile (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:158:32)
host.rockpro64	2019-09-20 09:24:05.324	error	at objects.checkFile (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsUtils.js:248:20)
host.rockpro64	2019-09-20 09:24:05.324	error	at checkFileRights (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:683:33)
host.rockpro64	2019-09-20 09:24:05.324	error	at ObjectsInMemoryServer._readDir (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:584:50)
host.rockpro64	2019-09-20 09:24:05.324	error	TypeError: Cannot read property 'Eigene Images' of undefined
host.rockpro64	2019-09-20 09:24:05.321	error	uncaught exception: Cannot read property 'Eigene Images' of undefined`

Hier scheint aber noch etwas im argen zu sein.
Sobald ich in einem Widget ein Image Pfad änder will stürzt iobroker ab.

`2019-09-20 13:21:28.136  - [31merror[39m: host.rockpro64 uncaught exception: Cannot read property 'admin.admin' of undefined
2019-09-20 13:21:28.138  - [31merror[39m: host.rockpro64 TypeError: Cannot read property 'admin.admin' of undefined
    at ObjectsInMemoryServer._readDir (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:584:50)
    at checkFileRights (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:683:33)
    at objects.checkFile (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsUtils.js:248:20)
    at ObjectsInMemoryServer.checkFile (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:158:32)
    at checkFileRights (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsUtils.js:244:13)
    at ObjectsInMemoryServer.objects.getUserGroup (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsUtils.js:230:13)
    at ObjectsInMemoryServer.utils.getUserGroup (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:203:22)
    at Object.getUserGroup (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsUtils.js:333:25)
    at ObjectsInMemoryServer.getUserGroup (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:201:22)
    at Object.checkFileRights (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsUtils.js:226:17)
2019-09-20 13:21:28.140  - [32minfo[39m: host.rockpro64 iobroker _restart`

**Comment by Apollon77** [comment]
will be fixed in 2.0.5
