### ISSUE TITLE
[2.0.0] process will crash if alias set a invalid value

### ISSUE THREAD

**Issue by SchumyHao** [ioBroker/ioBroker.js-controller#456]
In https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/tools.js#L1604
It seems logger is not defined before.
So if I write an invalid alias function, crash comes up

**Comment by Apollon77** [comment]
Can you please provide the full log and error stack trace?

**Comment by SchumyHao** [comment]
```
2019-09-20 22:42:30.039  - error: admin.0 (1271) uncaught exception: logger is not defined
2019-09-20 22:42:30.041  - error: admin.0 (1271) ReferenceError: logger is not defined
    at Object.formatAliasValue (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1614:13)
    at objects.getObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5014:81)
    at (anonymous function).(anonymous function) (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:59081)
    at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-09-20 22:42:30.044  - info: admin.0 (1271) terminating http server on port 8081
2019-09-20 22:42:30.054  - info: admin.0 (1271) terminating
2019-09-20 22:42:30.197  - error: host.dockerhub-cn Caught by controller[0]: ReferenceError: logger is not defined
2019-09-20 22:42:30.198  - error: host.dockerhub-cn Caught by controller[0]:     at Object.formatAliasValue (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1614:13)
2019-09-20 22:42:30.199  - error: host.dockerhub-cn Caught by controller[0]:     at objects.getObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5014:81)
2019-09-20 22:42:30.199  - error: host.dockerhub-cn Caught by controller[0]:     at (anonymous function).(anonymous function) (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:59081)
2019-09-20 22:42:30.199  - error: host.dockerhub-cn Caught by controller[0]:     at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
2019-09-20 22:42:30.200  - error: host.dockerhub-cn Caught by controller[0]:     at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
2019-09-20 22:42:30.200  - error: host.dockerhub-cn Caught by controller[0]:     at process._tickCallback (internal/process/next_tick.js:68:7)
2019-09-20 22:42:30.200  - info: host.dockerhub-cn instance system.adapter.admin.0 terminated with code 0 (NO_ERROR)
2019-09-20 22:42:30.201  - info: host.dockerhub-cn Restart adapter system.adapter.admin.0 because enabled
```

**Comment by Apollon77** [comment]
I will take care in 2.0.5 later tonight
