### ISSUE TITLE
[2.0.9] Crash during `compact enable`

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#471]
```
$ iobroker compact web.0 enable 2
Compact mode supported: false
Compact mode enabled:   false --> true
Compact group:          1 --> 2
Instance settings for "web.0" are changed.
(node:2199) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:115:25)
    at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:82:20)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:561:12)
(node:2199) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2199) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I had previously enabled compact mode for admin (group 2). When I enabled compact for web afterwards (also group 2), this happened

**Comment by AlCalzone** [comment]
Now its stuck:
```
pi@Heizung:/opt/iobroker $ iobroker list instances
+ system.adapter.admin.0                 : admin                 -  enabled, compact enabled (group 2), port: 8081, bind: 0.0.0.0 (SSL), ru                                                                                                  n as: admin
+ system.adapter.alexa2.0                : alexa2                -  enabled, compact enabled (group 1)
+ system.adapter.ble.0                   : ble                   -  enabled, compact disabled
  system.adapter.connect.0               : connect               - disabled, compact disabled
  system.adapter.connect_ui.0            : connect_ui            - disabled, compact disabled
  system.adapter.flot.0                  : flot                  -  enabled, compact disabled
+ system.adapter.g-homa.0                : g-homa                -  enabled, compact disabled
  system.adapter.history.0               : history               - disabled, compact disabled
+ system.adapter.iot.0                   : iot                   -  enabled, compact enabled (group 1)
  system.adapter.iqontrol.0              : iqontrol              - disabled, compact disabled
+ system.adapter.javascript.0            : javascript            -  enabled, compact disabled
  system.adapter.javascript.1            : javascript            - disabled, compact disabled
+ system.adapter.mihome-vacuum.0         : mihome-vacuum         -  enabled, compact disabled, port: 54321
  system.adapter.philips-tv.0            : philips-tv            - disabled, compact disabled
+ system.adapter.scenes.0                : scenes                -  enabled, compact disabled
+ system.adapter.simple-api.0            : simple-api            -  enabled, compact disabled, port: 8087, bind: 0.0.0.0, run as: admin
  system.adapter.socketio.0              : socketio              - disabled, compact disabled, port: 8088, bind: 0.0.0.0, run as: admin
  system.adapter.terminal.0              : terminal              - disabled, compact disabled, port: 8090, bind: 0.0.0.0, run as: admin
  system.adapter.text2command.0          : text2command          - disabled, compact disabled
+ system.adapter.tradfri.0               : tradfri               -  enabled, compact disabled
  system.adapter.vw-carnet.0             : vw-carnet             - disabled, compact disabled
+ system.adapter.web.0                   : web                   -  enabled, compact disabled, port: 8082, bind: 0.0.0.0, run as: admin
+ system.adapter.yahka.0                 : yahka                 -  enabled, compact disabled
+ system.adapter.zwave.0                 : zwave                 -  enabled, compact disabled
  system.adapter.zwave2.0                : zwave2                - disabled, compact disabled

+ instance is alive
pi@Heizung:/opt/iobroker $ iobroker compact web.0 enable 2
Compact mode supported: false
Compact mode enabled:   true
Compact group:          2
No settings changed.
pi@Heizung:/opt/iobroker $ iobroker list instances
+ system.adapter.admin.0                 : admin                 -  enabled, compact enabled (group 2), port: 8081, bind: 0.0.0.0 (SSL), ru                                                                                                  n as: admin
+ system.adapter.alexa2.0                : alexa2                -  enabled, compact enabled (group 1)
+ system.adapter.ble.0                   : ble                   -  enabled, compact disabled
  system.adapter.connect.0               : connect               - disabled, compact disabled
  system.adapter.connect_ui.0            : connect_ui            - disabled, compact disabled
  system.adapter.flot.0                  : flot                  -  enabled, compact disabled
+ system.adapter.g-homa.0                : g-homa                -  enabled, compact disabled
  system.adapter.history.0               : history               - disabled, compact disabled
+ system.adapter.iot.0                   : iot                   -  enabled, compact enabled (group 1)
  system.adapter.iqontrol.0              : iqontrol              - disabled, compact disabled
+ system.adapter.javascript.0            : javascript            -  enabled, compact disabled
  system.adapter.javascript.1            : javascript            - disabled, compact disabled
+ system.adapter.mihome-vacuum.0         : mihome-vacuum         -  enabled, compact disabled, port: 54321
  system.adapter.philips-tv.0            : philips-tv            - disabled, compact disabled
+ system.adapter.scenes.0                : scenes                -  enabled, compact disabled
+ system.adapter.simple-api.0            : simple-api            -  enabled, compact disabled, port: 8087, bind: 0.0.0.0, run as: admin
  system.adapter.socketio.0              : socketio              - disabled, compact disabled, port: 8088, bind: 0.0.0.0, run as: admin
  system.adapter.terminal.0              : terminal              - disabled, compact disabled, port: 8090, bind: 0.0.0.0, run as: admin
  system.adapter.text2command.0          : text2command          - disabled, compact disabled
+ system.adapter.tradfri.0               : tradfri               -  enabled, compact disabled
  system.adapter.vw-carnet.0             : vw-carnet             - disabled, compact disabled
+ system.adapter.web.0                   : web                   -  enabled, compact disabled, port: 8082, bind: 0.0.0.0, run as: admin
+ system.adapter.yahka.0                 : yahka                 -  enabled, compact disabled
+ system.adapter.zwave.0                 : zwave                 -  enabled, compact disabled
  system.adapter.zwave2.0                : zwave2                - disabled, compact disabled

+ instance is alive
```

**Comment by Apollon77** [comment]
your web version is not supporting compact mode ... so you can not enable it. I need to check and fix that,

**Comment by Apollon77** [comment]
Changes:
I remove the "Compact mode supported: false" case and add 
```
This adapter does not support compact mode. The below settings will have no effect!
```

to make it more clear. The "connection closed issue will be handled with an other issue (duplicate)

**Comment by AlCalzone** [comment]
Web is up to date and now running in the same group as admin. I had to disable and re-enable compact for web.0 in order for the change to be picked up.
