### ISSUE TITLE
[2.0.9] CLI commands crash frequently

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#472]
This was after I upgraded iot.0:
```
2019-09-24 19:45:34.175 - error: host.Heizung iobroker (node:2345) 
UnhandledPromiseRejectionWarning: Error: Connection is closed. 
at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:115:25) 
at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:82:20) at Object.onceWrapper (events.js:315:30) at emitOne (events.js:116:13) 
at Socket.emit (events.js:211:7) 
at TCP._handle.close [as _onclose] (net.js:561:12)(node:2345) 

UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2345) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by AlCalzone** [comment]
And again after iqontrol

**Comment by AlCalzone** [comment]
Aaaand again:
```
2019-09-24 19:58:21.157  - info: host.Heizung.compactgroup2 terminated
2019-09-24 19:58:22.182  - error: host.Heizung Caught by controller[0]: (node:2586) UnhandledPromiseRejectionWarning: Error: Connection is closed.
2019-09-24 19:58:22.183  - error: host.Heizung Caught by controller[0]:     at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:115:25)
2019-09-24 19:58:22.184  - error: host.Heizung Caught by controller[0]:     at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:82:20)
2019-09-24 19:58:22.185  - error: host.Heizung Caught by controller[0]:     at Object.onceWrapper (events.js:315:30)
2019-09-24 19:58:22.185  - error: host.Heizung Caught by controller[0]:     at emitOne (events.js:116:13)
2019-09-24 19:58:22.186  - error: host.Heizung Caught by controller[0]:     at Socket.emit (events.js:211:7)
2019-09-24 19:58:22.186  - error: host.Heizung Caught by controller[0]:     at TCP._handle.close [as _onclose] (net.js:561:12)
2019-09-24 19:58:22.187  - error: host.Heizung Caught by controller[1]: (node:2586) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2019-09-24 19:58:22.187  - error: host.Heizung Caught by controller[1]: (node:2586) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-09-24 19:58:22.188  - error: host.Heizung Caught by controller[1]: (node:2586) UnhandledPromiseRejectionWarning: Error: Connection is closed.
2019-09-24 19:58:22.189  - error: host.Heizung Caught by controller[1]:     at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:115:25)
2019-09-24 19:58:22.189  - error: host.Heizung Caught by controller[1]:     at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:82:20)
2019-09-24 19:58:22.190  - error: host.Heizung Caught by controller[1]:     at Object.onceWrapper (events.js:315:30)
2019-09-24 19:58:22.190  - error: host.Heizung Caught by controller[1]:     at emitOne (events.js:116:13)
2019-09-24 19:58:22.191  - error: host.Heizung Caught by controller[1]:     at Socket.emit (events.js:211:7)
2019-09-24 19:58:22.191  - error: host.Heizung Caught by controller[1]:     at TCP._handle.close [as _onclose] (net.js:561:12)
2019-09-24 19:58:22.192  - error: host.Heizung Caught by controller[1]: (node:2586) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
2019-09-24 19:58:22.192  - info: host.Heizung Restart compact group controller 2
2019-09-24 19:58:22.193  - info: ["system.adapter.admin.0"]
2
```

**Comment by Apollon77** [comment]
maybe my latest changes on how connections are handled had an effect here. WIll check and fix that

**Comment by Apollon77** [comment]
One question: Do the cli commands crash or do they crash a running host? Seems like second one?

**Comment by Apollon77** [comment]
I opened https://github.com/luin/ioredis/issues/971

**Comment by AlCalzone** [comment]
Only the cli command crashes. The host runs fine
