### ISSUE TITLE
vis install error

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.js-controller#475]
TypeError: Cannot read property 'common' of null    at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1005:26)    at getForeignObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1257:33)    at objects.getObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2350:65)    at (anonymous function).(anonymous function) (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:59685)    at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)    at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)    at process._tickCallback (internal/process/next_tick.js:68:7)
npm

**Comment by Apollon77** [comment]
in node main.js --install
