### ISSUE TITLE
Catch .setobjectnotexists when combact instance is already closed

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.js-controller#517]
Http request returns a promise. Combact instance is terminated. Promise is resolve and Adapter is trying to .setobjectnotExists returns error and leads to restart of the compact group.
`
2019-10-28 09:46:50.500 - error: host.Caught by controller[6]: TypeError: Cannot read property 'getObject' of null
2019-10-28 09:46:50.500 - error: host.Caught by controller[6]: at Mercedesme.setObjectNotExists (/usr/local/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2581:26)
2019-10-28 09:46:50.500 - error: host.Caught by controller[6]: at vinArray.forEach.element (/usr/local/iobroker/node_modules/iobroker.mercedesme/main.js:955:11)
2019-10-28 09:46:50.500 - error: host.Caught by controller[6]: at Array.forEach ()
2019-10-28 09:46:50.500 - error: host.Caught by controller[6]: at Request.request.get [as _callback] (/usr/local/iobroker/node_modules/iobroker.mercedesme/main.js:954:19)
2019-10-28 09:46:50.500 - error: host.Caught by controller[6]: at Request.self.callback (/usr/local/iobroker/node_modules/request/request.js:185:22)
2019-10-28 09:46:50.500 - error: host.Caught by controller[6]: at Request.emit (events.js:198:13)
2019-10-28 09:46:50.501 - error: host.Caught by controller[6]: at Request. (/usr/local/iobroker/node_modules/request/request.js:1161:10)
2019-10-28 09:46:50.501 - error: host.Caught by controller[6]: at Request.emit (events.js:198:13)
2019-10-28 09:46:50.501 - error: host.Caught by controller[6]: at IncomingMessage. (/usr/local/iobroker/node_modules/request/request.js:1083:12)
2019-10-28 09:46:50.501 - error: host.Caught by controller[6]: at Object.onceWrapper (events.js:286:20)
2019-10-28 09:46:50.501 - info: host.Restart compact group controller 1
2019-10-28 09:47:20.505 - info: host.start controller for compactgroup 1
2019-10-28 09:47:20.509 - info: host.instance system.adapter.admin.0 is handled by compact group controller pid 13159
2019-10-28 09:47:20.510 - info: host.instance system.adapter.history.0 is handled by compact group controller pid 13159
2019-10-28 09:47:20.510 - info: host.instance system.adapter.web.0 is handled by compact group controller pid 13159
2019-10-28 09:47:20.940 - info: host..compactgroup1 iobroker.js-controller version 2.0.35 js-controller starting

`

**Comment by Apollon77** [comment]
We need to check "still existance" of states and objects for all adapter methods before doing the call

**Comment by Apollon77** [comment]
But: we will officially reject the Promise in this case! So your code still needs to handle that this happens
