### ISSUE TITLE
upgrate self error

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.js-controller#668]
when upgrading from 2.2.7 to 2.2.8, and now when upgrading from 2.2.8 to 2.2.9, this error appears and is not updated:
```
npm install iobroker.js-controller@2.2.9 --unsafe-perm --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code EEXIST
npm ERR! path /opt/iobroker/node_modules/iobroker.js-controller/node_modules/.bin/semver
npm ERR! Refusing to delete /opt/iobroker/node_modules/iobroker.js-controller/node_modules/.bin/semver: is outside /opt/iobroker/node_modules/iobroker.js-controller/node_modules/semver and not a link
npm ERR! File exists: /opt/iobroker/node_modules/iobroker.js-controller/node_modules/.bin/semver
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2020-02-13T19_15_19_193Z-debug.log

```
after deleting the file, it is updated with another error (the version is raised):

```
root@iobroker:/opt/iobroker# iobroker upgrade self
Update js-controller from @2.2.8 to @2.2.9
NPM version: 6.13.7
npm install iobroker.js-controller@2.2.9 --unsafe-perm --loglevel error --prefix "/opt/iobroker" (System call)
../src/contextify.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ContextifyContext::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/contextify.cc:62:74: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         ContextifyContext* ctx = new ContextifyContext(info[0]->ToObject());
                                                                          ^
In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63:0,
                 from ../src/contextify.cc:1:
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/contextify.cc: In static member function ‘static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)’:
../src/contextify.cc:131:68: error: no matching function for call to ‘v8::Function::NewInstance()’
         Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                                    ^
In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63:0,
                 from ../src/contextify.cc:1:
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:3993:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:3993:44: note:   candidate expects 3 arguments, 0 provided
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:3996:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:3996:44: note:   candidate expects 1 argument, 0 provided
../src/contextify.cc:150:16: error: ‘class v8::ObjectTemplate’ has no member named ‘SetAccessCheckCallbacks’; did you mean ‘SetAccessCheckCallback’?
         otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
                ^~~~~~~~~~~~~~~~~~~~~~~
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyGetter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&)’:
../src/contextify.cc:176:52: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Object> data = info.Data()->ToObject();
                                                    ^
In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63:0,
                 from ../src/contextify.cc:1:
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/contextify.cc:182:80: error: no matching function for call to ‘v8::Object::GetRealNamedProperty(v8::Local<v8::String>&)’
         Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                                                ^
In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63:0,
                 from ../src/contextify.cc:1:
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:3562:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::Context>, v8::Local<v8::Name>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(
                                           ^~~~~~~~~~~~~~~~~~~~
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:3562:43: note:   candidate expects 2 arguments, 1 provided
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertySetter(v8::Local<v8::String>, v8::Local<v8::Value>, const Nan::PropertyCallbackInfo<v8::Value>&)’:
../src/contextify.cc:192:52: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Object> data = info.Data()->ToObject();
                                                    ^
In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63:0,
                 from ../src/contextify.cc:1:
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)’:
../src/contextify.cc:203:52: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Object> data = info.Data()->ToObject();
                                                    ^
In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63:0,
                 from ../src/contextify.cc:1:
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/contextify.cc:209:67: error: no matching function for call to ‘v8::Object::GetRealNamedProperty(v8::Local<v8::String>&)’
         if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                                                   ^
In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63:0,
                 from ../src/contextify.cc:1:
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:3562:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::Context>, v8::Local<v8::Name>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(
                                           ^~~~~~~~~~~~~~~~~~~~
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:3562:43: note:   candidate expects 2 arguments, 1 provided
../src/contextify.cc:210:71: error: no matching function for call to ‘v8::Object::GetRealNamedProperty(v8::Local<v8::String>&)’
             !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                                                       ^
In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63:0,
                 from ../src/contextify.cc:1:
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:3562:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::Context>, v8::Local<v8::Name>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(
                                           ^~~~~~~~~~~~~~~~~~~~
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:3562:43: note:   candidate expects 2 arguments, 1 provided
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyDeleter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Boolean>&)’:
../src/contextify.cc:218:52: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Object> data = info.Data()->ToObject();
                                                    ^
In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63:0,
                 from ../src/contextify.cc:1:
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyEnumerator(const Nan::PropertyCallbackInfo<v8::Array>&)’:
../src/contextify.cc:229:52: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Object> data = info.Data()->ToObject();
                                                    ^
In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63:0,
                 from ../src/contextify.cc:1:
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/contextify.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ContextifyScript::RunInContext(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/contextify.cc:319:62: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         if (!ContextifyContext::InstanceOf(info[0]->ToObject()))
                                                              ^
In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63:0,
                 from ../src/contextify.cc:1:
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/contextify.cc:322:95: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         ContextifyContext* ctx = Nan::ObjectWrap::Unwrap<ContextifyContext>(info[0]->ToObject());
                                                                                               ^
In file included from /home/iobroker/.cache/node-gyp/10.19.0/include/node/node.h:63:0,
                 from ../src/contextify.cc:1:
/home/iobroker/.cache/node-gyp/10.19.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 3.10.105
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/contextify
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok
Starting node restart.js

```

**Comment by Apollon77** [comment]
The first error case with existing file is strange. Could it be that you copied node-modules directly via normal copy commands? But you solved it correctly. This is an npm thing and nothing to do with controller. 

Second is ok but only seems in an optional dependency. Was update still successful?

**Comment by Anzic23** [comment]
the oddity is that I already deleted this and many other files when switching from 2.2.7 to 2.2.8. Why did he appear again? I did not copy it myself.
after removal it was updated normally, except for errors in the log. now version 2.2.9
I cleaned these folders when switching from 2.2.7 to 2.2.8:
```
/iobroker/node_modules/.bin
/iobroker/node_modules/iobroker.javascript/node_modules/.bin
/iobroker/node_modules/iobroker.javascript/node_modules/node-pre-gyp/node_modules/.bin
/iobroker/node_modules/iobroker.javascript/node_modules/node-abi/node_modules/.bin/
```

**Comment by Apollon77** [comment]
Normally npm places symlinks to binary files from the sub modules in there and as long as it stays a symlink normally anything ok ok ... so I only saw that error in cases where those symlinks were converted to real files - one way is to copy the folder with wrong options.
So it is completely a Npm thing
