### ISSUE TITLE
Error: Cannot read property 'startsWith' of null

### ISSUE THREAD

**Issue by Zefau** [ioBroker/ioBroker.js-controller#700]
```
web.0 | 2020-02-29 21:18:41.822 | error | at process._tickCallback (internal/process/next_tick.js:61:11)
web.0 | 2020-02-29 21:18:41.822 | error | at /opt/iobroker/node_modules/socket.io/lib/socket.js:528:12
web.0 | 2020-02-29 21:18:41.822 | error | at Socket.emit (events.js:198:13)
web.0 | 2020-02-29 21:18:41.822 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.socketio/lib/socket.js:1122:30)
web.0 | 2020-02-29 21:18:41.822 | error | at Adapter.getForeignState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5666:24)
web.0 | 2020-02-29 21:18:41.822 | error | (5634) TypeError: Cannot read property 'startsWith' of null
web.0 | 2020-02-29 21:18:41.815 | error | (5634) uncaught exception: Cannot read property 'startsWith' of null
```

**Comment by foxriver76** [comment]
This should be fixed by https://github.com/ioBroker/ioBroker.js-controller/commit/337e8493cae446c951e202715ed20165632d4d03

**Comment by Apollon77** [comment]
I added some more checks also in other methods in my local version ... should come soon too, so lets leave open
