### ISSUE TITLE
Upload broken with "scan not supported"

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.js-controller#936]
```
$ ./iob.bat upload info

C:\iobroker>node node_modules/iobroker.js-controller/iobroker.js upload info
C:\iobroker\node_modules\standard-as-callback\built\index.js:6
        throw e;
        ^

ReplyError: Error scan NOT SUPPORTED
    at parseError (C:\iobroker\node_modules\ioredis\node_modules\redis-parser\lib\parser.js:179:12)       
    at parseType (C:\iobroker\node_modules\ioredis\node_modules\redis-parser\lib\parser.js:302:14)        
Emitted 'error' event on ScanStream instance at:
    at C:\iobroker\node_modules\ioredis\built\ScanStream.js:35:22
    at tryCatcher (C:\iobroker\node_modules\standard-as-callback\built\utils.js:11:23)
    at C:\iobroker\node_modules\standard-as-callback\built\index.js:30:51
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  command: {
    name: 'scan',
    args: [ '0', 'MATCH', 'cfg.o.system.host.*', 'COUNT', '500' ]
  }
}
```

**Comment by AlCalzone** [comment]
I forgot to restart...
